/* Flexhub site — i18n + checkout config */
(function () {
  const dict = {
    "en": {
      "skip": "Skip to content",
      "nav.benefits": "What it does",
      "nav.how": "How it works",
      "nav.buy": "Buy",
      "nav.faq": "FAQ",
      "nav.guide": "User guide",
      "how.guideT": "Want every detail?",
      "how.guideP": "The full user guide walks through both modes step by step (USB and wireless), Bluetooth pairing, every remote tab, macros, settings, updates and troubleshooting — with tap-to-try demos.",
      "how.guideCta": "Open the user guide →",
      "nav.cta": "Get Flexhub",
      "lang.label": "Language",
      "hero.eyebrow": "Wi‑Fi hotspot · shortcuts · mouse · light annotate · no app",
      "hero.title": "Old phone, new job — wireless shortcuts, mouse &amp; light touch<br><span class=\"accent\">from the phone you already have.</span>",
      "hero.lead": "Flexhub turns an old phone or tablet into a cheap wireless shortcut panel for your desk PC — plus a trackpad, presenter, signature pad and light annotate tool. Join the flexhub Wi‑Fi hotspot, open the browser — no App Store install for everyday use. Plug Flexhub into the PC over USB (driver-free), then lounge with the phone in hand.",
      "hero.ctaPrimary": "Get Flexhub",
      "hero.ctaSecondary": "See what it can do",
      "hero.m0": "✓ No app for everyday use",
      "hero.m1": "⌘ Custom shortcuts &amp; macros",
      "hero.m2": "◎ Secondary mouse / presenter",
      "hero.m3": "✎ Sign, doodle, PDF annotate",
      "hero.illustCaption": "Flexhub product illustration",
      "chip.noapp": "No app needed",
      "chip.mouse": "Trackpad / presenter",
      "chip.keyboard": "Shortcuts &amp; type",
      "chip.draw": "Light annotate",
      "chip.devices": "Phone · tablet · computer",
      "ben.kicker": "What it does",
      "ben.title": "A portable light tool.",
      "ben.f1t": "Driver-free. Travel-light.",
      "ben.f1p": "Plug Flexhub into the desk PC, join its Wi‑Fi hotspot on the phone you already own, and control from the sofa or a café seat — no bulky edit deck to pack. No downloads or accounts for everyday use; the app is only for occasional firmware updates.",
      "ben.b1t": "Trackpad &amp; wireless presenter",
      "ben.b1p": "Move, click and scroll from across the room. Ideal as a second pointing surface beside a main mouse — or as a simple wireless presenter — not as your only pro pointing device.",
      "ben.b2t": "Shortcuts &amp; macros on the phone",
      "ben.b2p": "Record macros on the Wi‑Fi page, save them to the device, and replay them later as shortcut-like actions — Stream Deck–like shortcuts without buying another deck.",
      "ben.b3t": "Occasional annotate, sign &amp; doodle",
      "ben.b3p": "Great for PDF markup, contract signatures, kids’ doodles and beginner sketches.",
      "dev.title": "Works with what you already have",
      "dev.lead": "Phones, tablets and computers — new or old. That spare phone in the drawer becomes a handy shortcut panel.",
      "dev.phone": "Phones",
      "dev.tablet": "Tablets",
      "dev.computer": "Computers",
      "ben.bonusT": "Little bonus: a spare remote",
      "ben.bonusP": "Remote under the cushions? Your phone can cover simple TV-box taps while you look. Nice to have — Flexhub’s real job is shortcuts, pointing and light touch on the PC.",
      "how.kicker": "How it works",
      "how.title": "Ready in under a minute.",
      "how.lead": "Nothing to download, nothing to sign up for. If you can plug in a USB stick or connect Bluetooth headphones, you're all set.",
      "how.s1t": "Plug it in — or pair it",
      "how.s1p": "Connect Flexhub to the device you want to control with a USB cable, or just power it up and pair it over Bluetooth.",
      "how.s2t": "Open your device",
      "how.s2p": "On your phone, tablet or computer, join the Wi-Fi named flexhub (password build.me) and open http://flexhub.local/ or http://192.168.4.1/ in the browser — no app needed, that's it.",
      "how.s3t": "Shortcuts, point, type, light touch",
      "how.s3p": "Fire macros and key combos, move the pointer, type a few words, or annotate a PDF — switch whenever you like from wherever you’re comfy.",
      "how.noteT": "The only time you need an app: updates",
      "how.noteP": "Every so often we may release improvements for Flexhub. That's the one moment you'll use our app — open it, tap update, done. Day to day, you can forget it exists.",
      "quote.text": "Shortcuts. Point. Type. Light touch — from the phone in your hand.",
      "quote.by": "A portable light tool for everyday non-pro and second-screen setups.",
      "buy.kicker": "Coming soon",
      "buy.title": "One little plug. A spare phone does the rest.",
      "buy.lead": "Flexhub will be available at visualbuild.shop very soon. Pricing and shipping details are on the way — check back shortly!",
      "buy.priceNote": "Price coming soon",
      "buy.cta": "Coming soon",
      "buy.fine": "Secure checkout on visualbuild.shop",
      "faq.kicker": "FAQ",
      "faq.title": "Good questions, quick answers",
      "faq.q0": "Do I need to download an app?",
      "faq.a0": "Not for everyday use — shortcuts, pointing, typing and light annotate without installing anything. You’ll only need our app when you want to update Flexhub, and that takes a few taps.",
      "faq.q1": "Which devices work?",
      "faq.a1": "Phones, tablets and computers — almost anything with a web browser, old or new. Even a phone that no longer gets updates works great as a wireless shortcut panel — for example, a first-gen Apple iPad mini.",
      "faq.q2": "Can I use it for drawing?",
      "faq.a2": "For light, occasional use — yes: PDF annotate, contract signatures, kids’ doodles and beginner doodles. No pressure levels — not a Wacom tablet.",
      "faq.q3": "Can I switch between mouse, keyboard and drawing?",
      "faq.a3": "Anytime. Fire a shortcut, move the pointer, type a few words, then annotate — all from the same device, with a single tap to switch.",
      "faq.q4": "Do I need to install anything on the device I control?",
      "faq.a4": "Nope. Whether you plug in with a USB cable or pair over Bluetooth, Flexhub shows up as an ordinary mouse and keyboard. An app only comes in on the occasional day you update Flexhub.",
      "faq.q5": "Is it a remote control?",
      "faq.a5": "Only as a little extra. Flexhub is made for shortcuts, pointing and light touch — but if your usual remote goes missing, your phone can help in a pinch.",
      "faq.q6": "Will it change anything on my device?",
      "faq.a6": "No. Your photos, messages and files stay exactly as they are. Flexhub simply gives your device one more way to be useful.",
      "nav.modes": "Two ways to connect",
      "hero.m4": "⇄ USB or Bluetooth · travel-light",
      "chip.modes": "USB · Bluetooth",
      "modes.kicker": "Two ways to connect",
      "modes.title": "Plug it in, or go wireless.",
      "modes.lead": "Flexhub talks to the device you want to control in whichever way suits you. Either way, your phone, tablet or computer is the one in your hand.",
      "modes.usbTag": "With a cable",
      "modes.usbT": "Plug straight in (USB)",
      "modes.usbP": "Connect Flexhub to the computer, screen or TV box you want to control with a USB data cable. It's recognised right away as a mouse and keyboard — nothing to install, nothing to pair.",
      "modes.usbBest": "Great for: your desk computer, a work laptop, anything with a free USB port.",
      "modes.btTag": "Wireless",
      "modes.btT": "Pair over Bluetooth",
      "modes.btP": "Just give Flexhub power — a phone charger or power bank is perfect. About two minutes after power-up, open the Bluetooth settings on the device you want to control and pick “flexhub”. Done!",
      "modes.btBest": "Great for: tablets, TV boxes like Apple TV, and devices without a spare USB port.",
      "modes.tipT": "Flexhub chooses for you",
      "modes.tipP": "When it powers up, Flexhub checks: connected to a device by cable? It works over USB. Only getting power? It switches to Bluetooth. Want to change? Just unplug it and plug it back in the other way.",
      "compare.title": "USB vs Bluetooth — at a glance",
      "compare.lead": "Same sunny control from your phone either way. Here's what each mode brings.",
      "compare.colFeature": "What you get",
      "compare.colUsb": "USB mode",
      "compare.colBt": "Bluetooth mode",
      "compare.r0f": "How it connects",
      "compare.r0u": "USB data cable into the device you want to control",
      "compare.r0b": "Power only, then pair <b>flexhub</b> on that device",
      "compare.r1f": "Keyboard & mouse",
      "compare.r1u": "Yes — shows up right away",
      "compare.r1b": "Yes — as flexhub",
      "compare.r2f": "Gamepad (DualSense & classic BT)",
      "compare.r2u": "Yes — DualSense & classic Bluetooth pads",
      "compare.r2b": "No gamepad in Bluetooth mode",
      "compare.r3f": "Control from your phone's browser",
      "compare.r3u": "Yes — phone / tablet / computer browser",
      "compare.r3b": "Yes — same Wi‑Fi page",
      "compare.r4f": "At power-up",
      "compare.r4": "Auto — data cable ready? USB. Only power? Bluetooth. Unplug and replug to switch.",
      "faq.q7": "USB or Bluetooth — which should I choose?",
      "faq.a7": "Whatever is easiest! Got a free USB port? Plug in and you're done. No port, or controlling a tablet or TV box? Power Flexhub from a charger and pair it over Bluetooth. Tip: pair it on the device you want to control — not on the phone in your hand.",
      "faq.q8": "How do I connect over Wi‑Fi?",
      "faq.a8": "On your phone, tablet or computer, join the Wi‑Fi named flexhub (password build.me), then open http://flexhub.local/ or http://192.168.4.1/ in the browser. That wireless hotspot is how Flexhub talks to the device in your hand — no App Store install for everyday use.",
      "faq.a11": "Yes. On the Flexhub Wi‑Fi page you can record macros, save them to the device, and replay them later as shortcut-like actions.",
      "faq.q11": "Can I set my own shortcut keys and macros?",
      "faq.a10": "No — and we say that up front. Flexhub has no pressure levels. It shines as a light trackpad, wireless presenter, signature pad, multimedia shortcut controller, and macros from key combos for Stream Deck–like shortcuts.",
      "faq.q10": "Can it replace my Wacom tablet?",
      "foot.privacy": "Privacy",
      "foot.terms": "Terms",
      "foot.refund": "Refunds",
      "foot.shipping": "Shipping",
      "foot.contact": "Contact & imprint",
      "foot.copy": "© 2026 Flexhub · visualbuild.shop",
      "brand.tag": "Wi‑Fi hotspot remote",
      "a11y.nav": "Primary",
      "a11y.lang": "Language",
      "a11y.illust": "Flexhub product illustration",
      "a11y.illustAlt": "Flexhub — a small white plug with red accents that turns your phone, tablet or computer into a mouse, keyboard and drawing pad",
      "a11y.compare": "USB versus Bluetooth comparison",
    },
    "zh": {
      "skip": "跳到正文",
      "nav.benefits": "能做什么",
      "nav.how": "怎么用",
      "nav.buy": "购买",
      "nav.faq": "常见问题",
      "nav.guide": "使用说明",
      "how.guideT": "想了解更多细节？",
      "how.guideP": "完整使用说明分别讲解 USB 模式和无线模式的完整流程、蓝牙配对、每个遥控标签、宏、设置、升级和常见问题处理——还能点一点试用。",
      "how.guideCta": "打开使用说明 →",
      "nav.cta": "获取 Flexhub",
      "lang.label": "语言",
      "hero.eyebrow": "无线热点 · 快捷键 · 鼠标 · 轻度批注 · 无需 App",
      "hero.title": "旧手机新用途 — 无线快捷键、鼠标与轻度触控<br><span class=\"accent\">用现成手机就能上手。</span>",
      "hero.lead": "Flexhub 把闲置手机或平板变成便宜的无线快捷面板，兼顾触控板、演示器、签名板和轻度批注。连上名为 flexhub 的无线热点，用浏览器打开即可——日常不必装应用商店 App。把 Flexhub 免驱插到电脑，人可以窝在沙发上用手机控桌面。",
      "hero.ctaPrimary": "获取 Flexhub",
      "hero.ctaSecondary": "看看它能做什么",
      "hero.m0": "✓ 日常使用无需 App",
      "hero.m1": "⌘ 自定义快捷键与宏",
      "hero.m2": "◎ 副鼠标 / 演示器",
      "hero.m3": "✎ 签名、涂鸦、PDF 批注",
      "hero.illustCaption": "Flexhub 产品示意图",
      "chip.noapp": "无需 App",
      "chip.mouse": "触控板 / 演示",
      "chip.keyboard": "快捷键与打字",
      "chip.draw": "轻度批注",
      "chip.devices": "手机 · 平板 · 电脑",
      "ben.kicker": "能做什么",
      "ben.title": "随身的轻量工具",
      "ben.f1t": "免驱，出行轻便",
      "ben.f1p": "把 Flexhub 插到电脑，用现成的手机连上它的无线热点，就能在沙发或咖啡馆控桌面——不用再背一块笨重的剪辑键盘。日常免下载、免账号；只有偶尔升级固件才需要 App。",
      "ben.b1t": "触控板与无线演示",
      "ben.b1p": "隔着房间也能移动、点击、滚动。适合当主鼠标旁边的第二块触控面，或简单无线演示器——而不是你唯一的专业定点设备。",
      "ben.b2t": "手机上的快捷键与宏",
      "ben.b2p": "可以在无线热点页面录制宏，保存到设备后回放执行类似快捷键的操作——不必再买一块专用键台。",
      "ben.b3t": "偶尔批注、签名与涂鸦",
      "ben.b3p": "适合 PDF 圈画、合同签名、孩子涂鸦和入门涂鸦。",
      "dev.title": "你手边的设备就能用",
      "dev.lead": "手机、平板、电脑，新旧都行。抽屉里那部闲置手机，正好当个快捷面板。",
      "dev.phone": "手机",
      "dev.tablet": "平板",
      "dev.computer": "电脑",
      "ben.bonusT": "小彩蛋：备用遥控",
      "ben.bonusP": "遥控器掉进沙发缝？找的时候手机可以先应付电视盒子的简单操作。有它挺好——Flexhub 真正擅长的是快捷键、指点和轻度触控。",
      "how.kicker": "怎么用",
      "how.title": "一分钟就能用上。",
      "how.lead": "不用下载，不用注册，没有复杂设置。会插 U 盘、会连蓝牙耳机，就会用 Flexhub。",
      "how.s1t": "插上，或者配对",
      "how.s1p": "用 USB 数据线把 Flexhub 连到你想控制的设备；或者只给它通电，再通过蓝牙配对。",
      "how.s2t": "打开你的设备",
      "how.s2p": "在手机、平板或电脑上连接名为 flexhub 的 Wi-Fi（密码 build.me），浏览器打开 http://flexhub.local/ 或 http://192.168.4.1/——无需 App，就这么简单。",
      "how.s3t": "快捷键、指点、打字、轻度触控",
      "how.s3p": "触发宏和组合键、移动指针、打几个字，或给 PDF 批注——随时切换，怎么舒服怎么来。",
      "how.noteT": "唯一需要 App 的时候：升级",
      "how.noteP": "我们会不定期为 Flexhub 带来新改进。只有这时才需要用到我们的 App——打开、点一下升级，就完成了。平时你完全可以忘了它。",
      "quote.text": "快捷键。指点。打字。轻度触控——全在你手里的手机上。",
      "quote.by": "面向日常非专业与第二屏幕场景的随身轻量工具。",
      "buy.kicker": "即将上市",
      "buy.title": "一个小插头，旧手机做其余的事。",
      "buy.lead": "Flexhub 即将在 visualbuild.shop 上架。价格与配送信息马上公布——敬请期待！",
      "buy.priceNote": "价格即将公布",
      "buy.cta": "即将开售",
      "buy.fine": "在 visualbuild.shop 安全结账",
      "faq.kicker": "常见问题",
      "faq.title": "好问题，简单答",
      "faq.q0": "需要下载 App 吗？",
      "faq.a0": "日常完全不需要——快捷键、指点、打字和轻度批注都不用装任何东西。只有想升级 Flexhub 时才需要我们的 App，点几下就好。",
      "faq.q1": "哪些设备可以用？",
      "faq.a1": "手机、平板和电脑都可以——几乎所有带浏览器的设备，新旧都行。即使是不再更新系统的旧手机，也很适合当无线快捷面板。例如 Apple iPad mini 第一代。",
      "faq.q2": "能用来画画吗？",
      "faq.a2": "轻度、偶尔用可以：PDF 批注、合同签名、孩子涂鸦、入门涂鸦。没有压感——不是 Wacom 数位板。",
      "faq.q3": "鼠标、键盘、手绘板可以随时切换吗？",
      "faq.a3": "随时可以。先触发快捷键，再挪指针、打几个字，再批注两笔——同一台设备，轻点切换。",
      "faq.q4": "被控制的设备需要安装什么吗？",
      "faq.a4": "不需要。无论用 USB 数据线插上，还是通过蓝牙配对，Flexhub 都会被识别为普通的鼠标和键盘。只有偶尔升级 Flexhub 时才会用到 App。",
      "faq.q5": "它是遥控器吗？",
      "faq.a5": "只是顺带的小功能。Flexhub 主要为快捷键、指点和轻度触控——不过原来的遥控器找不到时，手机也能临时帮上忙。",
      "faq.q6": "会改动我设备里的东西吗？",
      "faq.a6": "不会。照片、聊天记录和文件都原样保留。Flexhub 只是让你的设备多一种用处。",
      "nav.modes": "两种连接方式",
      "hero.m4": "⇄ USB 或蓝牙 · 出行轻便",
      "chip.modes": "USB · 蓝牙",
      "modes.kicker": "两种连接方式",
      "modes.title": "插上就用，或者无线连接。",
      "modes.lead": "Flexhub 可以用你喜欢的方式连接想要控制的设备。不管哪种方式，你手里拿的都是自己的手机、平板或电脑。",
      "modes.usbTag": "有线",
      "modes.usbT": "直接插上（USB）",
      "modes.usbP": "用 USB 数据线把 Flexhub 连到你想控制的电脑、屏幕或电视盒子上，它会立刻被识别为鼠标和键盘——不用安装，也不用配对。",
      "modes.usbBest": "适合：台式电脑、办公笔记本，以及任何有空闲 USB 口的设备。",
      "modes.btTag": "无线",
      "modes.btT": "蓝牙配对",
      "modes.btP": "只要给 Flexhub 通上电——手机充电头或充电宝都行。通电约两分钟后，在想控制的设备上打开蓝牙设置，选择「flexhub」，就好了！",
      "modes.btBest": "适合：平板、Apple TV 等电视盒子，以及没有空闲 USB 口的设备。",
      "modes.tipT": "Flexhub 会自动选择",
      "modes.tipP": "每次通电时，Flexhub 会先看一看：用数据线连着设备？那就走 USB。只是在充电？那就切换到蓝牙。想换一种方式？拔下来，换种方式重新插上就行。",
      "compare.title": "USB 与蓝牙一览",
      "compare.lead": "两种方式都能用手机开心地遥控。下面一眼看清差别。",
      "compare.colFeature": "你能得到什么",
      "compare.colUsb": "USB 模式",
      "compare.colBt": "蓝牙模式",
      "compare.r0f": "怎么连上",
      "compare.r0u": "用 USB 数据线插到想控制的设备上",
      "compare.r0b": "只供电，然后在目标设备上配对 <b>flexhub</b>",
      "compare.r1f": "键盘与鼠标",
      "compare.r1u": "有 — 插上就能用",
      "compare.r1b": "有 — 设备名 flexhub",
      "compare.r2f": "手柄（DualSense 与经典蓝牙）",
      "compare.r2u": "有 — DualSense 与经典蓝牙手柄",
      "compare.r2b": "蓝牙模式不支持手柄",
      "compare.r3f": "用手机浏览器遥控",
      "compare.r3u": "有 — 手机 / 平板 / 电脑浏览器",
      "compare.r3b": "有 — 同一个 Wi‑Fi 页面",
      "compare.r4f": "通电时",
      "compare.r4": "自动选择 — 数据线已就绪？走 USB。只供电？走蓝牙。想换方式？拔掉换种接法再通电。",
      "faq.q7": "USB 和蓝牙，该选哪个？",
      "faq.a7": "哪个方便选哪个！有空闲 USB 口？插上就好。没有 USB 口，或者要控制平板、电视盒子？用充电头给 Flexhub 供电，再用蓝牙配对。小提示：要在被控制的设备上配对，而不是在你手里的手机上。",
      "faq.q8": "怎么用 Wi‑Fi 连接？",
      "faq.a8": "在手机、平板或电脑上连接名为 flexhub 的 Wi‑Fi（密码 build.me），然后在浏览器打开 http://flexhub.local/ 或 http://192.168.4.1/。这个无线热点就是 Flexhub 和你手里设备对话的方式—日常使用不必装应用商店 App。",
      "faq.a11": "可以。在 Flexhub 无线热点页面可以录制宏，保存到设备后回放执行类似快捷键的操作。",
      "faq.q11": "可以自定义快捷键和宏吗？",
      "faq.a10": "不能——我们把话说在前面。Flexhub 没有压感等级。它擅长的是：轻触控板、无线演示器、签名板、多媒体快捷控制器，以及用组合键录制的宏来做类似 Stream Deck 的快捷操作。",
      "faq.q10": "能替代我的 Wacom 数位板吗？",
      "foot.privacy": "隐私政策",
      "foot.terms": "销售与使用条款",
      "foot.refund": "退款与退货",
      "foot.shipping": "配送",
      "foot.contact": "联系与经营者信息",
      "foot.copy": "© 2026 Flexhub · visualbuild.shop",
      "brand.tag": "Wi‑Fi 热点遥控",
      "a11y.nav": "主导航",
      "a11y.lang": "语言",
      "a11y.illust": "Flexhub 产品插图",
      "a11y.illustAlt": "Flexhub — 一个带红色点缀的白色小插头，让你的手机、平板或电脑变成鼠标、键盘和绘图板",
      "a11y.compare": "USB 与蓝牙对比",
    },
    "de": {
      "skip": "Zum Inhalt springen",
      "nav.benefits": "Funktionen",
      "nav.how": "So geht's",
      "nav.buy": "Kaufen",
      "nav.faq": "FAQ",
      "nav.guide": "Anleitung",
      "how.guideT": "Willst du jedes Detail?",
      "how.guideP": "Die vollständige Bedienungsanleitung geht Schritt für Schritt durch beide Modi (USB und Wireless), Bluetooth-Kopplung, jede Remote-Registerkarte, Makros, Einstellungen, Updates und Fehlerbehebung — mit Tap-to-Try-Demos.",
      "how.guideCta": "Öffnen Sie das Benutzerhandbuch →",
      "nav.cta": "Flexhub holen",
      "lang.label": "Sprache",
      "hero.eyebrow": "Wi‑Fi Hotspot · Shortcuts · Maus · Light Annotate · keine App",
      "hero.title": "Altes Telefon, neuer Job — drahtlose Verknüpfungen, Maus &amp; leichte Berührung<br><span class=\"accent\">von dem Telefon, das Sie bereits haben.</span>",
      "hero.lead": "Flexhub verwandelt ein altes Telefon oder Tablet in ein günstiges drahtloses Verknüpfungsfeld für Ihren Schreibtisch-PC — plus Trackpad, Präsentator, Signatur-Pad und leichtes Anmerkungs-Tool. Treten Sie dem flexhub Wi‑Fi Hotspot bei, öffnen Sie den Browser — keine App Store-Installation für den täglichen Gebrauch. Schließen Sie Flexhub über USB (fahrerlos) an den PC an und entspannen Sie sich dann mit dem Telefon in der Hand.",
      "hero.ctaPrimary": "Flexhub holen",
      "hero.ctaSecondary": "Was es kann",
      "hero.m0": "✓ Keine App für den täglichen Gebrauch",
      "hero.m1": "⌘ Benutzerdefinierte Verknüpfungen &amp; Makros",
      "hero.m2": "◎ Zweitmaus / Moderator",
      "hero.m3": "✎ Unterschreiben, kritzeln, PDFs kommentieren",
      "hero.illustCaption": "Flexhub Produktabbildung",
      "chip.noapp": "Keine App erforderlich",
      "chip.mouse": "Trackpad / Moderator",
      "chip.keyboard": "Verknüpfungen &amp; Typ",
      "chip.draw": "Leichte Anmerkungen",
      "chip.devices": "Telefon · Tablet · Computer",
      "ben.kicker": "Was es macht",
      "ben.title": "Ein tragbares Lichtwerkzeug.",
      "ben.f1t": "Fahrerfrei. Reiselicht.",
      "ben.f1p": "Schließen Sie Flexhub an den Schreibtisch-PC an, verbinden Sie den Wi‑Fi-Hotspot mit dem Telefon, das Sie bereits besitzen, und steuern Sie vom Sofa oder einem Café-Sitzplatz aus — kein sperriges Edit-Deck zum Packen. Keine Downloads oder Accounts für den täglichen Gebrauch; die App ist nur für gelegentliche Firmware-Updates gedacht.",
      "ben.b1t": "Trackpad &amp; Wireless Presenter",
      "ben.b1p": "Bewegen, klicken und scrollen Sie quer durch den Raum. Ideal als zweite Zeigefläche neben einer Hauptmaus — oder als einfacher drahtloser Präsentator — nicht als einziges Profi-Zeigegerät.",
      "ben.b2t": "Verknüpfungen &amp; Makros am Telefon",
      "ben.b2p": "Zeichnen Sie Makros auf der Wi‑Fi-Seite auf, speichern Sie sie auf dem Gerät und geben Sie sie später als Verknüpfungsaktionen wieder — Stream Deck-ähnliche Verknüpfungen, ohne ein weiteres Deck zu kaufen.",
      "ben.b3t": "Gelegentliche Anmerkungen, Unterschriften &amp; Kritzeleien",
      "ben.b3p": "Ideal für PDF Markup, Vertragsunterschriften, Kinderkritzeleien und Anfänger-Skizzen.",
      "dev.title": "Funktioniert mit dem, was Sie bereits haben",
      "dev.lead": "Handys, Tablets und Computer — neu oder alt. Das Ersatztelefon in der Schublade wird zu einem praktischen Verknüpfungsfeld.",
      "dev.phone": "Telefone",
      "dev.tablet": "Tabletten",
      "dev.computer": "Computer",
      "ben.bonusT": "Kleiner Bonus: eine Ersatzfernbedienung",
      "ben.bonusP": "Fernbedienung unter den Kissen? Ihr Telefon kann einfache TV-Box-Tipps abdecken, während Sie schauen. Nice to have — Flexhubs eigentliche Aufgabe sind Verknüpfungen, Zeigen und leichte Berührungen am PC.",
      "how.kicker": "So funktioniert es",
      "how.title": "In weniger als einer Minute fertig.",
      "how.lead": "Nichts zum Herunterladen, nichts zum Anmelden. Wenn Sie einen USB-Stick anschließen oder Bluetooth-Kopfhörer anschließen können, sind Sie startklar.",
      "how.s1t": "Schließen Sie es an — oder koppeln Sie es",
      "how.s1p": "Verbinden Sie Flexhub mit dem Gerät, das Sie mit einem USB-Kabel steuern möchten, oder schalten Sie es einfach ein und koppeln Sie es über Bluetooth.",
      "how.s2t": "Öffnen Sie Ihr Gerät",
      "how.s2p": "Schließen Sie sich auf Ihrem Telefon, Tablet oder Computer dem Wi-Fi mit dem Namen flexhub (Passwort build.me) an und öffnen Sie http://flexhub.local/ oder http://192.168.4.1/ im Browser — keine App erforderlich, das war 's.",
      "how.s3t": "Tastenkombinationen, Punkt, Typ, leichte Berührung",
      "how.s3p": "Feuern Sie Makros und Tastenkombinationen ab, bewegen Sie den Zeiger, tippen Sie ein paar Wörter oder kommentieren Sie einen PDF — wechseln Sie, wann immer Sie möchten, von wo immer Sie es bequem haben.",
      "how.noteT": "Die einzige Zeit, in der Sie eine App benötigen: Updates",
      "how.noteP": "Ab und zu können wir Verbesserungen für Flexhub veröffentlichen. Das ist der eine Moment, in dem du unsere App nutzen wirst — öffne sie, tippe auf Update, fertig. Tag für Tag kann man vergessen, dass es sie gibt.",
      "quote.text": "Verknüpfungen. Punkt. Typ. Leichte Berührung — vom Telefon in der Hand.",
      "quote.by": "Ein tragbares Lichtwerkzeug für alltägliche, nicht-professionelle und Second-Screen-Setups.",
      "buy.kicker": "Demnächst",
      "buy.title": "Ein kleiner Stecker. Ein Ersatztelefon erledigt den Rest.",
      "buy.lead": "Flexhub wird in Kürze bei visualbuild.shop verfügbar sein. Preis- und Versanddetails sind auf dem Weg — schau in Kürze wieder vorbei!",
      "buy.priceNote": "Preis folgt in Kürze",
      "buy.cta": "Demnächst",
      "buy.fine": "Sicherer Check-out am visualbuild.shop",
      "faq.kicker": "FAQ",
      "faq.title": "Gute Fragen, schnelle Antworten",
      "faq.q0": "Muss ich eine App herunterladen?",
      "faq.a0": "Nicht für den täglichen Gebrauch — Verknüpfungen, Zeigen, Tippen und leichte Anmerkungen, ohne etwas zu installieren. Du brauchst unsere App nur, wenn du Flexhub aktualisieren möchtest, und das dauert nur ein paar Fingertipps.",
      "faq.q1": "Welche Geräte funktionieren?",
      "faq.a1": "Handys, Tablets und Computer — fast alles mit einem Webbrowser, alt oder neu. Selbst ein Telefon, das keine Updates mehr erhält, funktioniert hervorragend als drahtloses Verknüpfungsfeld — zum Beispiel ein Apple iPad mini der ersten Generation.",
      "faq.q2": "Kann ich es zum Zeichnen verwenden?",
      "faq.a2": "Für leichten, gelegentlichen Gebrauch — ja: PDF Anmerkungen, Vertragsunterschriften, Kinderkritzeleien und Anfängerkritzeleien. Keine Druckstufen — keine Wacom-Tablette.",
      "faq.q3": "Kann ich zwischen Maus, Tastatur und Zeichnung wechseln?",
      "faq.a3": "Jederzeit. Feuern Sie eine Verknüpfung, bewegen Sie den Zeiger, geben Sie ein paar Wörter ein und kommentieren Sie dann — alles vom selben Gerät aus, mit einem einzigen Tippen zum Umschalten.",
      "faq.q4": "Muss ich etwas auf dem Gerät installieren, das ich kontrolliere?",
      "faq.a4": "Nein. Egal, ob Sie sich mit einem USB-Kabel anschließen oder über Bluetooth koppeln, Flexhub wird als gewöhnliche Maus und Tastatur angezeigt. Eine App kommt nur an dem gelegentlichen Tag, an dem Sie Flexhub aktualisieren.",
      "faq.q5": "Handelt es sich um eine Fernbedienung?",
      "faq.a5": "Nur als kleines Extra. Flexhub ist für Verknüpfungen, Zeigen und leichte Berührung gedacht — aber wenn Ihre übliche Fernbedienung verschwindet, kann Ihr Telefon im Notfall helfen.",
      "faq.q6": "Wird sich dadurch etwas auf meinem Gerät ändern?",
      "faq.a6": "Nein. Ihre Fotos, Nachrichten und Dateien bleiben genau so, wie sie sind. Flexhub gibt Ihrem Gerät einfach eine weitere Möglichkeit, nützlich zu sein.",
      "nav.modes": "Zwei Verbindungsarten",
      "hero.m4": "⇄ USB oder Bluetooth · Reiseleuchte",
      "chip.modes": "USB · Bluetooth",
      "modes.kicker": "Zwei Möglichkeiten, eine Verbindung herzustellen",
      "modes.title": "Schließen Sie es an oder gehen Sie drahtlos.",
      "modes.lead": "Flexhub spricht mit dem Gerät, das Sie steuern möchten, je nachdem, wie es Ihnen passt. So oder so, Ihr Telefon, Tablet oder Computer ist derjenige in Ihrer Hand.",
      "modes.usbTag": "Mit einem Kabel",
      "modes.usbT": "Gerade einstecken (USB)",
      "modes.usbP": "Verbinden Sie Flexhub mit dem Computer, Bildschirm oder der TV-Box, die Sie mit einem USB-Datenkabel steuern möchten. Es wird sofort als Maus und Tastatur erkannt — nichts zu installieren, nichts zu koppeln.",
      "modes.usbBest": "Ideal für: Ihren Schreibtischcomputer, einen Arbeitslaptop, alles mit einem kostenlosen USB-Anschluss.",
      "modes.btTag": "Drahtlos",
      "modes.btT": "Koppeln über Bluetooth",
      "modes.btP": "Geben Sie einfach Flexhub Power — ein Handy-Ladegerät oder eine Powerbank ist perfekt. Etwa zwei Minuten nach dem Einschalten öffnen Sie die Bluetooth-Einstellungen auf dem Gerät, das Sie steuern möchten, und wählen Sie „flexhub“. Fertig!",
      "modes.btBest": "Ideal für: Tablets, TV-Boxen wie Apple TV und Geräte ohne Ersatzanschluss USB.",
      "modes.tipT": "Flexhub wählt für Sie",
      "modes.tipP": "Wenn es hochfährt, prüft Flexhub: über Kabel mit einem Gerät verbunden? Es funktioniert über USB. Nur Strom bekommen? Es wechselt zu Bluetooth. Möchten Sie es ändern? Ziehen Sie einfach den Stecker aus der Steckdose und stecken Sie es in die andere Richtung wieder ein.",
      "compare.title": "USB vs Bluetooth — auf einen Blick",
      "compare.lead": "Die gleiche sonnige Steuerung von Ihrem Telefon aus. Hier ist, was jeder Modus bringt.",
      "compare.colFeature": "Was du bekommst",
      "compare.colUsb": "USB-Modus",
      "compare.colBt": "Bluetooth-Modus",
      "compare.r0f": "So verbindet es sich",
      "compare.r0u": "USB Datenkabel in das Gerät, das Sie steuern möchten",
      "compare.r0b": "Nur Strom, dann koppeln Sie <b>flexhub</b> auf diesem Gerät",
      "compare.r1f": "Tastatur & Maus",
      "compare.r1u": "Ja — taucht sofort auf",
      "compare.r1b": "Ja — als flexhub",
      "compare.r2f": "Gamepad (DualSense & Classic BT)",
      "compare.r2u": "Ja — DualSense & klassische Bluetooth-Pads",
      "compare.r2b": "Kein Gamepad im Bluetooth-Modus",
      "compare.r3f": "Steuerung über den Browser Ihres Telefons",
      "compare.r3u": "Ja — Telefon- / Tablet- / Computer-Browser",
      "compare.r3b": "Ja — gleiche Wi‑Fi Seite",
      "compare.r4f": "Beim Einschalten",
      "compare.r4": "Auto — Datenkabel bereit? USB. Nur Strom? Bluetooth. Ziehen Sie den Netzstecker und schließen Sie ihn erneut an, um den Schalter",
      "faq.q7": "USB oder Bluetooth — was soll ich wählen?",
      "faq.a7": "Was ist am einfachsten? Hast du einen kostenlosen USB-Port? Schließen Sie sich an und Sie sind fertig. Kein Anschluss oder Steuerung eines Tablets oder einer TV-Box? Versorgen Sie Flexhub mit einem Ladegerät und koppeln Sie es über Bluetooth. Tipp: Koppeln Sie es auf dem Gerät, das Sie steuern möchten — nicht auf dem Telefon in Ihrer Hand.",
      "faq.q8": "Wie verbinde ich mich über Wi‑Fi?",
      "faq.a8": "Schließen Sie sich auf Ihrem Telefon, Tablet oder Computer dem Wi‑Fi mit dem Namen flexhub (Passwort build.me) an und öffnen Sie dann http://flexhub.local/ oder http://192.168.4.1/ im Browser. Dieser drahtlose Hotspot ist die Art und Weise, wie Flexhub mit dem Gerät in Ihrer Hand spricht — keine App Store-Installation für den täglichen Gebrauch.",
      "faq.a11": "Ja. Auf der Seite Flexhub Wi‑Fi können Sie Makros aufnehmen, auf dem Gerät speichern und später als Verknüpfungsaktionen wiedergeben.",
      "faq.q11": "Kann ich meine eigenen Tastenkombinationen und Makros festlegen?",
      "faq.a10": "Nein — und das sagen wir im Voraus. Flexhub hat keine Druckstufen. Es glänzt als leichtes Trackpad, drahtloser Präsentator, Signaturpad, Multimedia-Verknüpfungs-Controller und Makros aus Tastenkombinationen für Stream Deck-ähnliche Verknüpfungen.",
      "faq.q10": "Kann es mein Wacom-Tablet ersetzen?",
      "foot.privacy": "Datenschutz",
      "foot.terms": "AGB",
      "foot.refund": "Erstattungen",
      "foot.shipping": "Versand",
      "foot.contact": "Kontakt & Impressum",
      "foot.copy": "© 2026 Flexhub · visualbuild.shop",
      "brand.tag": "Wi‑Fi-Hotspot-Fernbedienung",
      "a11y.nav": "Hauptnavigation",
      "a11y.lang": "Sprache",
      "a11y.illust": "Flexhub-Produktillustration",
      "a11y.illustAlt": "Flexhub — ein kleiner weißer Stecker mit roten Akzenten, der dein Handy, Tablet oder deinen Computer zu Maus, Tastatur und Zeichenfläche macht",
      "a11y.compare": "Vergleich USB und Bluetooth",
    },
    "fr": {
      "skip": "Aller au contenu",
      "nav.benefits": "Ce que ça fait",
      "nav.how": "Comment ça marche",
      "nav.buy": "Acheter",
      "nav.faq": "FAQ",
      "nav.guide": "Guide",
      "how.guideT": "Envie de tous les détails ?",
      "how.guideP": "Le guide complet parcourt les deux modes pas à pas (USB et sans fil), l'appairage Bluetooth, chaque onglet de la télécommande, les macros, les réglages, les mises à jour et le dépannage — avec des démos à essayer.",
      "how.guideCta": "Ouvrir le guide →",
      "nav.cta": "Obtenir Flexhub",
      "lang.label": "Langue",
      "hero.eyebrow": "Hotspot Wi‑Fi · raccourcis · souris · annotation légère · sans app",
      "hero.title": "Ancien téléphone, nouveau rôle — raccourcis sans fil, souris et toucher léger<br><span class=\"accent\">avec le téléphone que vous avez déjà.</span>",
      "hero.lead": "Flexhub transforme un vieux téléphone ou une tablette en panneau de raccourcis sans fil pour le PC du bureau — plus trackpad, présentateur, pad de signature et outil d'annotation légère. Rejoignez le hotspot Wi‑Fi flexhub, ouvrez le navigateur — pas d'installation App Store au quotidien. Branchez Flexhub en USB (sans pilote), puis pilotez depuis le canapé.",
      "hero.ctaPrimary": "Obtenir Flexhub",
      "hero.ctaSecondary": "Voir ce qu'il peut faire",
      "hero.m0": "✓ Pas d'app au quotidien",
      "hero.m1": "⌘ Raccourcis et macros perso",
      "hero.m2": "◎ Souris secondaire / présentateur",
      "hero.m3": "✎ Signer, gribouiller, annoter un PDF",
      "hero.illustCaption": "Illustration produit Flexhub",
      "chip.noapp": "Sans app",
      "chip.mouse": "Trackpad / présentateur",
      "chip.keyboard": "Raccourcis et saisie",
      "chip.draw": "Annotation légère",
      "chip.devices": "Téléphone · tablette · ordinateur",
      "ben.kicker": "Ce que ça fait",
      "ben.title": "Un outil léger et portable.",
      "ben.f1t": "Sans pilote. Léger en voyage.",
      "ben.f1p": "Branchez Flexhub sur le PC, rejoignez son hotspot Wi‑Fi avec le téléphone que vous avez déjà, et contrôlez depuis le canapé ou un café — sans deck d'édition encombrant. Pas de téléchargement ni de compte au quotidien ; l'app sert seulement aux mises à jour firmware occasionnelles.",
      "ben.b1t": "Trackpad et présentateur sans fil",
      "ben.b1p": "Bougez, cliquez et faites défiler à distance. Idéal comme second pointeur à côté de la souris principale — ou comme présentateur simple — pas comme seul périphérique pro.",
      "ben.b2t": "Raccourcis et macros sur le téléphone",
      "ben.b2p": "Enregistrez des macros sur la page Wi‑Fi, enregistrez-les sur l'appareil, puis rejouez-les comme des raccourcis — style Stream Deck sans racheter un deck.",
      "ben.b3t": "Annoter, signer et gribouiller de temps en temps",
      "ben.b3p": "Parfait pour annoter un PDF, signer un contrat, les gribouillis des enfants et les croquis débutants.",
      "dev.title": "Fonctionne avec ce que vous avez déjà",
      "dev.lead": "Téléphones, tablettes et ordinateurs — neufs ou anciens. Ce téléphone au fond du tiroir devient un panneau de raccourcis pratique.",
      "dev.phone": "Téléphones",
      "dev.tablet": "Tablettes",
      "dev.computer": "Ordinateurs",
      "ben.bonusT": "Petit bonus : une télécommande de secours",
      "ben.bonusP": "Télécommande sous les coussins ? Votre téléphone peut couvrir quelques appuis simples sur le box TV pendant que vous cherchez. Sympa à avoir — le vrai métier de Flexhub, ce sont les raccourcis, le pointage et le toucher léger sur le PC.",
      "how.kicker": "Comment ça marche",
      "how.title": "Prêt en moins d'une minute.",
      "how.lead": "Rien à télécharger, rien à créer. Si vous savez brancher une clé USB ou appairer des écouteurs Bluetooth, vous êtes prêt.",
      "how.s1t": "Branchez — ou appairer",
      "how.s1p": "Connectez Flexhub à l'appareil à contrôler avec un câble USB, ou alimentez-le simplement et appairer en Bluetooth.",
      "how.s2t": "Ouvrez votre appareil",
      "how.s2p": "Sur votre téléphone, tablette ou ordinateur, rejoignez le Wi‑Fi nommé flexhub (mot de passe build.me) et ouvrez http://flexhub.local/ ou http://192.168.4.1/ dans le navigateur — pas d'app, c'est tout.",
      "how.s3t": "Raccourcis, pointer, taper, toucher léger",
      "how.s3p": "Lancez macros et combos, déplacez le pointeur, tapez quelques mots, ou annotez un PDF — changez quand vous voulez, où vous êtes à l'aise.",
      "how.noteT": "Le seul moment où il faut une app : les mises à jour",
      "how.noteP": "De temps en temps, nous pouvons publier des améliorations pour Flexhub. C'est le seul moment où vous utiliserez notre app — ouvrez, appuyez sur mettre à jour, terminé. Au quotidien, vous pouvez l'oublier.",
      "quote.text": "Raccourcis. Pointer. Taper. Toucher léger — depuis le téléphone dans votre main.",
      "quote.by": "Un outil léger et portable pour le quotidien non pro et les seconds écrans.",
      "buy.kicker": "Bientôt disponible",
      "buy.title": "Une petite prise. Un vieux téléphone fait le reste.",
      "buy.lead": "Flexhub sera bientôt disponible sur visualbuild.shop. Prix et livraison arrivent — revenez bientôt !",
      "buy.priceNote": "Prix bientôt annoncé",
      "buy.cta": "Bientôt",
      "buy.fine": "Paiement sécurisé sur visualbuild.shop",
      "faq.kicker": "FAQ",
      "faq.title": "Bonnes questions, réponses rapides",
      "faq.q0": "Faut-il télécharger une app ?",
      "faq.a0": "Pas pour le quotidien — raccourcis, pointage, saisie et annotation légère sans rien installer. Vous n'aurez besoin de notre app que pour mettre à jour Flexhub, en quelques taps.",
      "faq.q1": "Quels appareils fonctionnent ?",
      "faq.a1": "Téléphones, tablettes et ordinateurs — presque tout avec un navigateur, neuf ou ancien. Même un téléphone qui ne reçoit plus de mises à jour marche très bien comme panneau de raccourcis — par exemple un iPad mini de première génération.",
      "faq.q2": "Puis-je l'utiliser pour dessiner ?",
      "faq.a2": "Pour un usage léger et occasionnel — oui : annoter un PDF, signer un contrat, gribouillis d'enfants et croquis débutants. Pas de niveaux de pression — ce n'est pas une tablette Wacom.",
      "faq.q3": "Puis-je passer de souris, clavier et dessin ?",
      "faq.a3": "À tout moment. Lancez un raccourci, bougez le pointeur, tapez quelques mots, puis annotez — le tout sur le même appareil, en un tap pour changer.",
      "faq.q4": "Faut-il installer quelque chose sur l'appareil contrôlé ?",
      "faq.a4": "Non. Que vous branchiez en USB ou appairiez en Bluetooth, Flexhub apparaît comme une souris et un clavier ordinaires. Une app n'intervient que le jour occasionnel où vous mettez Flexhub à jour.",
      "faq.q5": "Est-ce une télécommande ?",
      "faq.a5": "Seulement en petit plus. Flexhub est fait pour les raccourcis, le pointage et le toucher léger — mais si la télécommande habituelle disparaît, votre téléphone peut dépanner.",
      "faq.q6": "Ça change quelque chose sur mon appareil ?",
      "faq.a6": "Non. Photos, messages et fichiers restent tels quels. Flexhub donne juste une utilité de plus à votre appareil.",
      "nav.modes": "Deux façons de se connecter",
      "hero.m4": "⇄ USB ou Bluetooth · léger en voyage",
      "chip.modes": "USB · Bluetooth",
      "modes.kicker": "Deux façons de se connecter",
      "modes.title": "Branchez, ou passez en sans fil.",
      "modes.lead": "Flexhub parle à l'appareil à contrôler comme vous préférez. Dans les deux cas, c'est votre téléphone, tablette ou ordinateur que vous tenez.",
      "modes.usbTag": "Avec un câble",
      "modes.usbT": "Branchez directement (USB)",
      "modes.usbP": "Connectez Flexhub à l'ordinateur, l'écran ou le box TV à contrôler avec un câble USB données. Il est reconnu tout de suite comme souris et clavier — rien à installer, rien à appairer.",
      "modes.usbBest": "Idéal pour : le PC de bureau, un laptop pro, tout appareil avec un port USB libre.",
      "modes.btTag": "Sans fil",
      "modes.btT": "Appairage Bluetooth",
      "modes.btP": "Alimentez simplement Flexhub — chargeur téléphone ou power bank. Environ deux minutes après la mise sous tension, ouvrez les réglages Bluetooth sur l'appareil à contrôler et choisissez « flexhub ». Et voilà !",
      "modes.btBest": "Idéal pour : tablettes, box TV comme Apple TV, et appareils sans port USB libre.",
      "modes.tipT": "Flexhub choisit pour vous",
      "modes.tipP": "À l'allumage, Flexhub vérifie : câble données vers un appareil ? Mode USB. Seulement de l'alimentation ? Bluetooth. Pour changer : débranchez et rebranchez autrement.",
      "compare.title": "USB vs Bluetooth — en un coup d'œil",
      "compare.lead": "Le même contrôle depuis votre téléphone dans les deux cas. Voici ce qu'apporte chaque mode.",
      "compare.colFeature": "Ce que vous obtenez",
      "compare.colUsb": "Mode USB",
      "compare.colBt": "Mode Bluetooth",
      "compare.r0f": "Comment ça se connecte",
      "compare.r0u": "Câble USB données vers l'appareil à contrôler",
      "compare.r0b": "Alimentation seule, puis appairer <b>flexhub</b> sur cet appareil",
      "compare.r1f": "Clavier et souris",
      "compare.r1u": "Oui — apparaît tout de suite",
      "compare.r1b": "Oui — sous le nom flexhub",
      "compare.r2f": "Manette (DualSense et BT classique)",
      "compare.r2u": "Oui — DualSense et manettes Bluetooth classiques",
      "compare.r2b": "Pas de manette en mode Bluetooth",
      "compare.r3f": "Contrôle depuis le navigateur du téléphone",
      "compare.r3u": "Oui — navigateur téléphone / tablette / ordinateur",
      "compare.r3b": "Oui — même page Wi‑Fi",
      "compare.r4f": "À l'allumage",
      "compare.r4": "Auto — câble données prêt ? USB. Seulement l'alim ? Bluetooth. Débranchez et rebranchez pour changer.",
      "faq.q7": "USB ou Bluetooth — lequel choisir ?",
      "faq.a7": "Le plus simple ! Un port USB libre ? Branchez, c'est fait. Pas de port, ou contrôle d'une tablette / box TV ? Alimentez Flexhub avec un chargeur et appairer en Bluetooth. Astuce : appairer sur l'appareil à contrôler — pas sur le téléphone dans votre main.",
      "faq.q8": "Comment se connecter en Wi‑Fi ?",
      "faq.a8": "Sur votre téléphone, tablette ou ordinateur, rejoignez le Wi‑Fi nommé flexhub (mot de passe build.me), puis ouvrez http://flexhub.local/ ou http://192.168.4.1/ dans le navigateur. Ce hotspot est la façon dont Flexhub parle à l'appareil dans votre main — pas d'App Store au quotidien.",
      "faq.a11": "Oui. Sur la page Wi‑Fi Flexhub vous pouvez enregistrer des macros, les sauver sur l'appareil, et les rejouer plus tard comme des raccourcis.",
      "faq.q11": "Puis-je définir mes propres raccourcis et macros ?",
      "faq.a10": "Non — et on le dit clairement. Flexhub n'a pas de niveaux de pression. Il brille comme trackpad léger, présentateur sans fil, pad de signature, contrôleur multimédia, et macros de combos façon Stream Deck.",
      "faq.q10": "Peut-il remplacer ma tablette Wacom ?",
      "foot.privacy": "Confidentialité",
      "foot.terms": "Conditions",
      "foot.refund": "Remboursements",
      "foot.shipping": "Livraison",
      "foot.contact": "Contact et mentions légales",
      "foot.copy": "© 2026 Flexhub · visualbuild.shop",
      "brand.tag": "Télécommande via hotspot Wi‑Fi",
      "a11y.nav": "Navigation principale",
      "a11y.lang": "Langue",
      "a11y.illust": "Illustration du produit Flexhub",
      "a11y.illustAlt": "Flexhub — une petite prise blanche aux accents rouges qui transforme votre téléphone, tablette ou ordinateur en souris, clavier et surface de dessin",
      "a11y.compare": "Comparaison USB et Bluetooth",
    },
    "ja": {
      "skip": "コンテンツへスキップ",
      "nav.benefits": "できること",
      "nav.how": "使い方",
      "nav.buy": "購入",
      "nav.faq": "よくある質問",
      "nav.guide": "ガイド",
      "how.guideT": "もっと詳しく知りたい？",
      "how.guideP": "完全ガイドでは、USB / ワイヤレスの両モード、Bluetooth ペアリング、リモコンの各タブ、マクロ、設定、更新、トラブルシューティングを手順ごとに案内します。タップして試せるデモ付きです。",
      "how.guideCta": "ガイドを開く →",
      "nav.cta": "Flexhub を入手",
      "lang.label": "言語",
      "hero.eyebrow": "Wi‑Fi ホットスポット · ショートカット · マウス · 軽い注釈 · アプリ不要",
      "hero.title": "古いスマホに新しい仕事を — ワイヤレスショートカット、マウス、軽いタッチ<br><span class=\"accent\">手元のスマホそのままで。</span>",
      "hero.lead": "Flexhub は古いスマホやタブレットを、デスク PC 向けの手頃なワイヤレスショートカットパネルに変えます。トラックパッド、プレゼンター、署名パッド、軽い注釈ツールも。flexhub の Wi‑Fi ホットスポットに接続してブラウザを開くだけ — 日常利用に App Store のインストールは不要。Flexhub を PC に USB（ドライバ不要）で挿し、ソファからスマホで操作できます。",
      "hero.ctaPrimary": "Flexhub を入手",
      "hero.ctaSecondary": "できることを見る",
      "hero.m0": "✓ 日常利用にアプリ不要",
      "hero.m1": "⌘ カスタムショートカットとマクロ",
      "hero.m2": "◎ サブマウス / プレゼンター",
      "hero.m3": "✎ 署名、落書き、PDF 注釈",
      "hero.illustCaption": "Flexhub 製品イラスト",
      "chip.noapp": "アプリ不要",
      "chip.mouse": "トラックパッド / プレゼン",
      "chip.keyboard": "ショートカットと入力",
      "chip.draw": "軽い注釈",
      "chip.devices": "スマホ · タブレット · パソコン",
      "ben.kicker": "できること",
      "ben.title": "持ち運べる軽量ツール。",
      "ben.f1t": "ドライバ不要。旅も軽く。",
      "ben.f1p": "Flexhub をデスク PC に挿し、手元のスマホでその Wi‑Fi ホットスポットに接続すれば、ソファやカフェから操作できます — 大きな編集デッキは不要。日常はダウンロードもアカウントも不要。アプリはたまに行うファームウェア更新のときだけ。",
      "ben.b1t": "トラックパッドとワイヤレスプレゼンター",
      "ben.b1p": "離れた場所から移動・クリック・スクロール。メインマウスの隣の第二ポインタや、シンプルなワイヤレスプレゼンターに最適 — 唯一のプロ用ポインティングデバイスとしては想定していません。",
      "ben.b2t": "スマホ上のショートカットとマクロ",
      "ben.b2p": "Wi‑Fi ページでマクロを録画し、端末に保存して後からショートカットのように再生 — 新しいデッキを買わずに Stream Deck 風の操作ができます。",
      "ben.b3t": "ときどき注釈、署名、落書き",
      "ben.b3p": "PDF の書き込み、契約書の署名、子どもの落書き、入門スケッチにぴったり。",
      "dev.title": "すでに持っている機器で使えます",
      "dev.lead": "スマホ、タブレット、パソコン — 新旧問いません。引き出しの予備スマホが便利なショートカットパネルになります。",
      "dev.phone": "スマホ",
      "dev.tablet": "タブレット",
      "dev.computer": "パソコン",
      "ben.bonusT": "ちょっとしたおまけ：予備リモコン",
      "ben.bonusP": "リモコンがクッションの下？ 探しているあいだ、スマホで TV ボックスの簡単な操作をカバーできます。あると便利 — Flexhub の本業は PC 上のショートカット、ポインタ、軽いタッチです。",
      "how.kicker": "使い方",
      "how.title": "1 分以内に準備完了。",
      "how.lead": "ダウンロードも登録も不要。USB メモリを挿せたり Bluetooth イヤホンを繋げたりできれば大丈夫。",
      "how.s1t": "挿す — またはペアリング",
      "how.s1p": "制御したい機器に USB ケーブルで Flexhub を繋ぐか、電源だけ入れて Bluetooth でペアリングします。",
      "how.s2t": "デバイスを開く",
      "how.s2p": "スマホ、タブレット、パソコンで flexhub という Wi‑Fi（パスワード build.me）に接続し、ブラウザで http://flexhub.local/ または http://192.168.4.1/ を開く — アプリ不要、それで完了。",
      "how.s3t": "ショートカット、ポインタ、入力、軽いタッチ",
      "how.s3p": "マクロやキーコンボを実行し、ポインタを動かし、数語入力し、PDF に注釈 — 居心地のよい場所からいつでも切り替え。",
      "how.noteT": "アプリが必要な唯一の瞬間：更新",
      "how.noteP": "ときどき Flexhub の改善を公開します。そのときだけアプリを使い — 開いて更新をタップすれば完了。日常は忘れても大丈夫。",
      "quote.text": "ショートカット。ポインタ。入力。軽いタッチ — 手元のスマホから。",
      "quote.by": "日常の非プロ用途やサブ画面向けの、持ち運べる軽量ツール。",
      "buy.kicker": "近日公開",
      "buy.title": "小さなプラグひとつ。あとは予備のスマホ。",
      "buy.lead": "Flexhub はまもなく visualbuild.shop で購入できます。価格と配送情報も近日公開 — しばらくしてまたチェックを！",
      "buy.priceNote": "価格は近日発表",
      "buy.cta": "近日公開",
      "buy.fine": "visualbuild.shop で安全に決済",
      "faq.kicker": "よくある質問",
      "faq.title": "よい質問に、短い答え",
      "faq.q0": "アプリのダウンロードは必要？",
      "faq.a0": "日常利用には不要 — ショートカット、ポインタ、入力、軽い注釈は何も入れずに使えます。Flexhub を更新したいときだけアプリが必要で、数タップで済みます。",
      "faq.q1": "どの機器で使える？",
      "faq.a1": "スマホ、タブレット、パソコン — ブラウザがあるものならほぼどれでも、新旧問いません。更新が止まった古いスマホでも、ワイヤレスショートカットパネルとして十分使えます。例：初代 Apple iPad mini。",
      "faq.q2": "お絵かきに使える？",
      "faq.a2": "軽い・たまの用途なら — はい：PDF 注釈、契約署名、子どもの落書き、入門スケッチ。筆圧レベルはありません — Wacom タブレットではありません。",
      "faq.q3": "マウス、キーボード、描画を切り替えられる？",
      "faq.a3": "いつでも。ショートカットを打ち、ポインタを動かし、数語入力してから注釈 — 同じ端末で、タップ一つで切り替え。",
      "faq.q4": "制御する側の機器に何か入れる必要は？",
      "faq.a4": "不要です。USB で挿しても Bluetooth でペアしても、Flexhub は普通のマウスとキーボードとして認識されます。アプリが出てくるのは、たまに Flexhub を更新する日だけ。",
      "faq.q5": "リモコンなの？",
      "faq.a5": "おまけ程度です。Flexhub はショートカット、ポインタ、軽いタッチ向け — ただしいつものリモコンが見当たらないとき、スマホが助けになります。",
      "faq.q6": "端末の中身は変わる？",
      "faq.a6": "いいえ。写真、メッセージ、ファイルはそのまま。Flexhub は端末の使い道を一つ増やすだけです。",
      "nav.modes": "二つの接続方法",
      "hero.m4": "⇄ USB または Bluetooth · 旅も軽く",
      "chip.modes": "USB · Bluetooth",
      "modes.kicker": "二つの接続方法",
      "modes.title": "挿すか、ワイヤレスか。",
      "modes.lead": "Flexhub は、制御したい機器へあなたに合う方法で話します。どちらでも、手元にあるのは自分のスマホ、タブレット、パソコンです。",
      "modes.usbTag": "ケーブルあり",
      "modes.usbT": "そのまま挿す（USB）",
      "modes.usbP": "制御したいパソコン、画面、TV ボックスに USB データケーブルで Flexhub を接続。すぐにマウスとキーボードとして認識 — インストールもペアリングも不要。",
      "modes.usbBest": "向いている用途：デスクのパソコン、仕事用ノート、空き USB ポートがある機器。",
      "modes.btTag": "ワイヤレス",
      "modes.btT": "Bluetooth ペアリング",
      "modes.btP": "Flexhub に電源を入れるだけ — スマホ充電器やモバイルバッテリーで十分。通電から約 2 分後、制御したい機器の Bluetooth 設定を開き「flexhub」を選択。完了！",
      "modes.btBest": "向いている用途：タブレット、Apple TV などの TV ボックス、空き USB がない機器。",
      "modes.tipT": "Flexhub が自動で選びます",
      "modes.tipP": "電源投入時、Flexhub は確認します：データケーブルで機器に繋がっている？ → USB。電源だけ？ → Bluetooth。切り替えたいときは抜き、別のつなぎ方で挿し直してください。",
      "compare.title": "USB と Bluetooth — 一覧",
      "compare.lead": "どちらでもスマホから同じように操作。各モードの違いです。",
      "compare.colFeature": "できること",
      "compare.colUsb": "USB モード",
      "compare.colBt": "Bluetooth モード",
      "compare.r0f": "接続方法",
      "compare.r0u": "制御したい機器へ USB データケーブル",
      "compare.r0b": "電源のみ、その機器で <b>flexhub</b> をペア",
      "compare.r1f": "キーボードとマウス",
      "compare.r1u": "あり — すぐに表示",
      "compare.r1b": "あり — 名前は flexhub",
      "compare.r2f": "ゲームパッド（DualSense とクラシック BT）",
      "compare.r2u": "あり — DualSense とクラシック Bluetooth パッド",
      "compare.r2b": "Bluetooth モードではゲームパッドなし",
      "compare.r3f": "スマホのブラウザから操作",
      "compare.r3u": "あり — スマホ / タブレット / パソコンのブラウザ",
      "compare.r3b": "あり — 同じ Wi‑Fi ページ",
      "compare.r4f": "電源投入時",
      "compare.r4": "自動 — データケーブル準備OK？ USB。電源だけ？ Bluetooth。抜き差しで切り替え。",
      "faq.q7": "USB と Bluetooth、どちらを選ぶ？",
      "faq.a7": "簡単な方で！ 空き USB ポートがある？ 挿せば完了。ポートがない、またはタブレットや TV ボックスを制御？ 充電器で Flexhub に給電し Bluetooth でペア。ヒント：ペアするのは制御したい機器 — 手元のスマホではありません。",
      "faq.q8": "Wi‑Fi でどう繋ぐ？",
      "faq.a8": "スマホ、タブレット、パソコンで flexhub という Wi‑Fi（パスワード build.me）に接続し、ブラウザで http://flexhub.local/ または http://192.168.4.1/ を開きます。このホットスポットが Flexhub と手元端末の対話手段 — 日常に App Store は不要です。",
      "faq.a11": "はい。Flexhub の Wi‑Fi ページでマクロを録画し、端末に保存して、あとからショートカットのように再生できます。",
      "faq.q11": "自分のショートカットキーやマクロを設定できる？",
      "faq.a10": "いいえ — 先にそう言います。Flexhub に筆圧レベルはありません。軽いトラックパッド、ワイヤレスプレゼンター、署名パッド、マルチメディアショートカット、キーコンボから作る Stream Deck 風マクロが得意です。",
      "faq.q10": "Wacom タブレットの代わりになる？",
      "foot.privacy": "プライバシー",
      "foot.terms": "利用規約",
      "foot.refund": "返品・返金",
      "foot.shipping": "配送",
      "foot.contact": "お問い合わせ・運営者情報",
      "foot.copy": "© 2026 Flexhub · visualbuild.shop",
      "brand.tag": "Wi‑Fi ホットスポットのリモコン",
      "a11y.nav": "メインナビゲーション",
      "a11y.lang": "言語",
      "a11y.illust": "Flexhub 製品イラスト",
      "a11y.illustAlt": "Flexhub — スマホ・タブレット・パソコンをマウス、キーボード、描画パッドに変える、赤いアクセントの小さな白いプラグ",
      "a11y.compare": "USB と Bluetooth の比較",
    },
    "ko": {
      "skip": "본문으로 건너뛰기",
      "nav.benefits": "주요 기능",
      "nav.how": "작동 방식",
      "nav.buy": "구매",
      "nav.faq": "자주 묻는 질문",
      "nav.guide": "사용 설명서",
      "how.guideT": "자세한 내용이 궁금하세요?",
      "how.guideP": "전체 사용 설명서는 두 모드(USB와 무선), Bluetooth 페어링, 모든 리모컨 탭, 매크로, 설정, 업데이트, 문제 해결을 단계별로 안내하며, 직접 눌러 보는 데모도 있습니다.",
      "how.guideCta": "사용 설명서 열기 →",
      "nav.cta": "Flexhub 구매하기",
      "lang.label": "언어",
      "hero.eyebrow": "Wi‑Fi 핫스팟 · 단축키 · 마우스 · 가벼운 주석 · 앱 필요 없음",
      "hero.title": "오래된 휴대폰에 새 역할을 — 무선 단축키, 마우스와 가벼운 터치를<br><span class=\"accent\">지금 가진 휴대폰으로.</span>",
      "hero.lead": "Flexhub는 오래된 휴대폰이나 태블릿을 책상 PC용 저렴한 무선 단축키 패널로 바꿔 줍니다. 트랙패드, 프레젠터, 서명 패드, 가벼운 주석 도구로도 쓸 수 있습니다. flexhub Wi‑Fi 핫스팟에 접속해 브라우저를 열면 끝 — 평소에는 앱 스토어 설치가 필요 없습니다. Flexhub를 USB로 PC에 꽂고(드라이버 불필요) 휴대폰을 든 채 편히 쉬세요.",
      "hero.ctaPrimary": "Flexhub 구매하기",
      "hero.ctaSecondary": "무엇을 할 수 있는지 보기",
      "hero.m0": "✓ 평소에는 앱 필요 없음",
      "hero.m1": "⌘ 나만의 단축키와 매크로",
      "hero.m2": "◎ 보조 마우스 / 프레젠터",
      "hero.m3": "✎ 서명, 낙서, PDF 주석",
      "hero.illustCaption": "Flexhub 제품 일러스트",
      "chip.noapp": "앱 필요 없음",
      "chip.mouse": "트랙패드 / 프레젠터",
      "chip.keyboard": "단축키와 입력",
      "chip.draw": "가벼운 주석",
      "chip.devices": "휴대폰 · 태블릿 · 컴퓨터",
      "ben.kicker": "주요 기능",
      "ben.title": "들고 다니는 가벼운 도구.",
      "ben.f1t": "드라이버 불필요. 가볍게 휴대.",
      "ben.f1p": "Flexhub를 책상 PC에 꽂고, 이미 가진 휴대폰으로 Wi‑Fi 핫스팟에 접속해 소파나 카페 자리에서 제어하세요. 부피 큰 편집 패드를 챙길 필요가 없습니다. 평소에는 다운로드도 계정도 필요 없고, 앱은 가끔 하는 펌웨어 업데이트에만 씁니다.",
      "ben.b1t": "트랙패드와 무선 프레젠터",
      "ben.b1p": "방 건너편에서도 이동·클릭·스크롤할 수 있습니다. 주 마우스 옆의 보조 포인팅 장치나 간단한 무선 프레젠터로 제격이며, 유일한 전문가용 포인팅 장치로 쓰기 위한 것은 아닙니다.",
      "ben.b2t": "휴대폰 속 단축키와 매크로",
      "ben.b2p": "Wi‑Fi 페이지에서 매크로를 녹화하고 기기에 저장한 뒤 단축키처럼 다시 실행하세요. 스트림 덱을 따로 사지 않아도 비슷한 단축키를 쓸 수 있습니다.",
      "ben.b3t": "가끔씩 주석, 서명, 낙서",
      "ben.b3p": "PDF 표시, 계약서 서명, 아이들 낙서, 초보자 스케치에 좋습니다.",
      "dev.title": "이미 가진 기기와 함께",
      "dev.lead": "휴대폰, 태블릿, 컴퓨터 — 새것이든 오래된 것이든. 서랍 속 여분의 휴대폰이 쓸모 있는 단축키 패널이 됩니다.",
      "dev.phone": "휴대폰",
      "dev.tablet": "태블릿",
      "dev.computer": "컴퓨터",
      "ben.bonusT": "작은 보너스: 여분의 리모컨",
      "ben.bonusP": "리모컨이 쿠션 밑에 숨었나요? 찾는 동안 휴대폰으로 TV 박스의 간단한 조작을 대신할 수 있습니다. 있으면 좋은 기능일 뿐, Flexhub의 본업은 PC에서의 단축키, 포인팅, 가벼운 터치입니다.",
      "how.kicker": "작동 방식",
      "how.title": "1분이면 준비 완료.",
      "how.lead": "다운로드할 것도, 가입할 것도 없습니다. USB 메모리를 꽂거나 Bluetooth 헤드폰을 연결할 수 있다면 준비는 끝났습니다.",
      "how.s1t": "꽂거나 페어링하기",
      "how.s1p": "Flexhub를 제어할 기기에 USB 케이블로 연결하거나, 전원만 넣고 Bluetooth로 페어링하세요.",
      "how.s2t": "기기에서 열기",
      "how.s2p": "휴대폰·태블릿·컴퓨터에서 flexhub라는 Wi‑Fi(비밀번호 build.me)에 접속하고 브라우저에서 http://flexhub.local/ 또는 http://192.168.4.1/을 여세요. 앱은 필요 없습니다. 이게 끝입니다.",
      "how.s3t": "단축키, 포인팅, 입력, 가벼운 터치",
      "how.s3p": "매크로와 키 조합을 실행하고, 포인터를 움직이고, 몇 마디를 입력하거나 PDF에 주석을 다세요. 편한 곳 어디서든 원할 때 전환하면 됩니다.",
      "how.noteT": "앱이 필요한 유일한 때: 업데이트",
      "how.noteP": "가끔 Flexhub 개선 사항을 배포할 수 있습니다. 그때가 저희 앱을 쓰는 유일한 순간입니다 — 앱을 열고 업데이트를 누르면 끝. 평소에는 앱이 있다는 것조차 잊어도 됩니다.",
      "quote.text": "단축키. 포인팅. 입력. 가벼운 터치 — 손에 든 휴대폰으로.",
      "quote.by": "일상적인 비전문가용·보조 화면 환경을 위한 휴대용 가벼운 도구.",
      "buy.kicker": "곧 출시",
      "buy.title": "작은 플러그 하나. 나머지는 여분의 휴대폰이 합니다.",
      "buy.lead": "Flexhub는 곧 visualbuild.shop에서 만나볼 수 있습니다. 가격과 배송 안내는 준비 중이니 조금만 기다려 주세요!",
      "buy.priceNote": "가격 곧 공개",
      "buy.cta": "곧 출시",
      "buy.fine": "visualbuild.shop에서 안전하게 결제",
      "faq.kicker": "자주 묻는 질문",
      "faq.title": "좋은 질문, 빠른 답변",
      "faq.q0": "앱을 다운로드해야 하나요?",
      "faq.a0": "평소에는 필요 없습니다 — 단축키, 포인팅, 입력, 가벼운 주석을 아무것도 설치하지 않고 쓸 수 있습니다. 앱은 Flexhub를 업데이트할 때만 필요하며 몇 번만 누르면 됩니다.",
      "faq.q1": "어떤 기기에서 되나요?",
      "faq.a1": "휴대폰, 태블릿, 컴퓨터 — 웹 브라우저가 있다면 새것이든 오래된 것이든 거의 다 됩니다. 더 이상 업데이트되지 않는 휴대폰도 무선 단축키 패널로 훌륭하게 쓸 수 있습니다. 예를 들어 1세대 Apple iPad mini도 됩니다.",
      "faq.q2": "그림 그리기에 쓸 수 있나요?",
      "faq.a2": "가볍게, 가끔 쓰는 정도라면 가능합니다: PDF 주석, 계약서 서명, 아이들 낙서, 초보자 낙서. 필압은 없으며 Wacom 태블릿이 아닙니다.",
      "faq.q3": "마우스, 키보드, 그리기 사이를 전환할 수 있나요?",
      "faq.a3": "언제든지요. 단축키를 실행하고, 포인터를 움직이고, 몇 마디 입력한 뒤 주석까지 — 모두 같은 기기에서, 탭 한 번으로 전환합니다.",
      "faq.q4": "제어할 기기에 뭔가 설치해야 하나요?",
      "faq.a4": "아니요. USB 케이블로 꽂든 Bluetooth로 페어링하든 Flexhub는 평범한 마우스와 키보드로 인식됩니다. 앱은 가끔 Flexhub를 업데이트하는 날에만 필요합니다.",
      "faq.q5": "리모컨인가요?",
      "faq.a5": "작은 부가 기능일 뿐입니다. Flexhub는 단축키, 포인팅, 가벼운 터치를 위해 만들어졌지만, 평소 쓰는 리모컨이 없어졌을 때 휴대폰이 급한 대로 도움이 됩니다.",
      "faq.q6": "내 기기에 뭔가 바뀌나요?",
      "faq.a6": "아니요. 사진, 메시지, 파일은 그대로입니다. Flexhub는 기기를 활용할 방법을 하나 더 더해 줄 뿐입니다.",
      "nav.modes": "두 가지 연결 방식",
      "hero.m4": "⇄ USB 또는 Bluetooth · 가볍게 휴대",
      "chip.modes": "USB · Bluetooth",
      "modes.kicker": "두 가지 연결 방식",
      "modes.title": "꽂거나, 무선으로.",
      "modes.lead": "Flexhub는 제어할 기기와 편한 방식으로 연결됩니다. 어느 쪽이든 손에 든 휴대폰·태블릿·컴퓨터로 조작합니다.",
      "modes.usbTag": "케이블로",
      "modes.usbT": "바로 꽂기(USB)",
      "modes.usbP": "Flexhub를 제어할 컴퓨터, 모니터 또는 TV 박스에 USB 데이터 케이블로 연결하세요. 바로 마우스와 키보드로 인식되며, 설치도 페어링도 필요 없습니다.",
      "modes.usbBest": "추천: 책상 컴퓨터, 업무용 노트북, 빈 USB 포트가 있는 모든 기기.",
      "modes.btTag": "무선",
      "modes.btT": "Bluetooth로 페어링",
      "modes.btP": "Flexhub에 전원만 넣으세요 — 휴대폰 충전기나 보조배터리면 충분합니다. 전원을 켜고 약 2분 뒤 제어할 기기의 Bluetooth 설정을 열어 “flexhub”를 선택하면 끝!",
      "modes.btBest": "추천: 태블릿, Apple TV 같은 TV 박스, 빈 USB 포트가 없는 기기.",
      "modes.tipT": "Flexhub가 알아서 고릅니다",
      "modes.tipP": "전원이 켜지면 Flexhub가 확인합니다. 케이블로 기기에 연결됐나요? 그러면 USB로 동작합니다. 전원만 들어오나요? Bluetooth로 바뀝니다. 바꾸고 싶다면 뽑았다가 다른 방식으로 다시 꽂으세요.",
      "compare.title": "USB vs Bluetooth — 한눈에 보기",
      "compare.lead": "어느 쪽이든 휴대폰으로 쉽게 제어합니다. 각 모드의 특징은 다음과 같습니다.",
      "compare.colFeature": "기능",
      "compare.colUsb": "USB 모드",
      "compare.colBt": "Bluetooth 모드",
      "compare.r0f": "연결 방식",
      "compare.r0u": "제어할 기기에 USB 데이터 케이블로 연결",
      "compare.r0b": "전원만 연결한 뒤 그 기기에서 <b>flexhub</b>와 페어링",
      "compare.r1f": "키보드와 마우스",
      "compare.r1u": "예 — 바로 인식됨",
      "compare.r1b": "예 — flexhub로 표시",
      "compare.r2f": "게임패드(DualSense 및 일반 BT)",
      "compare.r2u": "예 — DualSense 및 일반 Bluetooth 패드",
      "compare.r2b": "Bluetooth 모드에서는 게임패드 없음",
      "compare.r3f": "휴대폰 브라우저로 제어",
      "compare.r3u": "예 — 휴대폰 / 태블릿 / 컴퓨터 브라우저",
      "compare.r3b": "예 — 같은 Wi‑Fi 페이지",
      "compare.r4f": "전원을 켤 때",
      "compare.r4": "자동 — 데이터 케이블 연결? USB. 전원만? Bluetooth. 바꾸려면 뽑았다 다시 꽂으세요.",
      "faq.q7": "USB와 Bluetooth 중 무엇을 고를까요?",
      "faq.a7": "더 쉬운 쪽이면 됩니다! 빈 USB 포트가 있나요? 꽂으면 끝입니다. 포트가 없거나 태블릿·TV 박스를 제어하나요? 충전기로 Flexhub에 전원을 넣고 Bluetooth로 페어링하세요. 팁: 손에 든 휴대폰이 아니라 제어할 기기에서 페어링하세요.",
      "faq.q8": "Wi‑Fi로는 어떻게 연결하나요?",
      "faq.a8": "휴대폰·태블릿·컴퓨터에서 flexhub라는 Wi‑Fi(비밀번호 build.me)에 접속한 뒤 브라우저에서 http://flexhub.local/ 또는 http://192.168.4.1/을 여세요. 이 무선 핫스팟으로 Flexhub가 손에 든 기기와 통신하며, 평소에는 앱 스토어 설치가 필요 없습니다.",
      "faq.a11": "예. Flexhub Wi‑Fi 페이지에서 매크로를 녹화하고 기기에 저장한 뒤 나중에 단축키처럼 다시 실행할 수 있습니다.",
      "faq.q11": "나만의 단축키와 매크로를 설정할 수 있나요?",
      "faq.a10": "아니요 — 미리 말씀드립니다. Flexhub에는 필압이 없습니다. 가벼운 트랙패드, 무선 프레젠터, 서명 패드, 멀티미디어 단축 컨트롤러, 키 조합 매크로를 활용한 스트림 덱 같은 단축키로 빛을 발합니다.",
      "faq.q10": "Wacom 태블릿을 대신할 수 있나요?",
      "foot.privacy": "개인정보처리방침",
      "foot.terms": "이용약관",
      "foot.refund": "환불",
      "foot.shipping": "배송",
      "foot.contact": "문의 및 사업자 정보",
      "foot.copy": "© 2026 Flexhub · visualbuild.shop",
      "brand.tag": "Wi‑Fi 핫스팟 리모컨",
      "a11y.nav": "주 메뉴",
      "a11y.lang": "언어",
      "a11y.illust": "Flexhub 제품 일러스트",
      "a11y.illustAlt": "Flexhub — 휴대폰·태블릿·컴퓨터를 마우스, 키보드, 드로잉 패드로 바꿔 주는 빨간 포인트의 작은 흰색 플러그",
      "a11y.compare": "USB와 Bluetooth 비교",
    },
    "ar": {
      "skip": "انتقل إلى المحتوى",
      "nav.benefits": "ماذا يفعل",
      "nav.how": "كيف يعمل",
      "nav.buy": "شراء",
      "nav.faq": "الأسئلة الشائعة",
      "nav.guide": "دليل المستخدم",
      "how.guideT": "تريد كل التفاصيل؟",
      "how.guideP": "يشرح دليل المستخدم الكامل الوضعين خطوة بخطوة (USB واللاسلكي)، وإقران Bluetooth، وكل تبويب في صفحة التحكم، والماكرو، والإعدادات، والتحديثات، واستكشاف الأخطاء — مع عروض تفاعلية تجربها بنقرة.",
      "how.guideCta": "افتح دليل المستخدم ←",
      "nav.cta": "احصل على Flexhub",
      "lang.label": "اللغة",
      "hero.eyebrow": "نقطة Wi‑Fi · اختصارات · فأرة · تعليق خفيف · بلا تطبيق",
      "hero.title": "هاتف قديم، مهمة جديدة — اختصارات لاسلكية وفأرة ولمس خفيف<br><span class=\"accent\">من الهاتف الذي تملكه بالفعل.</span>",
      "hero.lead": "يحوّل Flexhub هاتفًا أو جهازًا لوحيًا قديمًا إلى لوحة اختصارات لاسلكية رخيصة لحاسوب مكتبك — إلى جانب لوحة لمس وأداة عرض تقديمي ولوحة توقيع وأداة تعليق خفيفة. انضم إلى نقطة Wi‑Fi المسماة flexhub وافتح المتصفح — دون تثبيت أي تطبيق للاستخدام اليومي. وصّل Flexhub بالحاسوب عبر USB (بلا تعريفات)، ثم استرخِ والهاتف في يدك.",
      "hero.ctaPrimary": "احصل على Flexhub",
      "hero.ctaSecondary": "اكتشف ما يستطيع فعله",
      "hero.m0": "✓ بلا تطبيق للاستخدام اليومي",
      "hero.m1": "⌘ اختصارات وماكرو مخصصة",
      "hero.m2": "◎ فأرة ثانوية / أداة عرض",
      "hero.m3": "✎ توقيع، خربشة، تعليق على PDF",
      "hero.illustCaption": "رسم توضيحي لمنتج Flexhub",
      "chip.noapp": "لا حاجة إلى تطبيق",
      "chip.mouse": "لوحة لمس / أداة عرض",
      "chip.keyboard": "اختصارات وكتابة",
      "chip.draw": "تعليق خفيف",
      "chip.devices": "هاتف · جهاز لوحي · حاسوب",
      "ben.kicker": "ماذا يفعل",
      "ben.title": "أداة خفيفة محمولة.",
      "ben.f1t": "بلا تعريفات. خفيف للتنقل.",
      "ben.f1p": "وصّل Flexhub بحاسوب المكتب، وانضم إلى نقطة Wi‑Fi الخاصة به من الهاتف الذي تملكه، وتحكّم من الأريكة أو من مقعد في المقهى — دون حمل لوحة تحرير ضخمة. لا تنزيلات ولا حسابات للاستخدام اليومي؛ التطبيق فقط لتحديثات البرنامج الثابت العرضية.",
      "ben.b1t": "لوحة لمس وأداة عرض لاسلكية",
      "ben.b1p": "حرّك وانقر ومرّر من الجهة الأخرى للغرفة. مثالي كسطح تأشير ثانٍ بجانب الفأرة الرئيسية — أو كأداة عرض لاسلكية بسيطة — لا كجهاز تأشير احترافي وحيد.",
      "ben.b2t": "اختصارات وماكرو على الهاتف",
      "ben.b2p": "سجّل الماكرو في صفحة Wi‑Fi، واحفظها على الجهاز، وأعد تشغيلها لاحقًا كاختصارات — اختصارات شبيهة بلوحات البث دون شراء لوحة أخرى.",
      "ben.b3t": "تعليق وتوقيع وخربشة بين حين وآخر",
      "ben.b3p": "رائع للتعليق على ملفات PDF، وتوقيع العقود، وخربشات الأطفال، والرسوم البسيطة للمبتدئين.",
      "dev.title": "يعمل مع ما تملكه بالفعل",
      "dev.lead": "هواتف وأجهزة لوحية وحواسيب — جديدة أو قديمة. ذلك الهاتف الاحتياطي في الدرج يصبح لوحة اختصارات مفيدة.",
      "dev.phone": "الهواتف",
      "dev.tablet": "الأجهزة اللوحية",
      "dev.computer": "الحواسيب",
      "ben.bonusT": "ميزة إضافية: جهاز تحكم احتياطي",
      "ben.bonusP": "جهاز التحكم تحت الوسائد؟ يستطيع هاتفك تنفيذ النقرات البسيطة على جهاز التلفاز ريثما تبحث. ميزة لطيفة — فمهمة Flexhub الحقيقية هي الاختصارات والتأشير واللمس الخفيف على الحاسوب.",
      "how.kicker": "كيف يعمل",
      "how.title": "جاهز في أقل من دقيقة.",
      "how.lead": "لا شيء للتنزيل ولا شيء للتسجيل. إذا كنت تستطيع توصيل ذاكرة USB أو سماعات Bluetooth، فأنت جاهز.",
      "how.s1t": "وصّله — أو اقرنه",
      "how.s1p": "وصّل Flexhub بالجهاز الذي تريد التحكم فيه بكابل USB، أو شغّله فقط واقرنه عبر Bluetooth.",
      "how.s2t": "افتح جهازك",
      "how.s2p": "على هاتفك أو جهازك اللوحي أو حاسوبك، انضم إلى شبكة Wi‑Fi المسماة flexhub (كلمة المرور build.me) وافتح http://flexhub.local/ أو http://192.168.4.1/ في المتصفح — لا حاجة إلى تطبيق، هذا كل شيء.",
      "how.s3t": "اختصارات، تأشير، كتابة، لمس خفيف",
      "how.s3p": "شغّل الماكرو وتركيبات المفاتيح، وحرّك المؤشر، واكتب بضع كلمات، أو علّق على ملف PDF — وبدّل متى شئت من أي مكان مريح.",
      "how.noteT": "المرة الوحيدة التي تحتاج فيها إلى تطبيق: التحديثات",
      "how.noteP": "من حين لآخر قد نصدر تحسينات لـ Flexhub. هذه هي اللحظة الوحيدة التي ستستخدم فيها تطبيقنا — افتحه، واضغط تحديث، وانتهى الأمر. أما في الأيام العادية فيمكنك أن تنسى وجوده.",
      "quote.text": "اختصارات. تأشير. كتابة. لمس خفيف — من الهاتف الذي في يدك.",
      "quote.by": "أداة خفيفة محمولة للاستخدام اليومي غير الاحترافي وللشاشات الثانوية.",
      "buy.kicker": "قريبًا",
      "buy.title": "قابس صغير واحد. والهاتف الاحتياطي يتولّى الباقي.",
      "buy.lead": "سيتوفر Flexhub قريبًا جدًا على visualbuild.shop. تفاصيل السعر والشحن في الطريق — عُد قريبًا!",
      "buy.priceNote": "السعر قريبًا",
      "buy.cta": "قريبًا",
      "buy.fine": "دفع آمن على visualbuild.shop",
      "faq.kicker": "الأسئلة الشائعة",
      "faq.title": "أسئلة جيدة، إجابات سريعة",
      "faq.q0": "هل أحتاج إلى تنزيل تطبيق؟",
      "faq.a0": "ليس للاستخدام اليومي — الاختصارات والتأشير والكتابة والتعليق الخفيف دون تثبيت أي شيء. ستحتاج إلى تطبيقنا فقط عند تحديث Flexhub، ويستغرق ذلك بضع نقرات.",
      "faq.q1": "ما الأجهزة التي تعمل؟",
      "faq.a1": "الهواتف والأجهزة اللوحية والحواسيب — تقريبًا أي جهاز فيه متصفح ويب، قديمًا كان أو جديدًا. حتى الهاتف الذي لم يعد يتلقى تحديثات يعمل بشكل ممتاز كلوحة اختصارات لاسلكية — مثل Apple iPad mini من الجيل الأول.",
      "faq.q2": "هل يمكنني استخدامه للرسم؟",
      "faq.a2": "للاستخدام الخفيف والعرضي — نعم: التعليق على PDF، وتوقيع العقود، وخربشات الأطفال والمبتدئين. لا توجد مستويات ضغط — ليس لوح Wacom.",
      "faq.q3": "هل يمكنني التبديل بين الفأرة ولوحة المفاتيح والرسم؟",
      "faq.a3": "في أي وقت. شغّل اختصارًا، وحرّك المؤشر، واكتب بضع كلمات، ثم علّق — كله من الجهاز نفسه وبنقرة واحدة للتبديل.",
      "faq.q4": "هل أحتاج إلى تثبيت أي شيء على الجهاز الذي أتحكم فيه؟",
      "faq.a4": "لا. سواء وصّلته بكابل USB أو قرنته عبر Bluetooth، يظهر Flexhub كفأرة ولوحة مفاتيح عاديتين. لا تحتاج إلى تطبيق إلا في اليوم النادر الذي تحدّث فيه Flexhub.",
      "faq.q5": "هل هو جهاز تحكم عن بُعد؟",
      "faq.a5": "فقط كميزة إضافية صغيرة. صُنع Flexhub للاختصارات والتأشير واللمس الخفيف — لكن إذا ضاع جهاز التحكم المعتاد، يستطيع هاتفك أن يساعدك عند الحاجة.",
      "faq.q6": "هل سيغيّر أي شيء على جهازي؟",
      "faq.a6": "لا. تبقى صورك ورسائلك وملفاتك كما هي تمامًا. يمنح Flexhub جهازك ببساطة طريقة أخرى ليكون مفيدًا.",
      "nav.modes": "طريقتان للاتصال",
      "hero.m4": "⇄ USB أو Bluetooth · خفيف للتنقل",
      "chip.modes": "USB · Bluetooth",
      "modes.kicker": "طريقتان للاتصال",
      "modes.title": "وصّله، أو استخدمه لاسلكيًا.",
      "modes.lead": "يتواصل Flexhub مع الجهاز الذي تريد التحكم فيه بالطريقة التي تناسبك. وفي الحالتين، الهاتف أو الجهاز اللوحي أو الحاسوب الذي في يدك هو أداة التحكم.",
      "modes.usbTag": "بكابل",
      "modes.usbT": "وصّله مباشرة (USB)",
      "modes.usbP": "وصّل Flexhub بالحاسوب أو الشاشة أو جهاز التلفاز الذي تريد التحكم فيه بكابل بيانات USB. يُتعرّف عليه فورًا كفأرة ولوحة مفاتيح — لا شيء للتثبيت ولا شيء للإقران.",
      "modes.usbBest": "مناسب لـ: حاسوب مكتبك، وحاسوب العمل المحمول، وأي جهاز فيه منفذ USB فارغ.",
      "modes.btTag": "لاسلكي",
      "modes.btT": "الإقران عبر Bluetooth",
      "modes.btP": "زوّد Flexhub بالطاقة فقط — شاحن هاتف أو بطارية متنقلة يفي بالغرض. بعد نحو دقيقتين من التشغيل، افتح إعدادات Bluetooth على الجهاز الذي تريد التحكم فيه واختر “flexhub”. انتهى!",
      "modes.btBest": "مناسب لـ: الأجهزة اللوحية، وأجهزة التلفاز مثل Apple TV، والأجهزة التي ليس فيها منفذ USB فارغ.",
      "modes.tipT": "Flexhub يختار بدلًا منك",
      "modes.tipP": "عند التشغيل يتحقق Flexhub: هل هو موصول بجهاز بكابل؟ يعمل عبر USB. هل يحصل على الطاقة فقط؟ ينتقل إلى Bluetooth. تريد التغيير؟ افصله وأعد توصيله بالطريقة الأخرى.",
      "compare.title": "USB مقابل Bluetooth — نظرة سريعة",
      "compare.lead": "التحكم السلس نفسه من هاتفك في الحالتين. إليك ما يقدّمه كل وضع.",
      "compare.colFeature": "ما تحصل عليه",
      "compare.colUsb": "وضع USB",
      "compare.colBt": "وضع Bluetooth",
      "compare.r0f": "طريقة الاتصال",
      "compare.r0u": "كابل بيانات USB إلى الجهاز الذي تريد التحكم فيه",
      "compare.r0b": "طاقة فقط، ثم اقرن <b>flexhub</b> على ذلك الجهاز",
      "compare.r1f": "لوحة المفاتيح والفأرة",
      "compare.r1u": "نعم — يظهر فورًا",
      "compare.r1b": "نعم — باسم flexhub",
      "compare.r2f": "ذراع التحكم (DualSense وBluetooth التقليدية)",
      "compare.r2u": "نعم — DualSense وأذرع Bluetooth التقليدية",
      "compare.r2b": "لا دعم لذراع التحكم في وضع Bluetooth",
      "compare.r3f": "التحكم من متصفح هاتفك",
      "compare.r3u": "نعم — متصفح الهاتف / الجهاز اللوحي / الحاسوب",
      "compare.r3b": "نعم — صفحة Wi‑Fi نفسها",
      "compare.r4f": "عند التشغيل",
      "compare.r4": "تلقائي — كابل بيانات جاهز؟ USB. طاقة فقط؟ Bluetooth. افصله وأعد توصيله للتبديل.",
      "faq.q7": "USB أم Bluetooth — أيهما أختار؟",
      "faq.a7": "الأسهل لك! لديك منفذ USB فارغ؟ وصّله وانتهى الأمر. لا يوجد منفذ، أو تتحكم في جهاز لوحي أو جهاز تلفاز؟ شغّل Flexhub من شاحن واقرنه عبر Bluetooth. نصيحة: اقرنه على الجهاز الذي تريد التحكم فيه — لا على الهاتف الذي في يدك.",
      "faq.q8": "كيف أتصل عبر Wi‑Fi؟",
      "faq.a8": "على هاتفك أو جهازك اللوحي أو حاسوبك، انضم إلى شبكة Wi‑Fi المسماة flexhub (كلمة المرور build.me)، ثم افتح http://flexhub.local/ أو http://192.168.4.1/ في المتصفح. عبر هذه النقطة اللاسلكية يتواصل Flexhub مع الجهاز الذي في يدك — دون تثبيت أي تطبيق للاستخدام اليومي.",
      "faq.a11": "نعم. في صفحة Wi‑Fi الخاصة بـ Flexhub يمكنك تسجيل الماكرو وحفظها على الجهاز وإعادة تشغيلها لاحقًا كاختصارات.",
      "faq.q11": "هل يمكنني ضبط مفاتيح اختصار وماكرو خاصة بي؟",
      "faq.a10": "لا — ونقول ذلك بوضوح. لا توجد في Flexhub مستويات ضغط. يتألق كلوحة لمس خفيفة، وأداة عرض لاسلكية، ولوحة توقيع، ووحدة اختصارات للوسائط المتعددة، وماكرو من تركيبات المفاتيح لاختصارات شبيهة بلوحات البث.",
      "faq.q10": "هل يمكن أن يحل محل لوح Wacom؟",
      "foot.privacy": "الخصوصية",
      "foot.terms": "الشروط",
      "foot.refund": "الاسترداد",
      "foot.shipping": "الشحن",
      "foot.contact": "التواصل والبيانات القانونية",
      "foot.copy": "© 2026 Flexhub · visualbuild.shop",
      "brand.tag": "تحكم عن بُعد عبر نقطة Wi‑Fi",
      "a11y.nav": "التنقل الرئيسي",
      "a11y.lang": "اللغة",
      "a11y.illust": "رسم توضيحي لمنتج Flexhub",
      "a11y.illustAlt": "Flexhub — قابس أبيض صغير بلمسات حمراء يحوّل هاتفك أو جهازك اللوحي أو حاسوبك إلى فأرة ولوحة مفاتيح ولوحة رسم",
      "a11y.compare": "مقارنة بين USB وBluetooth",
    },
  };;

const LANG_HTML = {en:"en", zh:"zh-Hans", de:"de", fr:"fr", ja:"ja", ko:"ko", ar:"ar"};
  const ALL_LANGS = ["en","zh","de","fr","ja","ko","ar"];

  function detectLang() {
    try {
      const q = new URLSearchParams(location.search).get("lang");
      if (q && ALL_LANGS.indexOf(q) >= 0) return q;
    } catch (_) {}
    try {
      const s = localStorage.getItem("flexhub_lang");
      if (s && ALL_LANGS.indexOf(s) >= 0) return s;
    } catch (_) {}
    const nav = (typeof navigator !== "undefined" && (navigator.languages && navigator.languages[0] || navigator.language) || "").toLowerCase();
    if (/^zh/.test(nav)) return "zh";
    if (/^de/.test(nav)) return "de";
    if (/^fr/.test(nav)) return "fr";
    if (/^ja/.test(nav)) return "ja";
    if (/^ko/.test(nav)) return "ko";
    if (/^ar/.test(nav)) return "ar";
    return "en";
  }

  const META = {"en": {"t": "Flexhub — wireless shortcuts & light touch from your phone | Wi‑Fi hotspot, no app", "d": "Flexhub turns an old phone into a cheap wireless shortcut panel for your desk PC — macros, trackpad, presenter, signature pad and light annotate. Driver-free USB.", "ot": "Flexhub — wireless shortcuts from your phone"}, "zh": {"t": "Flexhub — 用手机无线快捷键与轻度触控 | Wi‑Fi 热点，无需 App", "d": "Flexhub 把闲置手机变成桌面电脑的便宜无线快捷面板——宏、触控板、演示器、签名板和轻度批注。USB 免驱。", "ot": "Flexhub — 用手机做无线快捷键"}, "de": {"t": "Flexhub — kabellose Shortcuts & leichte Bedienung vom Smartphone | Wi‑Fi-Hotspot, keine App", "d": "Flexhub macht ein altes Smartphone zum günstigen kabellosen Shortcut-Panel für den PC — Makros, Trackpad, Presenter, Unterschriftenfeld und leichte Anmerkungen. USB ohne Treiber.", "ot": "Flexhub — kabellose Shortcuts vom Smartphone"}, "fr": {"t": "Flexhub — raccourcis sans fil et toucher léger depuis votre téléphone | Hotspot Wi‑Fi, sans app", "d": "Flexhub transforme un vieux téléphone en panneau de raccourcis sans fil pour votre PC — macros, trackpad, présentateur, pad de signature et annotation légère. USB sans pilote.", "ot": "Flexhub — raccourcis sans fil depuis votre téléphone"}, "ja": {"t": "Flexhub — スマホからワイヤレスショートカットと軽いタッチ | Wi‑Fi ホットスポット、アプリ不要", "d": "Flexhub は古いスマホをデスク PC 向けの手頃なワイヤレスショートカットパネルに変えます — マクロ、トラックパッド、プレゼンター、署名パッド、軽い注釈。USB ドライバ不要。", "ot": "Flexhub — スマホからワイヤレスショートカット"}, "ko": {"t": "Flexhub — 폰으로 하는 무선 단축키와 가벼운 터치 | Wi‑Fi 핫스팟, 앱 없음", "d": "Flexhub는 오래된 폰을 책상 PC용 저렴한 무선 단축 패널로 바꿉니다 — 매크로, 트랙패드, 프레젠터, 서명 패드, 가벼운 주석. 드라이버 없는 USB.", "ot": "Flexhub — 폰으로 하는 무선 단축키"}, "ar": {"t": "Flexhub — اختصارات لاسلكية ولمس خفيف من هاتفك | نقطة Wi‑Fi، بلا تطبيق", "d": "يحوّل Flexhub هاتفاً قديماً إلى لوحة اختصارات لاسلكية رخيصة لحاسوب المكتب — ماكرو، لوحة تتبع، جهاز عرض، لوحة توقيع وتعليق خفيف. USB بدون تعريف.", "ot": "Flexhub — اختصارات لاسلكية من هاتفك"}};
  function setMeta(sel, val) { const m = document.querySelector(sel); if (m && val) m.setAttribute("content", val); }
  function applyMeta(lang) {
    const m = META[lang] || META.en;
    document.title = m.t;
    setMeta('meta[name="description"]', m.d);
    setMeta('meta[property="og:title"]', m.ot);
    setMeta('meta[property="og:description"]', m.d);
    setMeta('meta[name="twitter:title"]', m.ot);
    setMeta('meta[name="twitter:description"]', m.d);
  }

  function applyLang(lang) {
    if (ALL_LANGS.indexOf(lang) < 0) lang = "en";
    const pack = dict[lang] || dict.en;
    document.documentElement.lang = LANG_HTML[lang] || "en";
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    applyMeta(lang);
    document.querySelectorAll("[data-i18n]").forEach((el) => {
      const key = el.getAttribute("data-i18n");
      if (pack[key] != null) el.textContent = pack[key];
    });
    document.querySelectorAll("[data-i18n-html]").forEach((el) => {
      const key = el.getAttribute("data-i18n-html");
      if (pack[key] != null) el.innerHTML = pack[key];
    });
    document.querySelectorAll("[data-i18n-attr]").forEach((el) => {
      el.getAttribute("data-i18n-attr").split(";").forEach((pair) => {
        const i = pair.indexOf(":");
        if (i < 0) return;
        const attr = pair.slice(0, i).trim(), key = pair.slice(i + 1).trim();
        const v = pack[key] != null ? pack[key] : dict.en[key];
        if (attr && v != null) el.setAttribute(attr, v);
      });
    });
    try { localStorage.setItem("flexhub_lang", lang); } catch (_) {}
    const sel = document.getElementById("lang");
    if (sel) sel.value = lang;
  }

  applyLang(detectLang());

  const sel = document.getElementById("lang");
  if (sel) sel.addEventListener("change", () => applyLang(sel.value));

  const c = window.SHOP_CONFIG || {};
  const p = document.querySelector("#price");
  const n = document.querySelector("#priceNote");
  const b = document.querySelector("#buyButton");
  if (p && c.price) p.textContent = c.price;
  if (n && c.priceNote) n.textContent = c.priceNote;
  if (b && c.creemCheckoutUrl) {
    b.href = c.creemCheckoutUrl;
    b.textContent = (dict[(document.documentElement.lang === "zh-Hans" ? "zh" : document.documentElement.lang)] || dict.en)["nav.cta"] || "Buy now";
    b.classList.remove("off");
  } else if (b) {
    b.addEventListener("click", (e) => e.preventDefault());
    b.style.opacity = ".55";
    b.style.pointerEvents = "none";
  }
})();
