/* Flexhub site — i18n + checkout config */
(function () {
  const dict = {
    "en": {
      "skip": "Skip to content",
      "nav.benefits": "What it does",
      "nav.how": "How it works",
      "nav.buy": "Buy",
      "nav.faq": "FAQ",
      "nav.guide": "User guide",
      "how.guideT": "Want every detail?",
      "how.guideP": "The full user guide walks through both modes step by step (USB and wireless), Bluetooth pairing, every remote tab, macros, settings, updates and troubleshooting — with tap-to-try demos.",
      "how.guideCta": "Open the user guide →",
      "nav.cta": "Get Flexhub",
      "lang.label": "Language",
      "hero.eyebrow": "Wi‑Fi hotspot · shortcuts · mouse · light annotate · no app",
      "hero.title": "Old phone, new job — wireless shortcuts, mouse &amp; light touch<br><span class=\"accent\">from the phone you already have.</span>",
      "hero.lead": "Flexhub turns an old phone or tablet into a cheap wireless shortcut panel for your desk PC — plus a trackpad, presenter, signature pad and light annotate tool. Join the flexhub Wi‑Fi hotspot, open the browser — no App Store install for everyday use. Plug Flexhub into the PC over USB (driver-free), then lounge with the phone in hand.",
      "hero.ctaPrimary": "Get Flexhub",
      "hero.ctaSecondary": "See what it can do",
      "hero.m0": "✓ No app for everyday use",
      "hero.m1": "⌘ Custom shortcuts &amp; macros",
      "hero.m2": "◎ Secondary mouse / presenter",
      "hero.m3": "✎ Sign, doodle, PDF annotate",
      "hero.illustCaption": "Flexhub product illustration",
      "chip.noapp": "No app needed",
      "chip.mouse": "Trackpad / presenter",
      "chip.keyboard": "Shortcuts &amp; type",
      "chip.draw": "Light annotate",
      "chip.devices": "Phone · tablet · computer",
      "ben.kicker": "What it does",
      "ben.title": "A portable light tool.",
      "ben.f1t": "Driver-free. Travel-light.",
      "ben.f1p": "Plug Flexhub into the desk PC, join its Wi‑Fi hotspot on the phone you already own, and control from the sofa or a café seat — no bulky edit deck to pack. No downloads or accounts for everyday use; the app is only for occasional firmware updates.",
      "ben.b1t": "Trackpad &amp; wireless presenter",
      "ben.b1p": "Move, click and scroll from across the room. Ideal as a second pointing surface beside a main mouse — or as a simple wireless presenter — not as your only pro pointing device.",
      "ben.b2t": "Shortcuts &amp; macros on the phone",
      "ben.b2p": "Record macros on the Wi‑Fi page, save them to the device, and replay them later as shortcut-like actions — Stream Deck–like shortcuts without buying another deck.",
      "ben.b3t": "Occasional annotate, sign &amp; doodle",
      "ben.b3p": "Great for PDF markup, contract signatures, kids’ doodles and beginner sketches.",
      "dev.title": "Works with what you already have",
      "dev.lead": "Phones, tablets and computers — new or old. That spare phone in the drawer becomes a handy shortcut panel.",
      "dev.phone": "Phones",
      "dev.tablet": "Tablets",
      "dev.computer": "Computers",
      "ben.bonusT": "Little bonus: a spare remote",
      "ben.bonusP": "Remote under the cushions? Your phone can cover simple TV-box taps while you look. Nice to have — Flexhub’s real job is shortcuts, pointing and light touch on the PC.",
      "how.kicker": "How it works",
      "how.title": "Ready in under a minute.",
      "how.lead": "Nothing to download, nothing to sign up for. If you can plug in a USB stick or connect Bluetooth headphones, you're all set.",
      "how.s1t": "Plug it in — or pair it",
      "how.s1p": "Connect Flexhub to the device you want to control with a USB cable, or just power it up and pair it over Bluetooth.",
      "how.s2t": "Open your device",
      "how.s2p": "On your phone, tablet or computer, join the Wi-Fi named flexhub (password build.me) and open http://flexhub.local/ or http://192.168.4.1/ in the browser — no app needed, that's it.",
      "how.s3t": "Shortcuts, point, type, light touch",
      "how.s3p": "Fire macros and key combos, move the pointer, type a few words, or annotate a PDF — switch whenever you like from wherever you’re comfy.",
      "how.noteT": "The only time you need an app: updates",
      "how.noteP": "Every so often we may release improvements for Flexhub. That's the one moment you'll use our app — open it, tap update, done. Day to day, you can forget it exists.",
      "quote.text": "Shortcuts. Point. Type. Light touch — from the phone in your hand.",
      "quote.by": "A portable light tool for everyday non-pro and second-screen setups.",
      "buy.kicker": "Coming soon",
      "buy.title": "One little plug. A spare phone does the rest.",
      "buy.lead": "Flexhub will be available at visualbuild.shop very soon. Pricing and shipping details are on the way — check back shortly!",
      "buy.priceNote": "Price coming soon",
      "buy.cta": "Coming soon",
      "buy.fine": "Secure checkout on visualbuild.shop",
      "faq.kicker": "FAQ",
      "faq.title": "Good questions, quick answers",
      "faq.q0": "Do I need to download an app?",
      "faq.a0": "Not for everyday use — shortcuts, pointing, typing and light annotate without installing anything. You’ll only need our app when you want to update Flexhub, and that takes a few taps.",
      "faq.q1": "Which devices work?",
      "faq.a1": "Phones, tablets and computers — almost anything with a web browser, old or new. Even a phone that no longer gets updates works great as a wireless shortcut panel — for example, a first-gen Apple iPad mini.",
      "faq.q2": "Can I use it for drawing?",
      "faq.a2": "For light, occasional use — yes: PDF annotate, contract signatures, kids’ doodles and beginner doodles. No pressure levels — not a Wacom tablet.",
      "faq.q3": "Can I switch between mouse, keyboard and drawing?",
      "faq.a3": "Anytime. Fire a shortcut, move the pointer, type a few words, then annotate — all from the same device, with a single tap to switch.",
      "faq.q4": "Do I need to install anything on the device I control?",
      "faq.a4": "Nope. Whether you plug in with a USB cable or pair over Bluetooth, Flexhub shows up as an ordinary mouse and keyboard. An app only comes in on the occasional day you update Flexhub.",
      "faq.q5": "Is it a remote control?",
      "faq.a5": "Only as a little extra. Flexhub is made for shortcuts, pointing and light touch — but if your usual remote goes missing, your phone can help in a pinch.",
      "faq.q6": "Will it change anything on my device?",
      "faq.a6": "No. Your photos, messages and files stay exactly as they are. Flexhub simply gives your device one more way to be useful.",
      "nav.modes": "Two ways to connect",
      "hero.m4": "⇄ USB or Bluetooth · travel-light",
      "chip.modes": "USB · Bluetooth",
      "modes.kicker": "Two ways to connect",
      "modes.title": "Plug it in, or go wireless.",
      "modes.lead": "Flexhub talks to the device you want to control in whichever way suits you. Either way, your phone, tablet or computer is the one in your hand.",
      "modes.usbTag": "With a cable",
      "modes.usbT": "Plug straight in (USB)",
      "modes.usbP": "Connect Flexhub to the computer, screen or TV box you want to control with a USB data cable. It's recognised right away as a mouse and keyboard — nothing to install, nothing to pair.",
      "modes.usbBest": "Great for: your desk computer, a work laptop, anything with a free USB port.",
      "modes.btTag": "Wireless",
      "modes.btT": "Pair over Bluetooth",
      "modes.btP": "Just give Flexhub power — a phone charger or power bank is perfect. About two minutes after power-up, open the Bluetooth settings on the device you want to control and pick “flexhub”. Done!",
      "modes.btBest": "Great for: tablets, TV boxes like Apple TV, and devices without a spare USB port.",
      "modes.tipT": "Flexhub chooses for you",
      "modes.tipP": "When it powers up, Flexhub checks: connected to a device by cable? It works over USB. Only getting power? It switches to Bluetooth. Want to change? Just unplug it and plug it back in the other way.",
      "compare.title": "USB vs Bluetooth — at a glance",
      "compare.lead": "Same sunny control from your phone either way. Here's what each mode brings.",
      "compare.colFeature": "What you get",
      "compare.colUsb": "USB mode",
      "compare.colBt": "Bluetooth mode",
      "compare.r0f": "How it connects",
      "compare.r0u": "USB data cable into the device you want to control",
      "compare.r0b": "Power only, then pair <b>flexhub</b> on that device",
      "compare.r1f": "Keyboard & mouse",
      "compare.r1u": "Yes — shows up right away",
      "compare.r1b": "Yes — as flexhub",
      "compare.r2f": "Gamepad (DualSense & classic BT)",
      "compare.r2u": "Yes — DualSense & classic Bluetooth pads",
      "compare.r2b": "No gamepad in Bluetooth mode",
      "compare.r3f": "Control from your phone's browser",
      "compare.r3u": "Yes — phone / tablet / computer browser",
      "compare.r3b": "Yes — same Wi‑Fi page",
      "compare.r4f": "At power-up",
      "compare.r4": "Auto — data cable ready? USB. Only power? Bluetooth. Unplug and replug to switch.",
      "faq.q7": "USB or Bluetooth — which should I choose?",
      "faq.a7": "Whatever is easiest! Got a free USB port? Plug in and you're done. No port, or controlling a tablet or TV box? Power Flexhub from a charger and pair it over Bluetooth. Tip: pair it on the device you want to control — not on the phone in your hand.",
      "faq.q8": "How do I connect over Wi‑Fi?",
      "faq.a8": "On your phone, tablet or computer, join the Wi‑Fi named flexhub (password build.me), then open http://flexhub.local/ or http://192.168.4.1/ in the browser. That wireless hotspot is how Flexhub talks to the device in your hand — no App Store install for everyday use.",
      "faq.a11": "Yes. On the Flexhub Wi‑Fi page you can record macros, save them to the device, and replay them later as shortcut-like actions.",
      "faq.q11": "Can I set my own shortcut keys and macros?",
      "faq.a10": "No — and we say that up front. Flexhub has no pressure levels. It shines as a light trackpad, wireless presenter, signature pad, multimedia shortcut controller, and macros from key combos for Stream Deck–like shortcuts.",
      "faq.q10": "Can it replace my Wacom tablet?",
      "foot.privacy": "Privacy",
      "foot.terms": "Terms",
      "foot.refund": "Refunds",
      "foot.copy": "© 2026 Flexhub · visualbuild.shop"
    },
    "zh": {
      "skip": "跳到正文",
      "nav.benefits": "能做什么",
      "nav.how": "怎么用",
      "nav.buy": "购买",
      "nav.faq": "常见问题",
      "nav.guide": "使用说明",
      "how.guideT": "想了解更多细节？",
      "how.guideP": "完整使用说明分别讲解 USB 模式和无线模式的完整流程、蓝牙配对、每个遥控标签、宏、设置、升级和常见问题处理——还能点一点试用。",
      "how.guideCta": "打开使用说明 →",
      "nav.cta": "获取 Flexhub",
      "lang.label": "语言",
      "hero.eyebrow": "无线热点 · 快捷键 · 鼠标 · 轻度批注 · 无需 App",
      "hero.title": "旧手机新用途 — 无线快捷键、鼠标与轻度触控<br><span class=\"accent\">用现成手机就能上手。</span>",
      "hero.lead": "Flexhub 把闲置手机或平板变成便宜的无线快捷面板，兼顾触控板、演示器、签名板和轻度批注。连上名为 flexhub 的无线热点，用浏览器打开即可——日常不必装应用商店 App。把 Flexhub 免驱插到电脑，人可以窝在沙发上用手机控桌面。",
      "hero.ctaPrimary": "获取 Flexhub",
      "hero.ctaSecondary": "看看它能做什么",
      "hero.m0": "✓ 日常使用无需 App",
      "hero.m1": "⌘ 自定义快捷键与宏",
      "hero.m2": "◎ 副鼠标 / 演示器",
      "hero.m3": "✎ 签名、涂鸦、PDF 批注",
      "hero.illustCaption": "Flexhub 产品示意图",
      "chip.noapp": "无需 App",
      "chip.mouse": "触控板 / 演示",
      "chip.keyboard": "快捷键与打字",
      "chip.draw": "轻度批注",
      "chip.devices": "手机 · 平板 · 电脑",
      "ben.kicker": "能做什么",
      "ben.title": "随身的轻量工具",
      "ben.f1t": "免驱，出行轻便",
      "ben.f1p": "把 Flexhub 插到电脑，用现成的手机连上它的无线热点，就能在沙发或咖啡馆控桌面——不用再背一块笨重的剪辑键盘。日常免下载、免账号；只有偶尔升级固件才需要 App。",
      "ben.b1t": "触控板与无线演示",
      "ben.b1p": "隔着房间也能移动、点击、滚动。适合当主鼠标旁边的第二块触控面，或简单无线演示器——而不是你唯一的专业定点设备。",
      "ben.b2t": "手机上的快捷键与宏",
      "ben.b2p": "可以在无线热点页面录制宏，保存到设备后回放执行类似快捷键的操作——不必再买一块专用键台。",
      "ben.b3t": "偶尔批注、签名与涂鸦",
      "ben.b3p": "适合 PDF 圈画、合同签名、孩子涂鸦和入门涂鸦。",
      "dev.title": "你手边的设备就能用",
      "dev.lead": "手机、平板、电脑，新旧都行。抽屉里那部闲置手机，正好当个快捷面板。",
      "dev.phone": "手机",
      "dev.tablet": "平板",
      "dev.computer": "电脑",
      "ben.bonusT": "小彩蛋：备用遥控",
      "ben.bonusP": "遥控器掉进沙发缝？找的时候手机可以先应付电视盒子的简单操作。有它挺好——Flexhub 真正擅长的是快捷键、指点和轻度触控。",
      "how.kicker": "怎么用",
      "how.title": "一分钟就能用上。",
      "how.lead": "不用下载，不用注册，没有复杂设置。会插 U 盘、会连蓝牙耳机，就会用 Flexhub。",
      "how.s1t": "插上，或者配对",
      "how.s1p": "用 USB 数据线把 Flexhub 连到你想控制的设备；或者只给它通电，再通过蓝牙配对。",
      "how.s2t": "打开你的设备",
      "how.s2p": "在手机、平板或电脑上连接名为 flexhub 的 Wi-Fi（密码 build.me），浏览器打开 http://flexhub.local/ 或 http://192.168.4.1/——无需 App，就这么简单。",
      "how.s3t": "快捷键、指点、打字、轻度触控",
      "how.s3p": "触发宏和组合键、移动指针、打几个字，或给 PDF 批注——随时切换，怎么舒服怎么来。",
      "how.noteT": "唯一需要 App 的时候：升级",
      "how.noteP": "我们会不定期为 Flexhub 带来新改进。只有这时才需要用到我们的 App——打开、点一下升级，就完成了。平时你完全可以忘了它。",
      "quote.text": "快捷键。指点。打字。轻度触控——全在你手里的手机上。",
      "quote.by": "面向日常非专业与第二屏幕场景的随身轻量工具。",
      "buy.kicker": "即将上市",
      "buy.title": "一个小插头，旧手机做其余的事。",
      "buy.lead": "Flexhub 即将在 visualbuild.shop 上架。价格与配送信息马上公布——敬请期待！",
      "buy.priceNote": "价格即将公布",
      "buy.cta": "即将开售",
      "buy.fine": "在 visualbuild.shop 安全结账",
      "faq.kicker": "常见问题",
      "faq.title": "好问题，简单答",
      "faq.q0": "需要下载 App 吗？",
      "faq.a0": "日常完全不需要——快捷键、指点、打字和轻度批注都不用装任何东西。只有想升级 Flexhub 时才需要我们的 App，点几下就好。",
      "faq.q1": "哪些设备可以用？",
      "faq.a1": "手机、平板和电脑都可以——几乎所有带浏览器的设备，新旧都行。即使是不再更新系统的旧手机，也很适合当无线快捷面板。例如 Apple iPad mini 第一代。",
      "faq.q2": "能用来画画吗？",
      "faq.a2": "轻度、偶尔用可以：PDF 批注、合同签名、孩子涂鸦、入门涂鸦。没有压感——不是 Wacom 数位板。",
      "faq.q3": "鼠标、键盘、手绘板可以随时切换吗？",
      "faq.a3": "随时可以。先触发快捷键，再挪指针、打几个字，再批注两笔——同一台设备，轻点切换。",
      "faq.q4": "被控制的设备需要安装什么吗？",
      "faq.a4": "不需要。无论用 USB 数据线插上，还是通过蓝牙配对，Flexhub 都会被识别为普通的鼠标和键盘。只有偶尔升级 Flexhub 时才会用到 App。",
      "faq.q5": "它是遥控器吗？",
      "faq.a5": "只是顺带的小功能。Flexhub 主要为快捷键、指点和轻度触控——不过原来的遥控器找不到时，手机也能临时帮上忙。",
      "faq.q6": "会改动我设备里的东西吗？",
      "faq.a6": "不会。照片、聊天记录和文件都原样保留。Flexhub 只是让你的设备多一种用处。",
      "nav.modes": "两种连接方式",
      "hero.m4": "⇄ USB 或蓝牙 · 出行轻便",
      "chip.modes": "USB · 蓝牙",
      "modes.kicker": "两种连接方式",
      "modes.title": "插上就用，或者无线连接。",
      "modes.lead": "Flexhub 可以用你喜欢的方式连接想要控制的设备。不管哪种方式，你手里拿的都是自己的手机、平板或电脑。",
      "modes.usbTag": "有线",
      "modes.usbT": "直接插上（USB）",
      "modes.usbP": "用 USB 数据线把 Flexhub 连到你想控制的电脑、屏幕或电视盒子上，它会立刻被识别为鼠标和键盘——不用安装，也不用配对。",
      "modes.usbBest": "适合：台式电脑、办公笔记本，以及任何有空闲 USB 口的设备。",
      "modes.btTag": "无线",
      "modes.btT": "蓝牙配对",
      "modes.btP": "只要给 Flexhub 通上电——手机充电头或充电宝都行。通电约两分钟后，在想控制的设备上打开蓝牙设置，选择「flexhub」，就好了！",
      "modes.btBest": "适合：平板、Apple TV 等电视盒子，以及没有空闲 USB 口的设备。",
      "modes.tipT": "Flexhub 会自动选择",
      "modes.tipP": "每次通电时，Flexhub 会先看一看：用数据线连着设备？那就走 USB。只是在充电？那就切换到蓝牙。想换一种方式？拔下来，换种方式重新插上就行。",
      "compare.title": "USB 与蓝牙一览",
      "compare.lead": "两种方式都能用手机开心地遥控。下面一眼看清差别。",
      "compare.colFeature": "你能得到什么",
      "compare.colUsb": "USB 模式",
      "compare.colBt": "蓝牙模式",
      "compare.r0f": "怎么连上",
      "compare.r0u": "用 USB 数据线插到想控制的设备上",
      "compare.r0b": "只供电，然后在目标设备上配对 <b>flexhub</b>",
      "compare.r1f": "键盘与鼠标",
      "compare.r1u": "有 — 插上就能用",
      "compare.r1b": "有 — 设备名 flexhub",
      "compare.r2f": "手柄（DualSense 与经典蓝牙）",
      "compare.r2u": "有 — DualSense 与经典蓝牙手柄",
      "compare.r2b": "蓝牙模式不支持手柄",
      "compare.r3f": "用手机浏览器遥控",
      "compare.r3u": "有 — 手机 / 平板 / 电脑浏览器",
      "compare.r3b": "有 — 同一个 Wi‑Fi 页面",
      "compare.r4f": "通电时",
      "compare.r4": "自动选择 — 数据线已就绪？走 USB。只供电？走蓝牙。想换方式？拔掉换种接法再通电。",
      "faq.q7": "USB 和蓝牙，该选哪个？",
      "faq.a7": "哪个方便选哪个！有空闲 USB 口？插上就好。没有 USB 口，或者要控制平板、电视盒子？用充电头给 Flexhub 供电，再用蓝牙配对。小提示：要在被控制的设备上配对，而不是在你手里的手机上。",
      "faq.q8": "怎么用 Wi‑Fi 连接？",
      "faq.a8": "在手机、平板或电脑上连接名为 flexhub 的 Wi‑Fi（密码 build.me），然后在浏览器打开 http://flexhub.local/ 或 http://192.168.4.1/。这个无线热点就是 Flexhub 和你手里设备对话的方式—日常使用不必装应用商店 App。",
      "faq.a11": "可以。在 Flexhub 无线热点页面可以录制宏，保存到设备后回放执行类似快捷键的操作。",
      "faq.q11": "可以自定义快捷键和宏吗？",
      "faq.a10": "不能——我们把话说在前面。Flexhub 没有压感等级。它擅长的是：轻触控板、无线演示器、签名板、多媒体快捷控制器，以及用组合键录制的宏来做类似 Stream Deck 的快捷操作。",
      "faq.q10": "能替代我的 Wacom 数位板吗？",
      "foot.privacy": "隐私",
      "foot.terms": "条款",
      "foot.refund": "退换",
      "foot.copy": "© 2026 Flexhub · visualbuild.shop"
    }
  };

  function applyLang(lang) {
    const pack = dict[lang] || dict.en;
    document.documentElement.lang = lang === "zh" ? "zh-Hans" : "en";
    document.querySelectorAll("[data-i18n]").forEach((el) => {
      const key = el.getAttribute("data-i18n");
      if (pack[key] != null) el.textContent = pack[key];
    });
    document.querySelectorAll("[data-i18n-html]").forEach((el) => {
      const key = el.getAttribute("data-i18n-html");
      if (pack[key] != null) el.innerHTML = pack[key];
    });
    try { localStorage.setItem("flexhub_lang", lang); } catch (_) {}
    const sel = document.getElementById("lang");
    if (sel) sel.value = lang;
  }

  const saved = (function () {
    try { return localStorage.getItem("flexhub_lang"); } catch (_) { return null; }
  })();
  const preferZh = typeof navigator !== "undefined" && /^zh\b/i.test(navigator.language || "");
  applyLang(saved || (preferZh ? "zh" : "en"));

  const sel = document.getElementById("lang");
  if (sel) sel.addEventListener("change", () => applyLang(sel.value));

  const c = window.SHOP_CONFIG || {};
  const p = document.querySelector("#price");
  const n = document.querySelector("#priceNote");
  const b = document.querySelector("#buyButton");
  if (p && c.price) p.textContent = c.price;
  if (n && c.priceNote) n.textContent = c.priceNote;
  if (b && c.creemCheckoutUrl) {
    b.href = c.creemCheckoutUrl;
    b.textContent = document.documentElement.lang.startsWith("zh") ? "立即购买" : "Buy now";
    b.classList.remove("off");
  } else if (b) {
    b.addEventListener("click", (e) => e.preventDefault());
    b.style.opacity = ".55";
    b.style.pointerEvents = "none";
  }
})();
