/* Flexhub site — i18n + checkout config */
(function () {
  const dict = {
    "en": {
      "skip": "Skip to content",
      "nav.benefits": "What it does",
      "nav.how": "How it works",
      "nav.buy": "Buy",
      "nav.faq": "FAQ",
      "nav.guide": "User guide",
      "how.guideT": "Want every detail?",
      "how.guideP": "The full user guide walks through both modes step by step (USB and wireless), Bluetooth pairing, every remote tab, macros, settings, updates and troubleshooting — with tap-to-try demos.",
      "how.guideCta": "Open the user guide →",
      "nav.cta": "Get Flexhub",
      "lang.label": "Language",
      "hero.eyebrow": "Wi‑Fi hotspot · shortcuts · mouse · light annotate · no app",
      "hero.title": "Old phone, new job — wireless shortcuts, mouse &amp; light touch<br><span class=\"accent\">from the phone you already have.</span>",
      "hero.lead": "Flexhub turns an old phone or tablet into a cheap wireless shortcut panel for your desk PC — plus a trackpad, presenter, signature pad and light annotate tool. Join the flexhub Wi‑Fi hotspot, open the browser — no App Store install for everyday use. Plug Flexhub into the PC over USB (driver-free), then lounge with the phone in hand.",
      "hero.ctaPrimary": "Get Flexhub",
      "hero.ctaSecondary": "See what it can do",
      "hero.m0": "✓ No app for everyday use",
      "hero.m1": "⌘ Custom shortcuts &amp; macros",
      "hero.m2": "◎ Secondary mouse / presenter",
      "hero.m3": "✎ Sign, doodle, PDF annotate",
      "hero.illustCaption": "Flexhub product illustration",
      "chip.noapp": "No app needed",
      "chip.mouse": "Trackpad / presenter",
      "chip.keyboard": "Shortcuts &amp; type",
      "chip.draw": "Light annotate",
      "chip.devices": "Phone · tablet · computer",
      "ben.kicker": "What it does",
      "ben.title": "A portable light tool.",
      "ben.f1t": "Driver-free. Travel-light.",
      "ben.f1p": "Plug Flexhub into the desk PC, join its Wi‑Fi hotspot on the phone you already own, and control from the sofa or a café seat — no bulky edit deck to pack. No downloads or accounts for everyday use; the app is only for occasional firmware updates.",
      "ben.b1t": "Trackpad &amp; wireless presenter",
      "ben.b1p": "Move, click and scroll from across the room. Ideal as a second pointing surface beside a main mouse — or as a simple wireless presenter — not as your only pro pointing device.",
      "ben.b2t": "Shortcuts &amp; macros on the phone",
      "ben.b2p": "Record macros on the Wi‑Fi page, save them to the device, and replay them later as shortcut-like actions — Stream Deck–like shortcuts without buying another deck.",
      "ben.b3t": "Occasional annotate, sign &amp; doodle",
      "ben.b3p": "Great for PDF markup, contract signatures, kids’ doodles and beginner sketches.",
      "dev.title": "Works with what you already have",
      "dev.lead": "Phones, tablets and computers — new or old. That spare phone in the drawer becomes a handy shortcut panel.",
      "dev.phone": "Phones",
      "dev.tablet": "Tablets",
      "dev.computer": "Computers",
      "ben.bonusT": "Little bonus: a spare remote",
      "ben.bonusP": "Remote under the cushions? Your phone can cover simple TV-box taps while you look. Nice to have — Flexhub’s real job is shortcuts, pointing and light touch on the PC.",
      "how.kicker": "How it works",
      "how.title": "Ready in under a minute.",
      "how.lead": "Nothing to download, nothing to sign up for. If you can plug in a USB stick or connect Bluetooth headphones, you're all set.",
      "how.s1t": "Plug it in — or pair it",
      "how.s1p": "Connect Flexhub to the device you want to control with a USB cable, or just power it up and pair it over Bluetooth.",
      "how.s2t": "Open your device",
      "how.s2p": "On your phone, tablet or computer, join the Wi-Fi named flexhub (password build.me) and open http://flexhub.local/ or http://192.168.4.1/ in the browser — no app needed, that's it.",
      "how.s3t": "Shortcuts, point, type, light touch",
      "how.s3p": "Fire macros and key combos, move the pointer, type a few words, or annotate a PDF — switch whenever you like from wherever you’re comfy.",
      "how.noteT": "The only time you need an app: updates",
      "how.noteP": "Every so often we may release improvements for Flexhub. That's the one moment you'll use our app — open it, tap update, done. Day to day, you can forget it exists.",
      "quote.text": "Shortcuts. Point. Type. Light touch — from the phone in your hand.",
      "quote.by": "A portable light tool for everyday non-pro and second-screen setups.",
      "buy.kicker": "Coming soon",
      "buy.title": "One little plug. A spare phone does the rest.",
      "buy.lead": "Flexhub will be available at visualbuild.shop very soon. Pricing and shipping details are on the way — check back shortly!",
      "buy.priceNote": "Price coming soon",
      "buy.cta": "Coming soon",
      "buy.fine": "Secure checkout on visualbuild.shop",
      "faq.kicker": "FAQ",
      "faq.title": "Good questions, quick answers",
      "faq.q0": "Do I need to download an app?",
      "faq.a0": "Not for everyday use — shortcuts, pointing, typing and light annotate without installing anything. You’ll only need our app when you want to update Flexhub, and that takes a few taps.",
      "faq.q1": "Which devices work?",
      "faq.a1": "Phones, tablets and computers — almost anything with a web browser, old or new. Even a phone that no longer gets updates works great as a wireless shortcut panel — for example, a first-gen Apple iPad mini.",
      "faq.q2": "Can I use it for drawing?",
      "faq.a2": "For light, occasional use — yes: PDF annotate, contract signatures, kids’ doodles and beginner doodles. No pressure levels — not a Wacom tablet.",
      "faq.q3": "Can I switch between mouse, keyboard and drawing?",
      "faq.a3": "Anytime. Fire a shortcut, move the pointer, type a few words, then annotate — all from the same device, with a single tap to switch.",
      "faq.q4": "Do I need to install anything on the device I control?",
      "faq.a4": "Nope. Whether you plug in with a USB cable or pair over Bluetooth, Flexhub shows up as an ordinary mouse and keyboard. An app only comes in on the occasional day you update Flexhub.",
      "faq.q5": "Is it a remote control?",
      "faq.a5": "Only as a little extra. Flexhub is made for shortcuts, pointing and light touch — but if your usual remote goes missing, your phone can help in a pinch.",
      "faq.q6": "Will it change anything on my device?",
      "faq.a6": "No. Your photos, messages and files stay exactly as they are. Flexhub simply gives your device one more way to be useful.",
      "nav.modes": "Two ways to connect",
      "hero.m4": "⇄ USB or Bluetooth · travel-light",
      "chip.modes": "USB · Bluetooth",
      "modes.kicker": "Two ways to connect",
      "modes.title": "Plug it in, or go wireless.",
      "modes.lead": "Flexhub talks to the device you want to control in whichever way suits you. Either way, your phone, tablet or computer is the one in your hand.",
      "modes.usbTag": "With a cable",
      "modes.usbT": "Plug straight in (USB)",
      "modes.usbP": "Connect Flexhub to the computer, screen or TV box you want to control with a USB data cable. It's recognised right away as a mouse and keyboard — nothing to install, nothing to pair.",
      "modes.usbBest": "Great for: your desk computer, a work laptop, anything with a free USB port.",
      "modes.btTag": "Wireless",
      "modes.btT": "Pair over Bluetooth",
      "modes.btP": "Just give Flexhub power — a phone charger or power bank is perfect. About two minutes after power-up, open the Bluetooth settings on the device you want to control and pick “flexhub”. Done!",
      "modes.btBest": "Great for: tablets, TV boxes like Apple TV, and devices without a spare USB port.",
      "modes.tipT": "Flexhub chooses for you",
      "modes.tipP": "When it powers up, Flexhub checks: connected to a device by cable? It works over USB. Only getting power? It switches to Bluetooth. Want to change? Just unplug it and plug it back in the other way.",
      "compare.title": "USB vs Bluetooth — at a glance",
      "compare.lead": "Same sunny control from your phone either way. Here's what each mode brings.",
      "compare.colFeature": "What you get",
      "compare.colUsb": "USB mode",
      "compare.colBt": "Bluetooth mode",
      "compare.r0f": "How it connects",
      "compare.r0u": "USB data cable into the device you want to control",
      "compare.r0b": "Power only, then pair <b>flexhub</b> on that device",
      "compare.r1f": "Keyboard & mouse",
      "compare.r1u": "Yes — shows up right away",
      "compare.r1b": "Yes — as flexhub",
      "compare.r2f": "Gamepad (DualSense & classic BT)",
      "compare.r2u": "Yes — DualSense & classic Bluetooth pads",
      "compare.r2b": "No gamepad in Bluetooth mode",
      "compare.r3f": "Control from your phone's browser",
      "compare.r3u": "Yes — phone / tablet / computer browser",
      "compare.r3b": "Yes — same Wi‑Fi page",
      "compare.r4f": "At power-up",
      "compare.r4": "Auto — data cable ready? USB. Only power? Bluetooth. Unplug and replug to switch.",
      "faq.q7": "USB or Bluetooth — which should I choose?",
      "faq.a7": "Whatever is easiest! Got a free USB port? Plug in and you're done. No port, or controlling a tablet or TV box? Power Flexhub from a charger and pair it over Bluetooth. Tip: pair it on the device you want to control — not on the phone in your hand.",
      "faq.q8": "How do I connect over Wi‑Fi?",
      "faq.a8": "On your phone, tablet or computer, join the Wi‑Fi named flexhub (password build.me), then open http://flexhub.local/ or http://192.168.4.1/ in the browser. That wireless hotspot is how Flexhub talks to the device in your hand — no App Store install for everyday use.",
      "faq.a11": "Yes. On the Flexhub Wi‑Fi page you can record macros, save them to the device, and replay them later as shortcut-like actions.",
      "faq.q11": "Can I set my own shortcut keys and macros?",
      "faq.a10": "No — and we say that up front. Flexhub has no pressure levels. It shines as a light trackpad, wireless presenter, signature pad, multimedia shortcut controller, and macros from key combos for Stream Deck–like shortcuts.",
      "faq.q10": "Can it replace my Wacom tablet?",
      "foot.privacy": "Privacy",
      "foot.terms": "Terms",
      "foot.refund": "Refunds",
      "foot.copy": "© 2026 Flexhub · visualbuild.shop",
    },
    "zh": {
      "skip": "跳到正文",
      "nav.benefits": "能做什么",
      "nav.how": "怎么用",
      "nav.buy": "购买",
      "nav.faq": "常见问题",
      "nav.guide": "使用说明",
      "how.guideT": "想了解更多细节？",
      "how.guideP": "完整使用说明分别讲解 USB 模式和无线模式的完整流程、蓝牙配对、每个遥控标签、宏、设置、升级和常见问题处理——还能点一点试用。",
      "how.guideCta": "打开使用说明 →",
      "nav.cta": "获取 Flexhub",
      "lang.label": "语言",
      "hero.eyebrow": "无线热点 · 快捷键 · 鼠标 · 轻度批注 · 无需 App",
      "hero.title": "旧手机新用途 — 无线快捷键、鼠标与轻度触控<br><span class=\"accent\">用现成手机就能上手。</span>",
      "hero.lead": "Flexhub 把闲置手机或平板变成便宜的无线快捷面板，兼顾触控板、演示器、签名板和轻度批注。连上名为 flexhub 的无线热点，用浏览器打开即可——日常不必装应用商店 App。把 Flexhub 免驱插到电脑，人可以窝在沙发上用手机控桌面。",
      "hero.ctaPrimary": "获取 Flexhub",
      "hero.ctaSecondary": "看看它能做什么",
      "hero.m0": "✓ 日常使用无需 App",
      "hero.m1": "⌘ 自定义快捷键与宏",
      "hero.m2": "◎ 副鼠标 / 演示器",
      "hero.m3": "✎ 签名、涂鸦、PDF 批注",
      "hero.illustCaption": "Flexhub 产品示意图",
      "chip.noapp": "无需 App",
      "chip.mouse": "触控板 / 演示",
      "chip.keyboard": "快捷键与打字",
      "chip.draw": "轻度批注",
      "chip.devices": "手机 · 平板 · 电脑",
      "ben.kicker": "能做什么",
      "ben.title": "随身的轻量工具",
      "ben.f1t": "免驱，出行轻便",
      "ben.f1p": "把 Flexhub 插到电脑，用现成的手机连上它的无线热点，就能在沙发或咖啡馆控桌面——不用再背一块笨重的剪辑键盘。日常免下载、免账号；只有偶尔升级固件才需要 App。",
      "ben.b1t": "触控板与无线演示",
      "ben.b1p": "隔着房间也能移动、点击、滚动。适合当主鼠标旁边的第二块触控面，或简单无线演示器——而不是你唯一的专业定点设备。",
      "ben.b2t": "手机上的快捷键与宏",
      "ben.b2p": "可以在无线热点页面录制宏，保存到设备后回放执行类似快捷键的操作——不必再买一块专用键台。",
      "ben.b3t": "偶尔批注、签名与涂鸦",
      "ben.b3p": "适合 PDF 圈画、合同签名、孩子涂鸦和入门涂鸦。",
      "dev.title": "你手边的设备就能用",
      "dev.lead": "手机、平板、电脑，新旧都行。抽屉里那部闲置手机，正好当个快捷面板。",
      "dev.phone": "手机",
      "dev.tablet": "平板",
      "dev.computer": "电脑",
      "ben.bonusT": "小彩蛋：备用遥控",
      "ben.bonusP": "遥控器掉进沙发缝？找的时候手机可以先应付电视盒子的简单操作。有它挺好——Flexhub 真正擅长的是快捷键、指点和轻度触控。",
      "how.kicker": "怎么用",
      "how.title": "一分钟就能用上。",
      "how.lead": "不用下载，不用注册，没有复杂设置。会插 U 盘、会连蓝牙耳机，就会用 Flexhub。",
      "how.s1t": "插上，或者配对",
      "how.s1p": "用 USB 数据线把 Flexhub 连到你想控制的设备；或者只给它通电，再通过蓝牙配对。",
      "how.s2t": "打开你的设备",
      "how.s2p": "在手机、平板或电脑上连接名为 flexhub 的 Wi-Fi（密码 build.me），浏览器打开 http://flexhub.local/ 或 http://192.168.4.1/——无需 App，就这么简单。",
      "how.s3t": "快捷键、指点、打字、轻度触控",
      "how.s3p": "触发宏和组合键、移动指针、打几个字，或给 PDF 批注——随时切换，怎么舒服怎么来。",
      "how.noteT": "唯一需要 App 的时候：升级",
      "how.noteP": "我们会不定期为 Flexhub 带来新改进。只有这时才需要用到我们的 App——打开、点一下升级，就完成了。平时你完全可以忘了它。",
      "quote.text": "快捷键。指点。打字。轻度触控——全在你手里的手机上。",
      "quote.by": "面向日常非专业与第二屏幕场景的随身轻量工具。",
      "buy.kicker": "即将上市",
      "buy.title": "一个小插头，旧手机做其余的事。",
      "buy.lead": "Flexhub 即将在 visualbuild.shop 上架。价格与配送信息马上公布——敬请期待！",
      "buy.priceNote": "价格即将公布",
      "buy.cta": "即将开售",
      "buy.fine": "在 visualbuild.shop 安全结账",
      "faq.kicker": "常见问题",
      "faq.title": "好问题，简单答",
      "faq.q0": "需要下载 App 吗？",
      "faq.a0": "日常完全不需要——快捷键、指点、打字和轻度批注都不用装任何东西。只有想升级 Flexhub 时才需要我们的 App，点几下就好。",
      "faq.q1": "哪些设备可以用？",
      "faq.a1": "手机、平板和电脑都可以——几乎所有带浏览器的设备，新旧都行。即使是不再更新系统的旧手机，也很适合当无线快捷面板。例如 Apple iPad mini 第一代。",
      "faq.q2": "能用来画画吗？",
      "faq.a2": "轻度、偶尔用可以：PDF 批注、合同签名、孩子涂鸦、入门涂鸦。没有压感——不是 Wacom 数位板。",
      "faq.q3": "鼠标、键盘、手绘板可以随时切换吗？",
      "faq.a3": "随时可以。先触发快捷键，再挪指针、打几个字，再批注两笔——同一台设备，轻点切换。",
      "faq.q4": "被控制的设备需要安装什么吗？",
      "faq.a4": "不需要。无论用 USB 数据线插上，还是通过蓝牙配对，Flexhub 都会被识别为普通的鼠标和键盘。只有偶尔升级 Flexhub 时才会用到 App。",
      "faq.q5": "它是遥控器吗？",
      "faq.a5": "只是顺带的小功能。Flexhub 主要为快捷键、指点和轻度触控——不过原来的遥控器找不到时，手机也能临时帮上忙。",
      "faq.q6": "会改动我设备里的东西吗？",
      "faq.a6": "不会。照片、聊天记录和文件都原样保留。Flexhub 只是让你的设备多一种用处。",
      "nav.modes": "两种连接方式",
      "hero.m4": "⇄ USB 或蓝牙 · 出行轻便",
      "chip.modes": "USB · 蓝牙",
      "modes.kicker": "两种连接方式",
      "modes.title": "插上就用，或者无线连接。",
      "modes.lead": "Flexhub 可以用你喜欢的方式连接想要控制的设备。不管哪种方式，你手里拿的都是自己的手机、平板或电脑。",
      "modes.usbTag": "有线",
      "modes.usbT": "直接插上（USB）",
      "modes.usbP": "用 USB 数据线把 Flexhub 连到你想控制的电脑、屏幕或电视盒子上，它会立刻被识别为鼠标和键盘——不用安装，也不用配对。",
      "modes.usbBest": "适合：台式电脑、办公笔记本，以及任何有空闲 USB 口的设备。",
      "modes.btTag": "无线",
      "modes.btT": "蓝牙配对",
      "modes.btP": "只要给 Flexhub 通上电——手机充电头或充电宝都行。通电约两分钟后，在想控制的设备上打开蓝牙设置，选择「flexhub」，就好了！",
      "modes.btBest": "适合：平板、Apple TV 等电视盒子，以及没有空闲 USB 口的设备。",
      "modes.tipT": "Flexhub 会自动选择",
      "modes.tipP": "每次通电时，Flexhub 会先看一看：用数据线连着设备？那就走 USB。只是在充电？那就切换到蓝牙。想换一种方式？拔下来，换种方式重新插上就行。",
      "compare.title": "USB 与蓝牙一览",
      "compare.lead": "两种方式都能用手机开心地遥控。下面一眼看清差别。",
      "compare.colFeature": "你能得到什么",
      "compare.colUsb": "USB 模式",
      "compare.colBt": "蓝牙模式",
      "compare.r0f": "怎么连上",
      "compare.r0u": "用 USB 数据线插到想控制的设备上",
      "compare.r0b": "只供电，然后在目标设备上配对 <b>flexhub</b>",
      "compare.r1f": "键盘与鼠标",
      "compare.r1u": "有 — 插上就能用",
      "compare.r1b": "有 — 设备名 flexhub",
      "compare.r2f": "手柄（DualSense 与经典蓝牙）",
      "compare.r2u": "有 — DualSense 与经典蓝牙手柄",
      "compare.r2b": "蓝牙模式不支持手柄",
      "compare.r3f": "用手机浏览器遥控",
      "compare.r3u": "有 — 手机 / 平板 / 电脑浏览器",
      "compare.r3b": "有 — 同一个 Wi‑Fi 页面",
      "compare.r4f": "通电时",
      "compare.r4": "自动选择 — 数据线已就绪？走 USB。只供电？走蓝牙。想换方式？拔掉换种接法再通电。",
      "faq.q7": "USB 和蓝牙，该选哪个？",
      "faq.a7": "哪个方便选哪个！有空闲 USB 口？插上就好。没有 USB 口，或者要控制平板、电视盒子？用充电头给 Flexhub 供电，再用蓝牙配对。小提示：要在被控制的设备上配对，而不是在你手里的手机上。",
      "faq.q8": "怎么用 Wi‑Fi 连接？",
      "faq.a8": "在手机、平板或电脑上连接名为 flexhub 的 Wi‑Fi（密码 build.me），然后在浏览器打开 http://flexhub.local/ 或 http://192.168.4.1/。这个无线热点就是 Flexhub 和你手里设备对话的方式—日常使用不必装应用商店 App。",
      "faq.a11": "可以。在 Flexhub 无线热点页面可以录制宏，保存到设备后回放执行类似快捷键的操作。",
      "faq.q11": "可以自定义快捷键和宏吗？",
      "faq.a10": "不能——我们把话说在前面。Flexhub 没有压感等级。它擅长的是：轻触控板、无线演示器、签名板、多媒体快捷控制器，以及用组合键录制的宏来做类似 Stream Deck 的快捷操作。",
      "faq.q10": "能替代我的 Wacom 数位板吗？",
      "foot.privacy": "隐私",
      "foot.terms": "条款",
      "foot.refund": "退换",
      "foot.copy": "© 2026 Flexhub · visualbuild.shop",
    },
    "de": {
      "skip": "Zum Inhalt springen",
      "nav.benefits": "Funktionen",
      "nav.how": "So geht's",
      "nav.buy": "Kaufen",
      "nav.faq": "FAQ",
      "nav.guide": "Anleitung",
      "how.guideT": "Willst du jedes Detail?",
      "how.guideP": "Die vollständige Bedienungsanleitung geht Schritt für Schritt durch beide Modi (USB und Wireless), Bluetooth-Kopplung, jede Remote-Registerkarte, Makros, Einstellungen, Updates und Fehlerbehebung — mit Tap-to-Try-Demos.",
      "how.guideCta": "Öffnen Sie das Benutzerhandbuch →",
      "nav.cta": "Flexhub holen",
      "lang.label": "Sprache",
      "hero.eyebrow": "Wi‑Fi Hotspot · Shortcuts · Maus · Light Annotate · keine App",
      "hero.title": "Altes Telefon, neuer Job — drahtlose Verknüpfungen, Maus &amp; leichte Berührung<br><span class=\"accent\">von dem Telefon, das Sie bereits haben.</span>",
      "hero.lead": "Flexhub verwandelt ein altes Telefon oder Tablet in ein günstiges drahtloses Verknüpfungsfeld für Ihren Schreibtisch-PC — plus Trackpad, Präsentator, Signatur-Pad und leichtes Anmerkungs-Tool. Treten Sie dem flexhub Wi‑Fi Hotspot bei, öffnen Sie den Browser — keine App Store-Installation für den täglichen Gebrauch. Schließen Sie Flexhub über USB (fahrerlos) an den PC an und entspannen Sie sich dann mit dem Telefon in der Hand.",
      "hero.ctaPrimary": "Flexhub holen",
      "hero.ctaSecondary": "Was es kann",
      "hero.m0": "✓ Keine App für den täglichen Gebrauch",
      "hero.m1": "⌘ Benutzerdefinierte Verknüpfungen &amp; Makros",
      "hero.m2": "◎ Zweitmaus / Moderator",
      "hero.m3": "✎ Sign, doodle, PDF annotate",
      "hero.illustCaption": "Flexhub Produktabbildung",
      "chip.noapp": "Keine App erforderlich",
      "chip.mouse": "Trackpad / Moderator",
      "chip.keyboard": "Verknüpfungen &amp; Typ",
      "chip.draw": "Light annotate",
      "chip.devices": "Telefon · Tablet · Computer",
      "ben.kicker": "Was es macht",
      "ben.title": "Ein tragbares Lichtwerkzeug.",
      "ben.f1t": "Fahrerfrei. Reiselicht.",
      "ben.f1p": "Schließen Sie Flexhub an den Schreibtisch-PC an, verbinden Sie den Wi‑Fi-Hotspot mit dem Telefon, das Sie bereits besitzen, und steuern Sie vom Sofa oder einem Café-Sitzplatz aus — kein sperriges Edit-Deck zum Packen. Keine Downloads oder Accounts für den täglichen Gebrauch; die App ist nur für gelegentliche Firmware-Updates gedacht.",
      "ben.b1t": "Trackpad &amp; Wireless Presenter",
      "ben.b1p": "Bewegen, klicken und scrollen Sie quer durch den Raum. Ideal als zweite Zeigefläche neben einer Hauptmaus — oder als einfacher drahtloser Präsentator — nicht als einziges Profi-Zeigegerät.",
      "ben.b2t": "Verknüpfungen &amp; Makros am Telefon",
      "ben.b2p": "Zeichnen Sie Makros auf der Wi‑Fi-Seite auf, speichern Sie sie auf dem Gerät und geben Sie sie später als Verknüpfungsaktionen wieder — Stream Deck-ähnliche Verknüpfungen, ohne ein weiteres Deck zu kaufen.",
      "ben.b3t": "Gelegentliche Anmerkungen, Unterschriften &amp; Kritzeleien",
      "ben.b3p": "Ideal für PDF Markup, Vertragsunterschriften, Kinderkritzeleien und Anfänger-Skizzen.",
      "dev.title": "Funktioniert mit dem, was Sie bereits haben",
      "dev.lead": "Handys, Tablets und Computer — neu oder alt. Das Ersatztelefon in der Schublade wird zu einem praktischen Verknüpfungsfeld.",
      "dev.phone": "Telefone",
      "dev.tablet": "Tabletten",
      "dev.computer": "Computer",
      "ben.bonusT": "Kleiner Bonus: eine Ersatzfernbedienung",
      "ben.bonusP": "Fernbedienung unter den Kissen? Ihr Telefon kann einfache TV-Box-Tipps abdecken, während Sie schauen. Nice to have — Flexhubs eigentliche Aufgabe sind Verknüpfungen, Zeigen und leichte Berührungen am PC.",
      "how.kicker": "So funktioniert es",
      "how.title": "In weniger als einer Minute fertig.",
      "how.lead": "Nichts zum Herunterladen, nichts zum Anmelden. Wenn Sie einen USB-Stick anschließen oder Bluetooth-Kopfhörer anschließen können, sind Sie startklar.",
      "how.s1t": "Schließen Sie es an — oder koppeln Sie es",
      "how.s1p": "Verbinden Sie Flexhub mit dem Gerät, das Sie mit einem USB-Kabel steuern möchten, oder schalten Sie es einfach ein und koppeln Sie es über Bluetooth.",
      "how.s2t": "Öffnen Sie Ihr Gerät",
      "how.s2p": "Schließen Sie sich auf Ihrem Telefon, Tablet oder Computer dem Wi-Fi mit dem Namen flexhub (Passwort build.me) an und öffnen Sie http://flexhub.local/ oder http://192.168.4.1/ im Browser — keine App erforderlich, das war 's.",
      "how.s3t": "Tastenkombinationen, Punkt, Typ, leichte Berührung",
      "how.s3p": "Feuern Sie Makros und Tastenkombinationen ab, bewegen Sie den Zeiger, tippen Sie ein paar Wörter oder kommentieren Sie einen PDF — wechseln Sie, wann immer Sie möchten, von wo immer Sie es bequem haben.",
      "how.noteT": "Die einzige Zeit, in der Sie eine App benötigen: Updates",
      "how.noteP": "Ab und zu können wir Verbesserungen für Flexhub veröffentlichen. Das ist der eine Moment, in dem du unsere App nutzen wirst — öffne sie, tippe auf Update, fertig. Tag für Tag kann man vergessen, dass es sie gibt.",
      "quote.text": "Verknüpfungen. Punkt. Typ. Leichte Berührung — vom Telefon in der Hand.",
      "quote.by": "Ein tragbares Lichtwerkzeug für alltägliche, nicht-professionelle und Second-Screen-Setups.",
      "buy.kicker": "Demnächst",
      "buy.title": "Ein kleiner Stecker. Ein Ersatztelefon erledigt den Rest.",
      "buy.lead": "Flexhub wird in Kürze bei visualbuild.shop verfügbar sein. Preis- und Versanddetails sind auf dem Weg — schau in Kürze wieder vorbei!",
      "buy.priceNote": "Preis folgt in Kürze",
      "buy.cta": "Demnächst",
      "buy.fine": "Sicherer Check-out am visualbuild.shop",
      "faq.kicker": "FAQ",
      "faq.title": "Gute Fragen, schnelle Antworten",
      "faq.q0": "Muss ich eine App herunterladen?",
      "faq.a0": "Nicht für den täglichen Gebrauch — Verknüpfungen, Zeigen, Tippen und leichte Anmerkungen, ohne etwas zu installieren. Du brauchst unsere App nur, wenn du Flexhub aktualisieren möchtest, und das dauert nur ein paar Fingertipps.",
      "faq.q1": "Welche Geräte funktionieren?",
      "faq.a1": "Handys, Tablets und Computer — fast alles mit einem Webbrowser, alt oder neu. Selbst ein Telefon, das keine Updates mehr erhält, funktioniert hervorragend als drahtloses Verknüpfungsfeld — zum Beispiel ein Apple iPad mini der ersten Generation.",
      "faq.q2": "Kann ich es zum Zeichnen verwenden?",
      "faq.a2": "Für leichten, gelegentlichen Gebrauch — ja: PDF Anmerkungen, Vertragsunterschriften, Kinderkritzeleien und Anfängerkritzeleien. Keine Druckstufen — keine Wacom-Tablette.",
      "faq.q3": "Kann ich zwischen Maus, Tastatur und Zeichnung wechseln?",
      "faq.a3": "Jederzeit. Feuern Sie eine Verknüpfung, bewegen Sie den Zeiger, geben Sie ein paar Wörter ein und kommentieren Sie dann — alles vom selben Gerät aus, mit einem einzigen Tippen zum Umschalten.",
      "faq.q4": "Muss ich etwas auf dem Gerät installieren, das ich kontrolliere?",
      "faq.a4": "Nein. Egal, ob Sie sich mit einem USB-Kabel anschließen oder über Bluetooth koppeln, Flexhub wird als gewöhnliche Maus und Tastatur angezeigt. Eine App kommt nur an dem gelegentlichen Tag, an dem Sie Flexhub aktualisieren.",
      "faq.q5": "Handelt es sich um eine Fernbedienung?",
      "faq.a5": "Nur als kleines Extra. Flexhub ist für Verknüpfungen, Zeigen und leichte Berührung gedacht — aber wenn Ihre übliche Fernbedienung verschwindet, kann Ihr Telefon im Notfall helfen.",
      "faq.q6": "Wird sich dadurch etwas auf meinem Gerät ändern?",
      "faq.a6": "Nein. Ihre Fotos, Nachrichten und Dateien bleiben genau so, wie sie sind. Flexhub gibt Ihrem Gerät einfach eine weitere Möglichkeit, nützlich zu sein.",
      "nav.modes": "Zwei Verbindungsarten",
      "hero.m4": "⇄ USB oder Bluetooth · Reiseleuchte",
      "chip.modes": "USB · Bluetooth",
      "modes.kicker": "Zwei Möglichkeiten, eine Verbindung herzustellen",
      "modes.title": "Schließen Sie es an oder gehen Sie drahtlos.",
      "modes.lead": "Flexhub spricht mit dem Gerät, das Sie steuern möchten, je nachdem, wie es Ihnen passt. So oder so, Ihr Telefon, Tablet oder Computer ist derjenige in Ihrer Hand.",
      "modes.usbTag": "Mit einem Kabel",
      "modes.usbT": "Gerade einstecken (USB)",
      "modes.usbP": "Verbinden Sie Flexhub mit dem Computer, Bildschirm oder der TV-Box, die Sie mit einem USB-Datenkabel steuern möchten. Es wird sofort als Maus und Tastatur erkannt — nichts zu installieren, nichts zu koppeln.",
      "modes.usbBest": "Ideal für: Ihren Schreibtischcomputer, einen Arbeitslaptop, alles mit einem kostenlosen USB-Anschluss.",
      "modes.btTag": "Drahtlos",
      "modes.btT": "Koppeln über Bluetooth",
      "modes.btP": "Geben Sie einfach Flexhub Power — ein Handy-Ladegerät oder eine Powerbank ist perfekt. Etwa zwei Minuten nach dem Einschalten öffnen Sie die Bluetooth-Einstellungen auf dem Gerät, das Sie steuern möchten, und wählen Sie „flexhub“. Fertig!",
      "modes.btBest": "Ideal für: Tablets, TV-Boxen wie Apple TV und Geräte ohne Ersatzanschluss USB.",
      "modes.tipT": "Flexhub wählt für Sie",
      "modes.tipP": "Wenn es hochfährt, prüft Flexhub: über Kabel mit einem Gerät verbunden? Es funktioniert über USB. Nur Strom bekommen? Es wechselt zu Bluetooth. Möchten Sie es ändern? Ziehen Sie einfach den Stecker aus der Steckdose und stecken Sie es in die andere Richtung wieder ein.",
      "compare.title": "USB vs Bluetooth — auf einen Blick",
      "compare.lead": "Die gleiche sonnige Steuerung von Ihrem Telefon aus. Hier ist, was jeder Modus bringt.",
      "compare.colFeature": "Was du bekommst",
      "compare.colUsb": "USB-Modus",
      "compare.colBt": "Bluetooth-Modus",
      "compare.r0f": "So verbindet es sich",
      "compare.r0u": "USB Datenkabel in das Gerät, das Sie steuern möchten",
      "compare.r0b": "Nur Strom, dann koppeln Sie <b>flexhub</b> auf diesem Gerät",
      "compare.r1f": "Tastatur & Maus",
      "compare.r1u": "Ja — taucht sofort auf",
      "compare.r1b": "Ja — als flexhub",
      "compare.r2f": "Gamepad (DualSense & Classic BT)",
      "compare.r2u": "Ja — DualSense & klassische Bluetooth-Pads",
      "compare.r2b": "Kein Gamepad im Bluetooth-Modus",
      "compare.r3f": "Steuerung über den Browser Ihres Telefons",
      "compare.r3u": "Ja — Telefon- / Tablet- / Computer-Browser",
      "compare.r3b": "Ja — gleiche Wi‑Fi Seite",
      "compare.r4f": "Beim Einschalten",
      "compare.r4": "Auto — Datenkabel bereit? USB. Nur Strom? Bluetooth. Ziehen Sie den Netzstecker und schließen Sie ihn erneut an, um den Schalter",
      "faq.q7": "USB oder Bluetooth — was soll ich wählen?",
      "faq.a7": "Was ist am einfachsten? Hast du einen kostenlosen USB-Port? Schließen Sie sich an und Sie sind fertig. Kein Anschluss oder Steuerung eines Tablets oder einer TV-Box? Versorgen Sie Flexhub mit einem Ladegerät und koppeln Sie es über Bluetooth. Tipp: Koppeln Sie es auf dem Gerät, das Sie steuern möchten — nicht auf dem Telefon in Ihrer Hand.",
      "faq.q8": "Wie verbinde ich mich über Wi‑Fi?",
      "faq.a8": "Schließen Sie sich auf Ihrem Telefon, Tablet oder Computer dem Wi‑Fi mit dem Namen flexhub (Passwort build.me) an und öffnen Sie dann http://flexhub.local/ oder http://192.168.4.1/ im Browser. Dieser drahtlose Hotspot ist die Art und Weise, wie Flexhub mit dem Gerät in Ihrer Hand spricht — keine App Store-Installation für den täglichen Gebrauch.",
      "faq.a11": "Ja. Auf der Seite Flexhub Wi‑Fi können Sie Makros aufnehmen, auf dem Gerät speichern und später als Verknüpfungsaktionen wiedergeben.",
      "faq.q11": "Kann ich meine eigenen Tastenkombinationen und Makros festlegen?",
      "faq.a10": "Nein — und das sagen wir im Voraus. Flexhub hat keine Druckstufen. Es glänzt als leichtes Trackpad, drahtloser Präsentator, Signaturpad, Multimedia-Verknüpfungs-Controller und Makros aus Tastenkombinationen für Stream Deck-ähnliche Verknüpfungen.",
      "faq.q10": "Kann es mein Wacom-Tablet ersetzen?",
      "foot.privacy": "Datenschutz",
      "foot.terms": "AGB",
      "foot.refund": "Rückgabe",
      "foot.copy": "© 2026 Flexhub · visualbuild.shop",
    },
    "fr": {
      "skip": "Aller au contenu",
      "nav.benefits": "Ce que ça fait",
      "nav.how": "Comment ça marche",
      "nav.buy": "Acheter",
      "nav.faq": "FAQ",
      "nav.guide": "Guide",
      "how.guideT": "Envie de tous les détails ?",
      "how.guideP": "Le guide complet parcourt les deux modes pas à pas (USB et sans fil), l'appairage Bluetooth, chaque onglet de la télécommande, les macros, les réglages, les mises à jour et le dépannage — avec des démos à essayer.",
      "how.guideCta": "Ouvrir le guide →",
      "nav.cta": "Obtenir Flexhub",
      "lang.label": "Langue",
      "hero.eyebrow": "Hotspot Wi‑Fi · raccourcis · souris · annotation légère · sans app",
      "hero.title": "Ancien téléphone, nouveau rôle — raccourcis sans fil, souris et toucher léger<br><span class=\"accent\">avec le téléphone que vous avez déjà.</span>",
      "hero.lead": "Flexhub transforme un vieux téléphone ou une tablette en panneau de raccourcis sans fil pour le PC du bureau — plus trackpad, présentateur, pad de signature et outil d'annotation légère. Rejoignez le hotspot Wi‑Fi flexhub, ouvrez le navigateur — pas d'installation App Store au quotidien. Branchez Flexhub en USB (sans pilote), puis pilotez depuis le canapé.",
      "hero.ctaPrimary": "Obtenir Flexhub",
      "hero.ctaSecondary": "Voir ce qu'il peut faire",
      "hero.m0": "✓ Pas d'app au quotidien",
      "hero.m1": "⌘ Raccourcis et macros perso",
      "hero.m2": "◎ Souris secondaire / présentateur",
      "hero.m3": "✎ Signer, gribouiller, annoter un PDF",
      "hero.illustCaption": "Illustration produit Flexhub",
      "chip.noapp": "Sans app",
      "chip.mouse": "Trackpad / présentateur",
      "chip.keyboard": "Raccourcis et saisie",
      "chip.draw": "Annotation légère",
      "chip.devices": "Téléphone · tablette · ordinateur",
      "ben.kicker": "Ce que ça fait",
      "ben.title": "Un outil léger et portable.",
      "ben.f1t": "Sans pilote. Léger en voyage.",
      "ben.f1p": "Branchez Flexhub sur le PC, rejoignez son hotspot Wi‑Fi avec le téléphone que vous avez déjà, et contrôlez depuis le canapé ou un café — sans deck d'édition encombrant. Pas de téléchargement ni de compte au quotidien ; l'app sert seulement aux mises à jour firmware occasionnelles.",
      "ben.b1t": "Trackpad et présentateur sans fil",
      "ben.b1p": "Bougez, cliquez et faites défiler à distance. Idéal comme second pointeur à côté de la souris principale — ou comme présentateur simple — pas comme seul périphérique pro.",
      "ben.b2t": "Raccourcis et macros sur le téléphone",
      "ben.b2p": "Enregistrez des macros sur la page Wi‑Fi, enregistrez-les sur l'appareil, puis rejouez-les comme des raccourcis — style Stream Deck sans racheter un deck.",
      "ben.b3t": "Annoter, signer et gribouiller de temps en temps",
      "ben.b3p": "Parfait pour annoter un PDF, signer un contrat, les gribouillis des enfants et les croquis débutants.",
      "dev.title": "Fonctionne avec ce que vous avez déjà",
      "dev.lead": "Téléphones, tablettes et ordinateurs — neufs ou anciens. Ce téléphone au fond du tiroir devient un panneau de raccourcis pratique.",
      "dev.phone": "Téléphones",
      "dev.tablet": "Tablettes",
      "dev.computer": "Ordinateurs",
      "ben.bonusT": "Petit bonus : une télécommande de secours",
      "ben.bonusP": "Télécommande sous les coussins ? Votre téléphone peut couvrir quelques appuis simples sur le box TV pendant que vous cherchez. Sympa à avoir — le vrai métier de Flexhub, ce sont les raccourcis, le pointage et le toucher léger sur le PC.",
      "how.kicker": "Comment ça marche",
      "how.title": "Prêt en moins d'une minute.",
      "how.lead": "Rien à télécharger, rien à créer. Si vous savez brancher une clé USB ou appairer des écouteurs Bluetooth, vous êtes prêt.",
      "how.s1t": "Branchez — ou appairer",
      "how.s1p": "Connectez Flexhub à l'appareil à contrôler avec un câble USB, ou alimentez-le simplement et appairer en Bluetooth.",
      "how.s2t": "Ouvrez votre appareil",
      "how.s2p": "Sur votre téléphone, tablette ou ordinateur, rejoignez le Wi‑Fi nommé flexhub (mot de passe build.me) et ouvrez http://flexhub.local/ ou http://192.168.4.1/ dans le navigateur — pas d'app, c'est tout.",
      "how.s3t": "Raccourcis, pointer, taper, toucher léger",
      "how.s3p": "Lancez macros et combos, déplacez le pointeur, tapez quelques mots, ou annotez un PDF — changez quand vous voulez, où vous êtes à l'aise.",
      "how.noteT": "Le seul moment où il faut une app : les mises à jour",
      "how.noteP": "De temps en temps, nous pouvons publier des améliorations pour Flexhub. C'est le seul moment où vous utiliserez notre app — ouvrez, appuyez sur mettre à jour, terminé. Au quotidien, vous pouvez l'oublier.",
      "quote.text": "Raccourcis. Pointer. Taper. Toucher léger — depuis le téléphone dans votre main.",
      "quote.by": "Un outil léger et portable pour le quotidien non pro et les seconds écrans.",
      "buy.kicker": "Bientôt disponible",
      "buy.title": "Une petite prise. Un vieux téléphone fait le reste.",
      "buy.lead": "Flexhub sera bientôt disponible sur visualbuild.shop. Prix et livraison arrivent — revenez bientôt !",
      "buy.priceNote": "Prix bientôt annoncé",
      "buy.cta": "Bientôt",
      "buy.fine": "Paiement sécurisé sur visualbuild.shop",
      "faq.kicker": "FAQ",
      "faq.title": "Bonnes questions, réponses rapides",
      "faq.q0": "Faut-il télécharger une app ?",
      "faq.a0": "Pas pour le quotidien — raccourcis, pointage, saisie et annotation légère sans rien installer. Vous n'aurez besoin de notre app que pour mettre à jour Flexhub, en quelques taps.",
      "faq.q1": "Quels appareils fonctionnent ?",
      "faq.a1": "Téléphones, tablettes et ordinateurs — presque tout avec un navigateur, neuf ou ancien. Même un téléphone qui ne reçoit plus de mises à jour marche très bien comme panneau de raccourcis — par exemple un iPad mini de première génération.",
      "faq.q2": "Puis-je l'utiliser pour dessiner ?",
      "faq.a2": "Pour un usage léger et occasionnel — oui : annoter un PDF, signer un contrat, gribouillis d'enfants et croquis débutants. Pas de niveaux de pression — ce n'est pas une tablette Wacom.",
      "faq.q3": "Puis-je passer de souris, clavier et dessin ?",
      "faq.a3": "À tout moment. Lancez un raccourci, bougez le pointeur, tapez quelques mots, puis annotez — le tout sur le même appareil, en un tap pour changer.",
      "faq.q4": "Faut-il installer quelque chose sur l'appareil contrôlé ?",
      "faq.a4": "Non. Que vous branchiez en USB ou appairiez en Bluetooth, Flexhub apparaît comme une souris et un clavier ordinaires. Une app n'intervient que le jour occasionnel où vous mettez Flexhub à jour.",
      "faq.q5": "Est-ce une télécommande ?",
      "faq.a5": "Seulement en petit plus. Flexhub est fait pour les raccourcis, le pointage et le toucher léger — mais si la télécommande habituelle disparaît, votre téléphone peut dépanner.",
      "faq.q6": "Ça change quelque chose sur mon appareil ?",
      "faq.a6": "Non. Photos, messages et fichiers restent tels quels. Flexhub donne juste une utilité de plus à votre appareil.",
      "nav.modes": "Deux façons de se connecter",
      "hero.m4": "⇄ USB ou Bluetooth · léger en voyage",
      "chip.modes": "USB · Bluetooth",
      "modes.kicker": "Deux façons de se connecter",
      "modes.title": "Branchez, ou passez en sans fil.",
      "modes.lead": "Flexhub parle à l'appareil à contrôler comme vous préférez. Dans les deux cas, c'est votre téléphone, tablette ou ordinateur que vous tenez.",
      "modes.usbTag": "Avec un câble",
      "modes.usbT": "Branchez directement (USB)",
      "modes.usbP": "Connectez Flexhub à l'ordinateur, l'écran ou le box TV à contrôler avec un câble USB données. Il est reconnu tout de suite comme souris et clavier — rien à installer, rien à appairer.",
      "modes.usbBest": "Idéal pour : le PC de bureau, un laptop pro, tout appareil avec un port USB libre.",
      "modes.btTag": "Sans fil",
      "modes.btT": "Appairage Bluetooth",
      "modes.btP": "Alimentez simplement Flexhub — chargeur téléphone ou power bank. Environ deux minutes après la mise sous tension, ouvrez les réglages Bluetooth sur l'appareil à contrôler et choisissez « flexhub ». Et voilà !",
      "modes.btBest": "Idéal pour : tablettes, box TV comme Apple TV, et appareils sans port USB libre.",
      "modes.tipT": "Flexhub choisit pour vous",
      "modes.tipP": "À l'allumage, Flexhub vérifie : câble données vers un appareil ? Mode USB. Seulement de l'alimentation ? Bluetooth. Pour changer : débranchez et rebranchez autrement.",
      "compare.title": "USB vs Bluetooth — en un coup d'œil",
      "compare.lead": "Le même contrôle depuis votre téléphone dans les deux cas. Voici ce qu'apporte chaque mode.",
      "compare.colFeature": "Ce que vous obtenez",
      "compare.colUsb": "Mode USB",
      "compare.colBt": "Mode Bluetooth",
      "compare.r0f": "Comment ça se connecte",
      "compare.r0u": "Câble USB données vers l'appareil à contrôler",
      "compare.r0b": "Alimentation seule, puis appairer <b>flexhub</b> sur cet appareil",
      "compare.r1f": "Clavier et souris",
      "compare.r1u": "Oui — apparaît tout de suite",
      "compare.r1b": "Oui — sous le nom flexhub",
      "compare.r2f": "Manette (DualSense et BT classique)",
      "compare.r2u": "Oui — DualSense et manettes Bluetooth classiques",
      "compare.r2b": "Pas de manette en mode Bluetooth",
      "compare.r3f": "Contrôle depuis le navigateur du téléphone",
      "compare.r3u": "Oui — navigateur téléphone / tablette / ordinateur",
      "compare.r3b": "Oui — même page Wi‑Fi",
      "compare.r4f": "À l'allumage",
      "compare.r4": "Auto — câble données prêt ? USB. Seulement l'alim ? Bluetooth. Débranchez et rebranchez pour changer.",
      "faq.q7": "USB ou Bluetooth — lequel choisir ?",
      "faq.a7": "Le plus simple ! Un port USB libre ? Branchez, c'est fait. Pas de port, ou contrôle d'une tablette / box TV ? Alimentez Flexhub avec un chargeur et appairer en Bluetooth. Astuce : appairer sur l'appareil à contrôler — pas sur le téléphone dans votre main.",
      "faq.q8": "Comment se connecter en Wi‑Fi ?",
      "faq.a8": "Sur votre téléphone, tablette ou ordinateur, rejoignez le Wi‑Fi nommé flexhub (mot de passe build.me), puis ouvrez http://flexhub.local/ ou http://192.168.4.1/ dans le navigateur. Ce hotspot est la façon dont Flexhub parle à l'appareil dans votre main — pas d'App Store au quotidien.",
      "faq.a11": "Oui. Sur la page Wi‑Fi Flexhub vous pouvez enregistrer des macros, les sauver sur l'appareil, et les rejouer plus tard comme des raccourcis.",
      "faq.q11": "Puis-je définir mes propres raccourcis et macros ?",
      "faq.a10": "Non — et on le dit clairement. Flexhub n'a pas de niveaux de pression. Il brille comme trackpad léger, présentateur sans fil, pad de signature, contrôleur multimédia, et macros de combos façon Stream Deck.",
      "faq.q10": "Peut-il remplacer ma tablette Wacom ?",
      "foot.privacy": "Confidentialité",
      "foot.terms": "Conditions",
      "foot.refund": "Remboursements",
      "foot.copy": "© 2026 Flexhub · visualbuild.shop",
    },
    "ja": {
      "skip": "コンテンツへスキップ",
      "nav.benefits": "できること",
      "nav.how": "使い方",
      "nav.buy": "購入",
      "nav.faq": "FAQ",
      "nav.guide": "ガイド",
      "how.guideT": "もっと詳しく知りたい？",
      "how.guideP": "完全ガイドでは、USB / ワイヤレスの両モード、Bluetooth ペアリング、リモコンの各タブ、マクロ、設定、更新、トラブルシューティングを手順ごとに案内します。タップして試せるデモ付きです。",
      "how.guideCta": "ガイドを開く →",
      "nav.cta": "Flexhub を入手",
      "lang.label": "言語",
      "hero.eyebrow": "Wi‑Fi ホットスポット · ショートカット · マウス · 軽い注釈 · アプリ不要",
      "hero.title": "古いスマホに新しい仕事を — ワイヤレスショートカット、マウス、軽いタッチ<br><span class=\"accent\">手元のスマホそのままで。</span>",
      "hero.lead": "Flexhub は古いスマホやタブレットを、デスク PC 向けの手頃なワイヤレスショートカットパネルに変えます。トラックパッド、プレゼンター、署名パッド、軽い注釈ツールも。flexhub の Wi‑Fi ホットスポットに接続してブラウザを開くだけ — 日常利用に App Store のインストールは不要。Flexhub を PC に USB（ドライバ不要）で挿し、ソファからスマホで操作できます。",
      "hero.ctaPrimary": "Flexhub を入手",
      "hero.ctaSecondary": "できることを見る",
      "hero.m0": "✓ 日常利用にアプリ不要",
      "hero.m1": "⌘ カスタムショートカットとマクロ",
      "hero.m2": "◎ サブマウス / プレゼンター",
      "hero.m3": "✎ 署名、落書き、PDF 注釈",
      "hero.illustCaption": "Flexhub 製品イラスト",
      "chip.noapp": "アプリ不要",
      "chip.mouse": "トラックパッド / プレゼン",
      "chip.keyboard": "ショートカットと入力",
      "chip.draw": "軽い注釈",
      "chip.devices": "スマホ · タブレット · パソコン",
      "ben.kicker": "できること",
      "ben.title": "持ち運べる軽量ツール。",
      "ben.f1t": "ドライバ不要。旅も軽く。",
      "ben.f1p": "Flexhub をデスク PC に挿し、手元のスマホでその Wi‑Fi ホットスポットに接続すれば、ソファやカフェから操作できます — 大きな編集デッキは不要。日常はダウンロードもアカウントも不要。アプリはたまに行うファームウェア更新のときだけ。",
      "ben.b1t": "トラックパッドとワイヤレスプレゼンター",
      "ben.b1p": "離れた場所から移動・クリック・スクロール。メインマウスの隣の第二ポインタや、シンプルなワイヤレスプレゼンターに最適 — 唯一のプロ用ポインティングデバイスとしては想定していません。",
      "ben.b2t": "スマホ上のショートカットとマクロ",
      "ben.b2p": "Wi‑Fi ページでマクロを録画し、端末に保存して後からショートカットのように再生 — 新しいデッキを買わずに Stream Deck 風の操作ができます。",
      "ben.b3t": "ときどき注釈、署名、落書き",
      "ben.b3p": "PDF の書き込み、契約書の署名、子どもの落書き、入門スケッチにぴったり。",
      "dev.title": "すでに持っている機器で使えます",
      "dev.lead": "スマホ、タブレット、パソコン — 新旧問いません。引き出しの予備スマホが便利なショートカットパネルになります。",
      "dev.phone": "スマホ",
      "dev.tablet": "タブレット",
      "dev.computer": "パソコン",
      "ben.bonusT": "ちょっとしたおまけ：予備リモコン",
      "ben.bonusP": "リモコンがクッションの下？ 探しているあいだ、スマホで TV ボックスの簡単な操作をカバーできます。あると便利 — Flexhub の本業は PC 上のショートカット、ポインタ、軽いタッチです。",
      "how.kicker": "使い方",
      "how.title": "1 分以内に準備完了。",
      "how.lead": "ダウンロードも登録も不要。USB メモリを挿せたり Bluetooth イヤホンを繋げたりできれば大丈夫。",
      "how.s1t": "挿す — またはペアリング",
      "how.s1p": "制御したい機器に USB ケーブルで Flexhub を繋ぐか、電源だけ入れて Bluetooth でペアリングします。",
      "how.s2t": "デバイスを開く",
      "how.s2p": "スマホ、タブレット、パソコンで flexhub という Wi‑Fi（パスワード build.me）に接続し、ブラウザで http://flexhub.local/ または http://192.168.4.1/ を開く — アプリ不要、それで完了。",
      "how.s3t": "ショートカット、ポインタ、入力、軽いタッチ",
      "how.s3p": "マクロやキーコンボを実行し、ポインタを動かし、数語入力し、PDF に注釈 — 居心地のよい場所からいつでも切り替え。",
      "how.noteT": "アプリが必要な唯一の瞬間：更新",
      "how.noteP": "ときどき Flexhub の改善を公開します。そのときだけアプリを使い — 開いて更新をタップすれば完了。日常は忘れても大丈夫。",
      "quote.text": "ショートカット。ポインタ。入力。軽いタッチ — 手元のスマホから。",
      "quote.by": "日常の非プロ用途やサブ画面向けの、持ち運べる軽量ツール。",
      "buy.kicker": "近日公開",
      "buy.title": "小さなプラグひとつ。あとは予備のスマホ。",
      "buy.lead": "Flexhub はまもなく visualbuild.shop で購入できます。価格と配送情報も近日公開 — しばらくしてまたチェックを！",
      "buy.priceNote": "価格は近日発表",
      "buy.cta": "近日公開",
      "buy.fine": "visualbuild.shop で安全に決済",
      "faq.kicker": "FAQ",
      "faq.title": "よい質問に、短い答え",
      "faq.q0": "アプリのダウンロードは必要？",
      "faq.a0": "日常利用には不要 — ショートカット、ポインタ、入力、軽い注釈は何も入れずに使えます。Flexhub を更新したいときだけアプリが必要で、数タップで済みます。",
      "faq.q1": "どの機器で使える？",
      "faq.a1": "スマホ、タブレット、パソコン — ブラウザがあるものならほぼどれでも、新旧問いません。更新が止まった古いスマホでも、ワイヤレスショートカットパネルとして十分使えます。例：初代 Apple iPad mini。",
      "faq.q2": "お絵かきに使える？",
      "faq.a2": "軽い・たまの用途なら — はい：PDF 注釈、契約署名、子どもの落書き、入門スケッチ。筆圧レベルはありません — Wacom タブレットではありません。",
      "faq.q3": "マウス、キーボード、描画を切り替えられる？",
      "faq.a3": "いつでも。ショートカットを打ち、ポインタを動かし、数語入力してから注釈 — 同じ端末で、タップ一つで切り替え。",
      "faq.q4": "制御する側の機器に何か入れる必要は？",
      "faq.a4": "不要です。USB で挿しても Bluetooth でペアしても、Flexhub は普通のマウスとキーボードとして認識されます。アプリが出てくるのは、たまに Flexhub を更新する日だけ。",
      "faq.q5": "リモコンなの？",
      "faq.a5": "おまけ程度です。Flexhub はショートカット、ポインタ、軽いタッチ向け — ただしいつものリモコンが見当たらないとき、スマホが助けになります。",
      "faq.q6": "端末の中身は変わる？",
      "faq.a6": "いいえ。写真、メッセージ、ファイルはそのまま。Flexhub は端末の使い道を一つ増やすだけです。",
      "nav.modes": "二つの接続方法",
      "hero.m4": "⇄ USB または Bluetooth · 旅も軽く",
      "chip.modes": "USB · Bluetooth",
      "modes.kicker": "二つの接続方法",
      "modes.title": "挿すか、ワイヤレスか。",
      "modes.lead": "Flexhub は、制御したい機器へあなたに合う方法で話します。どちらでも、手元にあるのは自分のスマホ、タブレット、パソコンです。",
      "modes.usbTag": "ケーブルあり",
      "modes.usbT": "そのまま挿す（USB）",
      "modes.usbP": "制御したいパソコン、画面、TV ボックスに USB データケーブルで Flexhub を接続。すぐにマウスとキーボードとして認識 — インストールもペアリングも不要。",
      "modes.usbBest": "向いている用途：デスクのパソコン、仕事用ノート、空き USB ポートがある機器。",
      "modes.btTag": "ワイヤレス",
      "modes.btT": "Bluetooth ペアリング",
      "modes.btP": "Flexhub に電源を入れるだけ — スマホ充電器やモバイルバッテリーで十分。通電から約 2 分後、制御したい機器の Bluetooth 設定を開き「flexhub」を選択。完了！",
      "modes.btBest": "向いている用途：タブレット、Apple TV などの TV ボックス、空き USB がない機器。",
      "modes.tipT": "Flexhub が自動で選びます",
      "modes.tipP": "電源投入時、Flexhub は確認します：データケーブルで機器に繋がっている？ → USB。電源だけ？ → Bluetooth。切り替えたいときは抜き、別のつなぎ方で挿し直してください。",
      "compare.title": "USB と Bluetooth — 一覧",
      "compare.lead": "どちらでもスマホから同じように操作。各モードの違いです。",
      "compare.colFeature": "できること",
      "compare.colUsb": "USB モード",
      "compare.colBt": "Bluetooth モード",
      "compare.r0f": "接続方法",
      "compare.r0u": "制御したい機器へ USB データケーブル",
      "compare.r0b": "電源のみ、その機器で <b>flexhub</b> をペア",
      "compare.r1f": "キーボードとマウス",
      "compare.r1u": "あり — すぐに表示",
      "compare.r1b": "あり — 名前は flexhub",
      "compare.r2f": "ゲームパッド（DualSense とクラシック BT）",
      "compare.r2u": "あり — DualSense とクラシック Bluetooth パッド",
      "compare.r2b": "Bluetooth モードではゲームパッドなし",
      "compare.r3f": "スマホのブラウザから操作",
      "compare.r3u": "あり — スマホ / タブレット / パソコンのブラウザ",
      "compare.r3b": "あり — 同じ Wi‑Fi ページ",
      "compare.r4f": "電源投入時",
      "compare.r4": "自動 — データケーブル準備OK？ USB。電源だけ？ Bluetooth。抜き差しで切り替え。",
      "faq.q7": "USB と Bluetooth、どちらを選ぶ？",
      "faq.a7": "簡単な方で！ 空き USB ポートがある？ 挿せば完了。ポートがない、またはタブレットや TV ボックスを制御？ 充電器で Flexhub に給電し Bluetooth でペア。ヒント：ペアするのは制御したい機器 — 手元のスマホではありません。",
      "faq.q8": "Wi‑Fi でどう繋ぐ？",
      "faq.a8": "スマホ、タブレット、パソコンで flexhub という Wi‑Fi（パスワード build.me）に接続し、ブラウザで http://flexhub.local/ または http://192.168.4.1/ を開きます。このホットスポットが Flexhub と手元端末の対話手段 — 日常に App Store は不要です。",
      "faq.a11": "はい。Flexhub の Wi‑Fi ページでマクロを録画し、端末に保存して、あとからショートカットのように再生できます。",
      "faq.q11": "自分のショートカットキーやマクロを設定できる？",
      "faq.a10": "いいえ — 先にそう言います。Flexhub に筆圧レベルはありません。軽いトラックパッド、ワイヤレスプレゼンター、署名パッド、マルチメディアショートカット、キーコンボから作る Stream Deck 風マクロが得意です。",
      "faq.q10": "Wacom タブレットの代わりになる？",
      "foot.privacy": "プライバシー",
      "foot.terms": "利用規約",
      "foot.refund": "返金",
      "foot.copy": "© 2026 Flexhub · visualbuild.shop",
    },
    "ko": {
      "skip": "본문으로 건너뛰기",
      "nav.benefits": "할 수 있는 일",
      "nav.how": "사용 방법",
      "nav.buy": "구매",
      "nav.faq": "FAQ",
      "nav.guide": "가이드",
      "how.guideT": "모든 세부 사항을 원하십니까?",
      "how.guideP": "전체 사용자 가이드는 단계 (USB 및 무선), Bluetooth 페어링, 모든 원격 탭, 매크로, 설정, 업데이트 및 문제 해결에 의해 두 가지 모드를 통해 걸린다. 탭 - 투 - 트리 데모.",
      "how.guideCta": "사용자 가이드 열기 →",
      "nav.cta": "Flexhub 받기",
      "lang.label": "언어",
      "hero.eyebrow": "Wi‑Fi 핫스팟 · 단축키 · 마우스 · 가벼운 주석 · 앱 없음",
      "hero.title": "오래된 폰, 새 일자리 — 무선 단축키·마우스·가벼운 터치<br><span class=\"accent\">이미 있는 폰으로.</span>",
      "hero.lead": "Flexhub는 오래된 폰이나 태블릿을 책상 PC용 저렴한 무선 단축 패널로 바꿉니다. 트랙패드, 프레젠터, 서명 패드, 가벼운 주석 도구까지. flexhub Wi‑Fi 핫스팟에 접속해 브라우저만 열면 됩니다 — 일상 사용에 App Store 설치는 필요 없습니다. Flexhub를 PC에 USB(드라이버 없음)로 꽂고, 소파에서 폰으로 조종하세요.",
      "hero.ctaPrimary": "Flexhub 받기",
      "hero.ctaSecondary": "무엇을 할 수 있는지 보기",
      "hero.m0": "✓ 매일 사용을위한 앱 없음",
      "hero.m1": "⌘ 사용자 정의 단축키 &amp; 매크로",
      "hero.m2": "◎ 보조 쥐/현재",
      "hero.m3": "✎ 표시, doodle, PDF 주석",
      "hero.illustCaption": "Flexhub 제품 삽화",
      "chip.noapp": "앱 없음",
      "chip.mouse": "트랙패드/현재",
      "chip.keyboard": "단축키 &amp; 유형",
      "chip.draw": "빛 annotate",
      "chip.devices": "전화 · 태블릿 · 컴퓨터",
      "ben.kicker": "그것은 무엇입니까?",
      "ben.title": "휴대용 가벼운 도구.",
      "ben.f1t": "드라이버 무료. 여행 빛.",
      "ben.f1p": "책상 PC에 Flexhub를 플러그 앤 플레이하면 전화기의 Wi-Fi 핫스팟에 가입하고 소파 또는 카페 시트에서 제어 할 수 있습니다. 부피가 큰 편집 데크가 없습니다. 매일 사용을위한 다운로드 또는 계정이 없습니다. 앱은 가끔 펌웨어 업데이트에만 사용됩니다.",
      "ben.b1t": "Trackpad &amp; 무선 선물",
      "ben.b1p": "방 전체에 이동, 클릭 및 스크롤. 주요 마우스 옆에 두 번째 포인팅 표면과 이상 - 또는 간단한 무선 레귤레이터로 - 뿐만 아니라 프로 포인팅 장치.",
      "ben.b2t": "Shortcuts &amp; 휴대 전화에 매크로",
      "ben.b2p": "Wi-Fi 페이지의 기록 매크로는 장치로 저장하고 나중에 단축키처럼 동작합니다. Stream Deck와 같은 단축키는 다른 데크를 구입하지 않고 있습니다.",
      "ben.b3t": "Occasional 주석, 기호 &amp; doodle",
      "ben.b3p": "PDF 마크 업, 계약 서명, 아이의 doodles 및 초보자 스케치에 대 한 좋은.",
      "dev.title": "당신이 이미 가지고있는 일에",
      "dev.lead": "전화, 태블릿 및 컴퓨터 — 새로운 또는 오래된. 서랍에 휴대 전화가 편리한 단축 패널이됩니다.",
      "dev.phone": "전화 번호",
      "dev.tablet": "기타 제품",
      "dev.computer": "컴퓨터",
      "ben.bonusT": "작은 보너스 : 여분의 리모트",
      "ben.bonusP": "방석의 밑에 리모트? 휴대 전화는 간단한 TV 박스 탭을 커버 할 수 있습니다. 좋은 - Flexhub의 실제 작업은 PC에 단축키, 포인팅 및 라이트 터치입니다.",
      "how.kicker": "어떻게 작동합니까?",
      "how.title": "1분 안에 준비 완료.",
      "how.lead": "다운로드 할 수 없습니다. USB 스틱에 플러그 또는 Bluetooth 헤드폰을 연결하면 모든 세트가 있습니다.",
      "how.s1t": "플러그인 — 또는 쌍",
      "how.s1p": "Flexhub를 USB 케이블로 제어하려는 장치에 Flexhub를 연결하거나 Bluetooth 이상 전원을 켜고 쌍하십시오.",
      "how.s2t": "당신의 장치를 열기",
      "how.s2p": "휴대 전화, 태블릿 또는 컴퓨터에서 Wi-Fi 이름을 flexhub (password build.me)에 가입하고 브라우저에서 http://flexhub.local/ 또는 http://192.168.4.1/를 엽니 다 - 응용 프로그램이 필요하지 않습니다.",
      "how.s3t": "단축키, 점, 유형, 빛 접촉",
      "how.s3p": "화재 매크로와 키 콤보, 포인터를 이동, 몇 단어를 입력, 또는 PDF를 할당 — 당신이 comfy 어디를 좋아하는 때마다 스위치.",
      "how.noteT": "앱이 필요한 유일한 시간: 업데이트",
      "how.noteP": "종종 Flexhub에 대한 개선을 해제 할 수 있습니다. 그것은 당신이 우리의 응용 프로그램을 사용할 수있는 한 순간입니다 — 그것을 열, 탭 업데이트, 완료. 일, 당신은 그것을 잊을 수 있습니다.",
      "quote.text": "바로가기 지점. 유형. 라이트 터치 - 휴대 전화에서 손.",
      "quote.by": "매일 비프로 및 두 번째 화면 설정을위한 휴대용 조명 도구.",
      "buy.kicker": "곧 출시",
      "buy.title": "1개의 작은 마개. 휴대폰은 나머지입니다.",
      "buy.lead": "Flexhub는 visualbuild.shop에서 아주 빨리 유효할 것입니다. 가격 및 배송 세부 사항은 길에 있습니다. — 곧 확인!",
      "buy.priceNote": "곧 출시",
      "buy.cta": "곧 출시",
      "buy.fine": "visualbuild.shop에 안전한 체크 아웃",
      "faq.kicker": "제품 정보",
      "faq.title": "좋은 질문, 빠른 답변",
      "faq.q0": "앱을 다운로드해야 하나요?",
      "faq.a0": "일상적인 사용의 경우 — 단축키, 포인팅, 태핑 및 빛은 아무것도 설치하지 않고. Flexhub를 업데이트 할 때 앱만 필요하며 몇 번 탭이 걸립니다.",
      "faq.q1": "어떤 장치가 작동합니까?",
      "faq.a1": "전화, 태블릿 및 컴퓨터 - 웹 브라우저, 오래된 또는 새로운 거의 아무것도. 더 이상 업데이트가 작동하지 않는 전화는 무선 단축키 패널 - 예를 들어, 최초의 Apple iPad 미니.",
      "faq.q2": "그림을 위해 그것을 사용할 수 있습니까?",
      "faq.a2": "빛의 경우, 가끔 사용 — 예: PDF annotate, 계약 서명, 아이의 doodles 및 초보자 doodles. Wacom 태블릿이 아닌 압력 수준이 없습니다.",
      "faq.q3": "쥐, 키보드 및 그림 사이 전환할 수 있습니까?",
      "faq.a3": "시간. 단축키를 불, 포인터를 이동, 몇 단어를 입력, 다음 annotate — 모두 같은 장치에서, 하나의 탭으로 전환합니다.",
      "faq.q4": "나는 장치에서 아무것도 설치할 필요가 있습니까?",
      "faq.a4": "노프. USB 케이블 또는 Bluetooth, Flexhub를 통해 쌍으로 플러그가 일반 마우스와 키보드로 표시됩니다. 앱은 때때로 제공됩니다. Flexhub를 업데이트하십시오.",
      "faq.q5": "원격 제어입니까?",
      "faq.a5": "약간의 추가. Flexhub는 shortcuts, pointing 및 light touch를 위해 만들어졌습니다 — 그러나 당신의 보통 리모트가 누락되는 경우에, 당신의 전화는 pinch에서 도울 수 있습니다.",
      "faq.q6": "기기에서 아무것도 변경할 수 있습니까?",
      "faq.a6": "이름 * 사진, 메시지 및 파일은 정확히 그대로 유지됩니다. Flexhub는 단순히 당신의 장치를 유용한 한 더 많은 방법을 제공합니다.",
      "nav.modes": "두 가지 연결 방식",
      "hero.m4": "USB 또는 Bluetooth · 여행 빛",
      "chip.modes": "USB · Bluetooth",
      "modes.kicker": "연결할 수있는 두 가지 방법",
      "modes.title": "그것을 안으로 폐쇄하거나, 무선을 갑니다.",
      "modes.lead": "Flexhub는 어떤 방식으로 당신을 적응시키기 위하여 통제하고 싶은 장치에 이야기합니다. 어느 방법, 당신의 전화, 정제 또는 컴퓨터는 당신의 손에 있는 것입니다.",
      "modes.usbTag": "케이블로",
      "modes.usbT": "플러그 (USB)",
      "modes.usbP": "Flexhub를 컴퓨터, 화면 또는 TV 박스에 연결하면 USB 데이터 케이블로 제어 할 수 있습니다. 마우스와 키보드로 바로 인식됩니다. 설치하지 않고 쌍이 없습니다.",
      "modes.usbBest": "대 한: 책상 컴퓨터, 작업 노트북, 무료 USB 포트와 아무것도.",
      "modes.btTag": "제품정보",
      "modes.btT": "Bluetooth에 쌍",
      "modes.btP": "그냥 Flexhub 전원 - 전화 충전기 또는 전원 은행이 완벽합니다. 파워 업 후 약 2 분, 제어하고 \"flexhub\"을 선택하려는 장치에 Bluetooth 설정을 엽니 다. 이름 *",
      "modes.btBest": "중대한을 위해: 정제, Apple TV 같이 텔레비젼 상자, 및 여분 USB 항구 없는 장치.",
      "modes.tipT": "Flexhub 당신을 위해 선택합니다",
      "modes.tipP": "전원이 켜지면 Flexhub 검사 : 케이블에 연결된 장치? 그것은 USB 이상 작동합니다. 힘을 얻는? 그것은 Bluetooth로 전환합니다. 변경하시겠습니까? 그냥 그것을 제거하고 다른 방법으로 다시 연결.",
      "compare.title": "USB 대 Bluetooth — 한 눈에",
      "compare.lead": "당신의 전화에서 동일한 화창한 통제 어느 방법. 각 모드가 가져옵니다.",
      "compare.colFeature": "당신이 얻는 무엇",
      "compare.colUsb": "USB 모드",
      "compare.colBt": "Bluetooth 모드",
      "compare.r0f": "연결 방법",
      "compare.r0u": "USB 데이터 케이블 제어 장치로",
      "compare.r0b": "힘 단지, 그 장치에 <b>flexhub</b> 쌍",
      "compare.r1f": "키보드 & 쥐",
      "compare.r1u": "예 - 즉시 표시",
      "compare.r1b": "예 - flexhub로",
      "compare.r2f": "Gamepad (DualSense 및 클래식 BT)",
      "compare.r2u": "예 - DualSense 및 클래식 Bluetooth 패드",
      "compare.r2b": "Bluetooth 모드에서 게임 패드 없음",
      "compare.r3f": "휴대폰의 브라우저에서 제어",
      "compare.r3u": "예 - 전화 / 태블릿 / 컴퓨터 브라우저",
      "compare.r3b": "예 - 동일한 Wi-Fi 페이지",
      "compare.r4f": "파워 업",
      "compare.r4": "자동차 - 데이터 케이블 준비? 크기: USB. 힘만? 크기: Bluetooth. 스위치에 플러그 앤 리플러.",
      "faq.q7": "USB 또는 Bluetooth - 나는 선택해야합니까?",
      "faq.a7": "가장 쉽게! 무료 USB 포트를 제공? 로그인하고 있습니다. 항구 없음, 또는 정제 또는 텔레비젼 상자 통제? 충전기에서 전원 Flexhub와 Bluetooth에 쌍. 팁: 제어하려는 장치에 그것을 쌍 — 휴대 전화에서 당신의 손에.",
      "faq.q8": "Wi-Fi를 어떻게 연결합니까?",
      "faq.a8": "휴대 전화, 태블릿 또는 컴퓨터에서 flexhub (password build.me)라는 Wi-Fi에 가입 한 다음 브라우저에서 http://flexhub.local/ 또는 http://192.168.4.1/를 엽니 다. 즉 무선 핫스팟은 Flexhub가 당신의 손에 장치에 대해 이야기하는 방법 - 매일 사용을위한 앱 스토어 설치 없음.",
      "faq.a11": "예. Flexhub Wi-Fi 페이지에서 매크로를 기록하고 장치를 저장하고 단축키와 같은 작업을 다시 재생할 수 있습니다.",
      "faq.q11": "나는 내 자신의 단축키와 매크로를 설정할 수 있습니까?",
      "faq.a10": "아니오 — 우리는 그것을 정면이라고 말합니다. Flexhub에는 압력 수준이 없습니다. 그것은 가벼운 트랙패드, 무선 선물, 서명 패드, 멀티미디어 단축키 관제사로 빛나고, Stream Deck 같이 단축키를 위한 열쇠 combos에서 매크로.",
      "faq.q10": "Wacom 태블릿을 교체 할 수 있습니까?",
      "foot.privacy": "개인정보",
      "foot.terms": "약관",
      "foot.refund": "환불",
      "foot.copy": "Flexhub · visualbuild.shop",
    },
    "ar": {
      "skip": "تخطَّ إلى المحتوى",
      "nav.benefits": "ماذا يفعل",
      "nav.how": "كيف يعمل",
      "nav.buy": "شراء",
      "nav.faq": "الأسئلة",
      "nav.guide": "الدليل",
      "how.guideT": "هل تريد كل التفاصيل؟",
      "how.guideP": "ويسير الدليل الكامل للمستعملين عبر كلتا الوسيلتين خطوة بخطوة (xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "how.guideCta": "افتح دليل الاستخدام ←",
      "nav.cta": "احصل على Flexhub",
      "lang.label": "اللغة",
      "hero.eyebrow": "? ?",
      "hero.title": "هاتف قديم، وظيفة جديدة - اختصارات لاسلكية، فأر وملامس خفيفة </span>",
      "hero.lead": "Flexhub حول هاتف قديم أو قرص إلى لوحة قصيرة رخيصة لاسلكية لمكتبك PC - بالإضافة إلى جهاز تعقب، ومقدم، وبطاقة توقيع، وأداة شروح خفيفة. انضموا إلى الـ (xxxxxxx) و إفتحوا الـ (بروزر) Plug Flexhub into the PC over USB (driver-free), then lounge with the phone in hand.",
      "hero.ctaPrimary": "احصل على العشرون",
      "hero.ctaSecondary": "انظر ما يمكن أن تفعله",
      "hero.m0": "عدم تطبيق الاستخدام اليومي",
      "hero.m1": "⌘ Custom shortcuts &amp; macros",
      "hero.m2": "◎ الفأر الثانوي/المقدم",
      "hero.m3": "✎ Sign, doodle, PDF annotate",
      "hero.illustCaption": "Flexhub product illustration",
      "chip.noapp": "لا حاجة لذلك",
      "chip.mouse": "Trackpad/ presenter",
      "chip.keyboard": "الطرق القصيرة والنوع",
      "chip.draw": "شروح الضوء",
      "chip.devices": "جهاز الكمبيوتر",
      "ben.kicker": "ماذا تفعل؟",
      "ben.title": "أداة خفيفة محمولة",
      "ben.f1t": "بدون سائق رحلة طيران",
      "ben.f1p": "Plug Flexhub into the office PC, join its Wi-Fi hotspot on the phone you already own, and control from the sofa or a café seat — no bulky edit deck topack. No downloads or accounts for everyday use; the app is only for occasional firmware updates.",
      "ben.b1t": "مُقدِّم لاسلكي",
      "ben.b1p": "تحرّكوا، انقروا و انحنوا من الغرفة المثالية كسطح ثانٍ بجانب فأر رئيسي - أو كمقدم لاسلكي بسيط - ليس كجهاز توجيهك الوحيد",
      "ben.b2t": "Shortcuts &amp; macros on the phone",
      "ben.b2p": "Record macros on the Wi‐Fi page, save them to the tool, and replay them later as shortcut-like actions — Stream Deck -like shortcuts without buy another deck.",
      "ben.b3t": "Occasional annotate, sign &amp; doodle",
      "ben.b3p": "عظيم بالنسبة للعلامات العشرون، التوقيعات التعاقدية، الدودلزات الأطفال والرسومات الأولية.",
      "dev.title": "يعمل مع ما لديك بالفعل",
      "dev.lead": "Phones, tablets and computers - new or old. ذلك الهاتف الإحتياطي في الدرج يصبح لوحة مختصرة",
      "dev.phone": "الهواتف",
      "dev.tablet": "الجداول",
      "dev.computer": "الحواسيب",
      "ben.bonusT": "مكافأة صغيرة:",
      "ben.bonusP": "ترفيه تحت الوسائد؟ هاتفك يمكن أن يغطي الصنابير التلفزيونية البسيطة بينما تنظر ومن الجميل أن يكون - العمل الحقيقي لـ &quot; Flexhub &quot; هو اختصارات، وتوجيهات، وملامسة خفيفة على PC.",
      "how.kicker": "كيف يعمل",
      "how.title": "جاهز تحت دقيقة",
      "how.lead": "لا شيء للتحميل، لا شيء للتسجيل. إذا كنت تستطيع أن تنزل في عصا USB أو ربط XXP0x سماعات، كنت كل المجموعة.",
      "how.s1t": "اربطها او اربطها",
      "how.s1p": "إربطْ Flexhub إلى الجهازِ تُريدُ أَنْ تُسيطرَ مَع a كابل USB، أَو فقط يَقْويه فوق Bluetooth.",
      "how.s2t": "افتح جهازك",
      "how.s2p": "على هاتفك أو قرص أو كمبيوتر، انضموا إلى الـ (xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "how.s3t": "طرق، نقطة، نوع، لمسة خفيفة",
      "how.s3p": "فــي إطــار مــاكروات ومركبــات مفاتيح، حركــم المذكــر، وطبع بضع كلمات، أو شطب ×xxxxxxxxxxxxxxx، أي تبديل كلما أردت من أي مكان ترضي فيه.",
      "how.noteT": "المرة الوحيدة التي تحتاج فيها إلى تطبيق:",
      "how.noteP": "ويمكننا في كل مرة أن نصدر تحسينات لعشرين ألفا. هذه هي اللحظة الوحيدة التي ستستخدم فيها تطبيقنا افتحه، تحديثه، انتهى يوماً بعد يوم يمكنك نسيان وجوده",
      "quote.text": "طرق قصيرة نقطة. نوع. لمسة خفيفة من الهاتف في يدك",
      "quote.by": "أداة خفيفة محمولة للتجهيزات اليومية غير المحظورة والشاشة الثانية.",
      "buy.kicker": "قريباً",
      "buy.title": "قطعة صغيرة واحدة. هاتف إضافي يفعل الباقي",
      "buy.lead": "Flexhub will be available at visualbuild.shop very soon. تفاصيل الخصخصة والشحن في الطريق - تراجعوا قريبا!",
      "buy.priceNote": "السعر قادم قريبا",
      "buy.cta": "قريباً",
      "buy.fine": "مراقبة آمنة على XXP0x",
      "faq.kicker": "FAQ",
      "faq.title": "أسئلة جيدة، إجابات سريعة",
      "faq.q0": "هل أحتاج لتحميل تطبيق؟",
      "faq.a0": "ليس للاستخدام اليومي - اختصارات، اشارة، وصفة، اشارة خفيفة دون تركيب أي شيء. ولن تحتاجوا إلا إلى تطبيقنا عندما ترغبون في تحديث العشرينات من القرن العشرين، وهذا يتطلب عدداً قليلاً من الصنابير.",
      "faq.q1": "أي أجهزة تعمل؟",
      "faq.a1": "Phones, tablets and computers - almost anything with a web browser, old or new. وحتى الهاتف الذي لم يعد يحصل على آخر المستجدات يعمل بشكل رائع كفريق قصير لاسلكي - على سبيل المثال، مصغر من طراز XXP0xxxxxx20.",
      "faq.q2": "هل يمكنني استخدامها للرسم؟",
      "faq.a2": "وللضوء، الاستخدام العرضي - نعم: شروح العقد العشرون، التوقيعات، دودة الأطفال والمبتدئين. لا مستويات للضغط - ليس طاولة xxxxxx.",
      "faq.q3": "هل يمكنني التبديل بين الفأر، لوحة المفاتيح والرسم؟",
      "faq.a3": "في أي وقت أطلق طريقاً مختصراً، حرّك المُشير، طباعة بضعة كلمات، ثم شُمِّر، كلّها من نفس الجهاز، مع صنبور واحد للتبديل.",
      "faq.q4": "هل عليّ تركيب أي شيء على الجهاز الذي أتحكم به؟",
      "faq.a4": "لا وسواء دخلتم بكابل من طراز XXP2xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx تطبيق فقط يأتي في اليوم الذي تستكمل فيه العشرينات",
      "faq.q5": "هل هو جهاز التحكم عن بعد؟",
      "faq.a5": "فقط كقليل من الاضافات XXP0x مصنوعة من أجل الإختصار، الإشارة واللمسة الخفيفة - ولكن إذا كان جهازك النائي العادي مفقوداً، هاتفك يمكن أن يساعد في دبوس.",
      "faq.q6": "هل سيغير أي شيء على جهازي؟",
      "faq.a6": "لا صورك ورسائلك وملفاتك تبقى كما هي بالضبط Flexhub ببساطة تعطي جهازك طريقة أخرى لتكون مفيدة.",
      "nav.modes": "طريقتان للاتصال",
      "hero.m4": "⇄ xxxxxxxxxxxxxxxxxxxxx0x0",
      "chip.modes": "USB XXP0x",
      "modes.kicker": "طريقتان للتواصل",
      "modes.title": "اربطها أو اتجه بلا سلك",
      "modes.lead": "XXP0x يتحدث إلى الجهاز الذي تريد التحكم فيه بأي طريقة تناسبك في كلتا الحالتين، هاتفك، اللوحة أو الكمبيوتر هو الذي في يدك.",
      "modes.usbTag": "مع كابل",
      "modes.usbT": "Plug straight in (USB)",
      "modes.usbP": "اتصلي بـ (xxxxxxxxxxxxx) إلى الحاسوب أو الشاشة أو صندوق التلفزيون الذي تريدين التحكم به بكابل بيانات USB إنه مُعترف به على الفور كفئران و لوحة مفاتيح لا شيء للتركيب ولا شيء للزوجين",
      "modes.usbBest": "عظيم لـ: حاسوبك المكتبي، حاسوب محمول عمل، أي شيء مع ميناء 20xx20 مجانا.",
      "modes.btTag": "لاسلكي",
      "modes.btT": "Pair over Bluetooth",
      "modes.btP": "فقط أعطى Flexhub الطاقة - شاحن الهاتف أو بنك الطاقة مثالي. وبعد حوالي دقيقتين من بدء تشغيل الطاقة، فتح العشرون العشرينات على الجهاز الذي ترغب في السيطرة عليه واختيار &quot; العشرينات &quot; . تم!",
      "modes.btBest": "عظيم ل: أقراص، وصناديق تلفزيونية مثل XXP0x، وأجهزة بدون مرفأ XXP1x.",
      "modes.tipT": "Flexhub اختار لك",
      "modes.tipP": "عندما يُصبحُ، Flexhub يُدقّقُ: مُصَلَب إلى a جهاز بالكابلِ؟ يعمل على 20xxxx. فقط الحصول على الطاقة؟ يتحول إلى عشرين هل تريد التغيير؟ فقط أفتحه وأعيده إلى الطريق الآخر",
      "compare.title": "USB vs Bluetooth - at a glance",
      "compare.lead": "نفس التحكم المشمس من هاتفك في كلتا الحالتين إليك ما تجلبه كل طريقة",
      "compare.colFeature": "ما تحصل عليه",
      "compare.colUsb": "XXP0x",
      "compare.colBt": "XXP0x",
      "compare.r0f": "كيف يتواصل",
      "compare.r0u": "USB كابل بيانات في الجهاز الذي تريد السيطرة عليه",
      "compare.r0b": "السلطة فقط، ثم زوجين من <b>flexhubX</b> على ذلك الجهاز",
      "compare.r1f": "فأر لوحة المفاتيح",
      "compare.r1u": "نعم - يظهر على الفور",
      "compare.r1b": "نعم - flexhub",
      "compare.r2f": "Gamepad (DualSense) Class BT",
      "compare.r2u": "نعم - 20xxxxxxxxxxx",
      "compare.r2b": "No gamepad in Bluetooth mode",
      "compare.r3f": "التحكم من مصفف هاتفك",
      "compare.r3u": "نعم - الهاتف/الطاولة/الجهاز",
      "compare.r3b": "نعم - نفس الصفحة",
      "compare.r4f": "في الطاقة",
      "compare.r4": "أوتو - كابل البيانات جاهز؟ USB. القوة فقط؟ Bluetooth. اغلق و اعيد تشغيله",
      "faq.q7": "USB or Bluetooth - which should I choose?",
      "faq.a7": "مهما كان أسهل! حصلت على ميناء 20x20 مجانا؟ ادخلي وانتهيتِ لا ميناء، أو السيطرة على لوحة أو صندوق تلفزيون؟ Flexhub من شاحن وزوجها على XXP0x. ضعه على الجهاز الذي تريد التحكم به ليس على الهاتف في يدك",
      "faq.q8": "كيف أتواصل مع (واي فاي)؟",
      "faq.a8": "On your phone, tablet or computer, join the Wi‐Fi named flexhub (password build.me), then open http://flexhub.local/ or http://192.168.4.1/ in the browser. هذه البقعة الساخنة اللاسلكية هي الطريقة التي يتحدث بها Flexhub إلى الجهاز في يدك - لا توجد عبوة أبوس ستوري للاستخدام اليومي.",
      "faq.a11": "نعم في صفحة (xxxxxxx) يمكنك تسجيل (ككرو) وإنقاذهم للجهاز و إعادة تشغيلهم لاحقاً كإجراءات مختصرة",
      "faq.q11": "هل يمكنني أن أضع مفاتيح شقتي الخاصة ومفتاحي؟",
      "faq.a10": "لا - ونحن نقول ذلك في المقدمة. Flexhub has no pressure levels. إنها تشرق كجهاز تعقب خفيف، ومقدم لاسلكي، وبطاقة توقيع، وجهاز مراقبة مختصر متعددة الوسائط، وكموجات من غيبوبة رئيسية لقطع قصيرة من طراز XXP0xxx0.",
      "faq.q10": "هل يمكن أن يحل محل أقراصي العشرون؟",
      "foot.privacy": "الخصوصية",
      "foot.terms": "الشروط",
      "foot.refund": "الاسترداد",
      "foot.copy": "2026 Flexhub XXP0x",
    },
  };

const LANG_HTML = {en:"en", zh:"zh-Hans", de:"de", fr:"fr", ja:"ja", ko:"ko", ar:"ar"};
  const ALL_LANGS = ["en","zh","de","fr","ja","ko","ar"];

  function detectLang() {
    try {
      const q = new URLSearchParams(location.search).get("lang");
      if (q && ALL_LANGS.indexOf(q) >= 0) return q;
    } catch (_) {}
    try {
      const s = localStorage.getItem("flexhub_lang");
      if (s && ALL_LANGS.indexOf(s) >= 0) return s;
    } catch (_) {}
    const nav = (typeof navigator !== "undefined" && (navigator.languages && navigator.languages[0] || navigator.language) || "").toLowerCase();
    if (/^zh/.test(nav)) return "zh";
    if (/^de/.test(nav)) return "de";
    if (/^fr/.test(nav)) return "fr";
    if (/^ja/.test(nav)) return "ja";
    if (/^ko/.test(nav)) return "ko";
    if (/^ar/.test(nav)) return "ar";
    return "en";
  }

  function applyLang(lang) {
    if (ALL_LANGS.indexOf(lang) < 0) lang = "en";
    const pack = dict[lang] || dict.en;
    document.documentElement.lang = LANG_HTML[lang] || "en";
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    document.querySelectorAll("[data-i18n]").forEach((el) => {
      const key = el.getAttribute("data-i18n");
      if (pack[key] != null) el.textContent = pack[key];
    });
    document.querySelectorAll("[data-i18n-html]").forEach((el) => {
      const key = el.getAttribute("data-i18n-html");
      if (pack[key] != null) el.innerHTML = pack[key];
    });
    try { localStorage.setItem("flexhub_lang", lang); } catch (_) {}
    const sel = document.getElementById("lang");
    if (sel) sel.value = lang;
  }

  applyLang(detectLang());

  const sel = document.getElementById("lang");
  if (sel) sel.addEventListener("change", () => applyLang(sel.value));

  const c = window.SHOP_CONFIG || {};
  const p = document.querySelector("#price");
  const n = document.querySelector("#priceNote");
  const b = document.querySelector("#buyButton");
  if (p && c.price) p.textContent = c.price;
  if (n && c.priceNote) n.textContent = c.priceNote;
  if (b && c.creemCheckoutUrl) {
    b.href = c.creemCheckoutUrl;
    b.textContent = (dict[(document.documentElement.lang === "zh-Hans" ? "zh" : document.documentElement.lang)] || dict.en)["nav.cta"] || "Buy now";
    b.classList.remove("off");
  } else if (b) {
    b.addEventListener("click", (e) => e.preventDefault());
    b.style.opacity = ".55";
    b.style.pointerEvents = "none";
  }
})();
